apache/brpc

docs/cn/avalanche.md

The original hyperlink for little's law is actually for "little".

Fix the little's law's hyperlink

---

docs/cn/getting_started.md

Change doc format for Prepare deps in getting_started.md.
Signed-off-by: youji <youji@ebay.com>

change: update text format for getting_started.md

---

src/brpc/controller.cpp
src/brpc/controller.h
src/brpc/details/controller_private_accessor.h
src/brpc/policy/redis_authenticator.cpp
src/brpc/policy/redis_authenticator.h
src/brpc/policy/redis_protocol.cpp
src/brpc/socket.cpp
src/brpc/socket.h
test/brpc_redis_unittest.cpp

pipelined_count 使用了uint64的16位，考虑到单次请求中不会发特别多的命令数，使用最高位标识这次request是否添加了AUTH命令，导致影响是单次请求最大命令数从最大65535下调到32767

add redis auth.

---

CMakeLists.txt
cmake/CMakeLists.download_gtest.in
cmake/CompileProto.cmake
cmake/SetupGtest.cmake
cmake/brpc.pc.in
src/CMakeLists.txt
test/CMakeLists.txt

Improve cmake by:
- Use GNUInstallDirs to determine install directories for better compatibility
- Compile gtest as a subproject which is recommended by gtest team, instead of depending on a pre-built one.
- Add a build option to clone and compile gtest automatically
- Add a cache variable to specify a system-wide gtest source dir for those who do not want to clone
- Generate and install a pkg-config file `brpc.pc` to make depending on brpc easier with build systems that respect the xNIX-standard way (i.e. anything significant except bazel).
- Incorporate protos into cmake dependency system and compile protos at build time. Reconfiguration  no longer recompiles protos and will no longer trigger a huge recompilation.

Improve cmake

---

src/brpc/global.cpp
src/brpc/policy/consul_naming_service.cpp
src/brpc/policy/consul_naming_service.h
test/brpc_naming_service_unittest.cpp

功能点：
1. 可通过consul获取服务列表。
2. 当consul不可用时可自动降级到file naming service，当consul恢复时可自动恢复到consul naming service。主要是考虑consul不可用时，服务进程又恰好发生重启的场景。其中，服务节点列表文件也是会通过consul自动更新的，里面会保存consul不可用之前最新的下游服务节点。
设计细节：
使用Blocking Queries模式访问consul，即客户端从consul获取服务列表时都会附带当前的index以及超时时间。consul收到请求后若发现请求的index与当前index相等，则阻塞该请求，直到服务列表发生变化或超过超时时间才返回结果。

add consul naming service

---

docs/cn/thrift.md
docs/en/thrift.md
example/thrift_extension_c++/server.cpp
src/brpc/controller.h
src/brpc/details/thrift_utils.h
src/brpc/policy/thrift_protocol.cpp
src/brpc/thrift_message.cpp
src/brpc/thrift_message.h

We need to provide a way to get thrift method name in server side before Cast() was called.

Fix thrift method name issue

---

src/butil/sys_byteorder.h

1. fix issue #346  
butil/sys_byteorder.h
move #include<stdlib.h> #include<libkern/OSByteOrder.h> #include <byteswap.h> ...
out of namespace butil in case of pollute namespace.

issue#346 move #include out of namespace butil

---

src/brpc/channel.cpp
src/brpc/channel.h
src/brpc/circuit_breaker.cpp
src/brpc/circuit_breaker.h
src/brpc/controller.cpp
src/brpc/controller.h
src/brpc/socket.cpp
src/brpc/socket.h
test/brpc_naming_service_unittest.cpp

增加了CircuitBreaker：
- 每个Socket中都有一个CircuitBreaker对象
- 在ChannelOptions中新增enable_circuit_breaker开关
- Socket发现CircuitBreaker::OnCallEnd返回false之后调用SetFailed，之后由healthy check thread调用 Reset 来复位。
还存在的问题：
- 只有main socket才需要circuitbreaker，每个socket都有一个circuitbreaker是否有些浪费。
- PR中的默认参数还需要进一步调整。

Circuit breaker

---

src/brpc/policy/thrift_protocol.cpp

Compile error:
/tmp/brpc-20180926-16463-1e3avfz/brpc-a9e954879fda1c63f0f772b47d87943129e5af1f/src/brpc/policy/thrift_protocol.cpp:52:38: error: expected function body after function declarator
void bthread_assign_data(void* data) __THROW;
__THROW is only defined in glibc, which cannot be used in non-glibc systems.
As none of the other protocol uses __THROW for the same function, I assume it is safe to remove
(or replace it with 'noexcept' specifier in standard C++11).

Fix compile error in thrift_protocol.cpp under macOS

---

Makefile

High version protobuf (like 3.6.0) will generate c++11 code.

Makefile: fix for high version protobuf

---

src/butil/files/dir_reader_posix.h
src/butil/files/dir_reader_unix.h

1. braft relies on the interface DirReaderPosix's implementation
2. the default DirReaderFallback is empty in OSX

make braft work in mac OSX

---

src/brpc/builtin/connections_service.cpp
src/brpc/circuit_breaker.cpp
src/brpc/circuit_breaker.h
src/brpc/controller.cpp
src/brpc/socket.cpp
src/brpc/socket.h
test/brpc_circuit_breaker_unittest.cpp

在SharedPart统计了每个Socket的出错情况，并暴露在connections页面上。
error_count : 总的出错次数
health_index : 100表示没出错，接近0表示即将被熔断)
broken_times : 被SetFailed的次数, 仅记录SetFailed=0的次数
不论是否开启熔断都会进行统计。

Exposing the status of CircuitBreaker to the builtIn page

---

src/brpc/policy/discovery_naming_service.cpp

Discovery服务DoCancel请求，如果不指定Content-Type: application/x-www-form-urlencoded,返回的结果为两个Object，Discovery服务端这样返回也很怪异。

fix discovery docancel request return error response

---

src/brpc/policy/http2_rpc_protocol.cpp

* 当h2response的包体长度小于remote window size时，当前的做法是直接return，导致client无法收到response。
spec中并未说明此情况的做法，一个办法是直接返回RST_STREAM，即此次pr的解决方案。另一种方案是等到收到WINDOW_UPDATE后重试，需要额外的设计和实现。
* 修复sending时的memory leak

fix h2 big response not sending bug

---

src/butil/iobuf.cpp
test/iobuf_unittest.cpp

acquire tls block可能会取到full的block，加了单测可以复现，在release block chain的时候会导致abort

Fix acquire tls block

---

src/bthread/mutex.h

Fix #645 
Signed-off-by: Cholerae Hu <choleraehyq@gmail.com>

mutex: throw system_error when constuctor failed and lock failed

---

docs/cn/getting_started.md

否则会报
```
[ 25%] Building CXX object CMakeFiles/gtest.dir/src/gtest-all.cc.o
In file included from /Users/cholerae/Documents/cppcode/googletest/googletest/src/gtest-all.cc:38:
In file included from /Users/cholerae/Documents/cppcode/googletest/googletest/include/gtest/gtest.h:60:
In file included from /Users/cholerae/Documents/cppcode/googletest/googletest/include/gtest/internal/gtest-internal.h:40:
/Users/cholerae/Documents/cppcode/googletest/googletest/include/gtest/internal/gtest-port.h:836:12: error: no member named 'make_tuple' in namespace 'std'
using std::make_tuple;
~~~~~^
/Users/cholerae/Documents/cppcode/googletest/googletest/include/gtest/internal/gtest-port.h:837:12: error: no member named 'tuple' in namespace 'std'
using std::tuple;
~~~~~^ …
```

fix googletest compile commands on macos

---

config_brpc.sh

Bug report: #769 
Related issue: #328 #360 #666 #723 #726
According to the [instruction](https://github.com/apache/incubator-brpc/blob/master/docs/cn/getting_started.md)
given by incubator-brpc, openssl seems to be an optional lib but it is required
on all platforms, despite that openssl may be installed by default and no need
to install manually. 
However, openssl is not trusted by Apple due to [heartbleed](https://en.m.wikipedia.org/wiki/Heartbleed),
if we need to get openssl support, we need to install it manually.
We can compile/install leveldb, gflags, openssl, openssl, protobuf on mac by
simply using the package manager called `brew` as suggested by the brpc
installation instruction, or install by hand with `autotools + libtool + pkg-config` 
from source code published on github (or …

Fix compilation errors caused by ssl on MacOS

---

src/brpc/adaptive_connection_type.h
src/brpc/adaptive_max_concurrency.h
src/brpc/adaptive_protocol_type.h
src/brpc/server.cpp
test/brpc_adaptive_class_unittest.cpp

1. 为 AdaptiveXXX 的构造函数增加了explicit 关键字，以避免一些预期之外的隐式转换 (如执行 std::string == int，会调用 operator ==(butil:StringPiece, AdaptiveMaxConcurrency)
2. 用户代码中，一些显示的operator==依旧是被允许的，比如AdaptiveConnectionType与brpc::ConnectionType是可以直接调用operator==的(参考unit-test)
2. 删除了行末的空行

add explicit key word for AdaptiveXXX

---

src/brpc/circuit_breaker.cpp
src/brpc/circuit_breaker.h
src/brpc/socket.cpp
test/brpc_circuit_breaker_unittest.cpp

1. fix sp->circuit_breaker->Reset() 时可能存在的data race
2. 调整CircuitBreaker::Reset的策略，Reset之后，如果已经经过了初始化阶段，则继续使用之前ema_latency。如果Reset的时候还处于初始化阶段，则丢弃之前积累的数据

CircuitBreaker： fix race condition， adjust reset policy

---

src/brpc/thrift_message.cpp

remove ```#include wire_format_lite_inl.h``` to fix Protobuf 3.8 build error 
test build ok with protobuf 3.6.1 and protobuf 3.8.0

remove ```#include wire_format_lite_inl.h```  fix Protobuf 3.8 build error

---

src/brpc/policy/locality_aware_load_balancer.cpp

To avoid zero exception.
Fix: https://github.com/apache/incubator-brpc/issues/898
(This is a Baidu internal modification)

fix _avg_latency maybe zero

---

src/butil/logging.h

此处应该和其他宏一样使用顶层命名空间中的 logging， 否则当用户自定义了子 logging  namespace 时就会可能造成冲突。

fix bug: logging namespace conflict

---

src/brpc/details/mesalink_ssl_helper.cpp

This PR fixes an issue where the MesaLink TLS backend failed to verify client certs signed with self-signed CA certs. Insecure SSL/TLS versions (3.0, 1.0, 1.1) are also disabled in favor of MesaLink.
This PR depends on PR #878 for CI testing.

mesalink: bug fix for client authentication

---

config_brpc.sh

For example, to configure the brpc build with self-built version of protobuf/protoc, like this:
```
$ ll third_party/install/protobuf/bin/
total 57412
drwxrwxr-x 2 heliangliang heliangliang     4096 Oct  8 10:58 ./
drwxrwxr-x 5 heliangliang heliangliang     4096 Oct  8 10:58 ../
lrwxrwxrwx 1 heliangliang heliangliang       14 Oct  8 10:58 protoc -> protoc-3.8.0.0*
-rwxr-xr-x 1 heliangliang heliangliang 58780232 Oct  8 10:58 protoc-3.8.0.0*
```
The current script won't find the protoc without `-L` option.

Support symlink for config find_bin

---

src/brpc/policy/discovery_naming_service.cpp

在使用bili discovery服务发现中，原SDK在fetch nodes没有对服务节点机房做区分，fetch回来的是所有机房的节点，导致多活出现了跨机房调用。
discovery_zone 设置了就会fetch对应的机房节点，不设置默认所有机房节点。

add zone for bili discovery in fetching server nodes

---

src/brpc/server.cpp

The following step will mess up the pid file:
1. Start the server with pid file enabled. Suppose the pid is 12345.
2. Make the server core dump. 
3. Restart the server. Suppose the new pid is 8888. The pid file will be overwritten with the wrong content 88885.

bugfix: pid file may be overwritten

---

src/brpc/policy/auto_concurrency_limiter.cpp
src/brpc/policy/auto_concurrency_limiter.h

保障max currency 不小于bthread concurrency

limit minimum value of max_concurrency for auto_cl

---

docs/cn/bvar_c++.md

It seems that "<>" will be recognized as an html tag and
cannot be displayed on web page.

Add missing '`'

---

example/redis_c++/redis_server.cpp
src/brpc/policy/redis_protocol.cpp
src/brpc/redis.cpp
src/brpc/redis.h
src/brpc/redis_command.cpp
src/brpc/redis_command.h
test/brpc_redis_unittest.cpp

1.将const char*替换为butil::StringPiece。当args中包含字符'\0'时，可以知道其真实长度
2.支持长度为0的arg。例如：set key ""，是一个合法的redis请求

fix redis args

---

src/butil/strings/string_piece.h

Here may means we don't need to touch `BasicStringPiece` directly. So I removed it here.

(FIX COMMENT)butil: remove BasicStringPiece in comments

---

.asf.yaml

An error occurred while running github feature in .asf.yaml!:
.asf.yaml: Invalid GitHub label 'RPC' - must be lowercase alphanumerical and <= 35 characters!
---------------------------------------------------------------------
got one mail from apache infra, so change it to lowercase

update .asf.yaml to change RPC into lowercase

---

src/brpc/global.cpp
src/brpc/policy/domain_naming_service.cpp
src/brpc/policy/domain_naming_service.h

当naming service使用https时，使用443作为默认端口。

For https naming service, use 443 as default port

---

src/brpc/trackme.cpp
src/bthread/task_group.cpp

1. change the prefix of static global variables from "g_" to "s_" in brpc/trackme.cpp.  
2. delete outdated comments in src/bthread/task_group.cpp.  
3. all other changes  are the trailing spaces.

coding style fix in brpc/trackme.cpp

---

src/bthread/context.cpp

Only reproduced and tested with x64 linux and gcc 7 / 8 / 10.
Not sure if this error exist on other platforms.
Asm functions in context.cpp is invalid as [this topic](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=47071) discussed.
Need change back the section before the end of the inline-asm.
Related issue: https://github.com/apache/incubator-brpc/issues/1186

Fix the compile error when using GCC compiler with asan enabled on Linux platform.

---

src/brpc/builtin/hotspots_service.cpp

kFlameGraph这个变量目前只针对OS_LINUX
但是函数调用的时候，没有加宏保护，导致在macOS下编译失败

Fix build failure on macOS with FlameGraph

---

docs/cn/status.md
docs/en/status.md

文档中的代码示例写错了，需要实现的函数名应为Describe

status文档中的代码示例写错了，需要实现的函数名应为Describe

---

src/brpc/policy/locality_aware_load_balancer.cpp

glog的FATAL级别，会触发core dump（glog的设计，不是bug）
在使用glog的情况下，最好不要在服务正常运行的代码中使用FATAL。避免下游异常时，让当前服务直接core掉。

修改la策略中的异常日志的级别，避免在使用glog的情况下core dump

---

docs/cn/rpc_replay.md
src/brpc/rpc_dump.h

文档（docs/cn/rpc_replay.md）和注释（src/brpc/rpc_dump.h）中的SampleRequest写错了，应为SampledRequest。
顺便给文档中的SampledRequest套上命名空间。和前后代码风格对齐。

SampleRequest写错了应为SampledRequest

---

tools/rpc_replay/rpc_replay.cpp

因为 ChannelGroup 有成员函数channel，是通过传入的ProtocolType当成数组_chans下标使用的。
```cpp
brpc::Channel* channel(brpc::ProtocolType type) {
if ((size_t)type < _chans.size()) {
return _chans[(size_t)type];
}
return NULL;
}
```
而_chans的大小，是如此定义：
```cpp
for (size_t i = 0; i < protocols.size(); ++i) {
max_protocol_size = std::max(max_protocol_size,
(size_t)protocols[i].first);
}
_chans.resize(max_protocol_size);
```
比如当最大的ProtocolType是26的时候，这个数组的大小是26，但是数组的下标只有0到25，那么是无法通过26找到channel的。
当前因为rpc_replay支持回放的协议类型比较少，所以没出问题。
resize的大小应该是ProtocalType的最大值 + 1

修复rpc_replay中ChannelGroup初始化时resize的bug

---

docs/cn/flags.md

BRPC_RPC_VALIDATE_GFLAG应为BRPC_VALIDATE_GFLAG
will close #1399

文档修复：BRPC_RPC_VALIDATE_GFLAG改为BRPC_VALIDATE_GFLAG

---

src/brpc/policy/rtmp_protocol.cpp
src/bthread/fd.cpp
src/butil/object_pool_inl.h
src/butil/resource_pool_inl.h
src/butil/third_party/rapidjson/document.h

发现 #1381 这个PR被merge以后，还是有大量`no trivial copy-assignment; use value-initialization instead [-Wclass-memaccess]`的警告。
比如：
```
/home/guodong/github/guodong/incubator-brpc/src/butil/resource_pool.h:97:54:   required from ‘T* butil::get_resource(butil::ResourceId<T>*) [with T = bthread::TimerThread::Task]’
/home/guodong/github/guodong/incubator-brpc/src/bthread/timer_thread.cpp:187:43:   required from here
/home/guodong/github/guodong/incubator-brpc/src/butil/resource_pool_inl.h:133:19: warning: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘class butil::atomic<butil::ResourcePool<bthread::TimerThread::Task>::Block*>’ with no trivial copy-assignment; use value-initialization instead [-Wclass-memaccess]
133 |             memset(blocks, 0, sizeof(butil::atomic<Block*>) * …
```

消除高版本GCC上编译时大量-Wclass-memaccess的警告

---

src/brpc/event_dispatcher.cpp
src/brpc/event_dispatcher.h
src/bthread/bthread.cpp
src/bthread/types.h

bthread epoll_wait .about_to_quit will be set to true in some cases. refer to https://github.com/apache/incubator-brpc/issues/1177

add flag BTHREAD_NEVER_QUIT

---

docs/cn/client.md
docs/en/client.md

Fix http client doc

---

src/brpc/uri.cpp
test/brpc_uri_unittest.cpp

这个PR的目的检查url中是否有不可打印字符。
可打印字符的维基百科：
https://en.wikipedia.org/wiki/ASCII#Printable_characters
之前遇到过一个问题，在调用一个HTTP API接口的时候，要加一个签名字段作为query参数。用openssl计算签名的时候，最后意外多复制了一位，这一位是不可打印的字符。
让后请求接口一直失败，日志打印URL查看也没有问题，因为是不可打印字符，所以无法输出，其实是多了一个隐藏字符。
导致调试了很长时间。
当然可打印的字符中也不是全部都是URL的合法字符，但是其他的非法字符，只要是可打印的都可以很快定位到问题，因此不做考虑。因为判断合法字符的比较繁琐（也容易错漏，引发不必要问题），以下这些都是合法字符：
`A-Z`, `a-z`, `0-9`, `-`, `.`, `_`, `~`, `:`, `/`, `?`, `#`, `[`, `]`, `@`, `!`, `$`, `&`, `'`, `(`, `)`, `*`, `+`, `,`, `;`, `%`, `=`
当然如果你们觉得判断是不是合法字符更合适的话，我也可以改成 is_valid 函数。

check is valid character in uri

---

docs/cn/getting_started.md
docs/en/getting_started.md
docs/en/thrift.md

- tanslate cn/getting_started.md into Chinese.
- move origin getting_started.md to docs/en.
- docs/en/thrift.md reference en/getting_started.md.
原先 docs/cn目录下放的 getting_started.md 是英文的。这个目录应该放中文的才对。
转移到了en目录下，然后对cn目录中的该文件做了一下翻译。

Tanslate getting_started.md into Chinese

---

src/brpc/rtmp.cpp
src/brpc/rtmp.h

Fix #1110
Ref: https://docs.fileformat.com/video/flv/#structure

Add rtmp/FlvWriterOptions to support writing audio/video content only

---

docs/cn/http_client.md
docs/en/http_client.md
src/brpc/channel.cpp
src/brpc/channel.h
src/brpc/details/http_message.cpp
test/brpc_channel_unittest.cpp

当前brpc的实现中，如果http请求，uri没有设置全地址，比如"/get_result?a=b"，那么会默认用ip+port作为HTTP 报头的header字段。
但是这样有问题，即使我的Channel初始化的时候使用的是域名，比如：`http://www.foo.com`，最后对对端看到的还是ip+端口。但像Apache/Nginx这种Web Server都是只是单地址多服务的，`http://www.foo.com` 和 `www.bar.com` 可能是同一个ip和端口（对应的是Apache的地址），然后Web Server会通过Host字段来路由到具体的服务。如果Apache看到的是Ip+端口，则不知道该把请求路由到哪个服务。
当前只能通过发送请求之时给uri填写完整的路径来解决，比如`http://www.foo.com/get_result?a=b`，但是感觉还是应该框架补全能力比较好。
因为比如我有多个环境，有测试、生产环境。他们访问下游HTTP服务的时候，每个环境的服务请求的接口地址是不同的。
比如生产环境是：`http://www.foo.com/get_result?a=b`，而测试环境是`http://www.foo-test.com/get_result?a=b`，我的服务在给Channel初始化的时候已经依据环境来用不同的域名地址进行了初始化。但是当实际给下游发请求的时候（CallMethod之前构造http_request的时候），还需要再判断一遍系统运行环境，再给cntl->http_request().uri() 视环境来赋不同的值。有些冗余，我感觉还是应该框架做好，减少冗余配置和冗余判断。
当然要实现这一feature，可实现的方案有很多。我这里采用的方案是也是当前感觉改动最小，影响最小但能达到目的的一个。受限于Brpc的历史设计，导致 …

Set hostname rather than ip when channel Init by hostname but not host in http_requst().uri()

---

src/brpc/protocol.cpp

Fix a typo  in src/brpc/protocol.cpp, compress_tpye->compress_type

Fix a typo of compress type

---

src/brpc/policy/http_rpc_protocol.cpp

When an incorrect HTTP request is received, the existing code returns an `HttpRequest`, which should actually return an `HttpResponse`.
before fixing:
```
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8010 (#0)
> GET /v1/queue/stop 1 HTTP/1.1
> Host: 127.0.0.1:8010
> User-Agent: curl/7.64.1
> Accept: */*
>
GET / HTTP/1.1
Host: 127.0.0.1:58674
Accept: */*
User-Agent: brpc/1.0 curl/7.0
* Closing connection 0
```
After modification:
```
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8010 (#0)
> GET /v1/queue/stop 1 HTTP/1.1
> Host: 127.0.0.1:8010
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 400 Bad Request
* no chunk, no close, no size. Assume close to signal end
<
* Closing connection 0
```

Fix HttpResponse error

---

config_brpc.sh

Exclude mesalink/openssl/ssl.h when find openssl

---

src/brpc/esp_message.cpp
src/brpc/esp_message.h
src/brpc/memcache.cpp
src/brpc/memcache.h
src/brpc/nshead_message.cpp
src/brpc/nshead_message.h
src/brpc/protocol.cpp
src/brpc/redis.cpp
src/brpc/redis.h
src/brpc/serialized_request.cpp
src/brpc/serialized_request.h
src/brpc/thrift_message.cpp
src/brpc/thrift_message.h

Support Protobuf 3.19.1 (breaking changes here: https://github.com/protocolbuffers/protobuf/commit/624d29d83306f3ce2c7e092dd44a891e04215e67)

Improvement: brpc support higher version of protobuf

---

src/brpc/controller.cpp

调试brpc过程中在此处发生coredump，原因是_current_call.sending_sock为NULL。参照d465115cb对rdma分支中此处提出修改。

Fix a null deref in Controller::EndRPC

---

tools/rpc_view/rpc_view.cpp

`defer_close_seconds` should be `defer_close_second`.

Fix rpc view `defer_close_second flag` typo

---

src/brpc/channel.cpp

loadbalancer：c_murmurhash
当某个下游实例由于某些原因被SetFailed之后，后台会启动一个健康检查线程定时(间隔由参数-health_check_interval控制)检查被屏蔽的实例是否恢复正常。
对于hash类型的loadbalancer，SelectServer(const SelectIn& in, SelectOut* out)函数中的in.has_request_code必须是true，否则会输出错误日志并返回错误(EINVAL)
```c++
if (!in.has_request_code) {
LOG(ERROR) << "Controller.set_request_code() is required";
return EINVAL;
}
```
如果下游实例只有几个，在某些情况下，有可能这些实例都被SetFailed了，从而导致后续的所有的请求都会失败。

Fix CheckHealth not set has_request_code

---

src/brpc/server.cpp
src/brpc/server.h

Related issue: #1482 
目前brpcz中只有method级别的eps(error_per_second)，本PR实现了server级别的eps。
其实server级别的eps对业务来说更为重要。

Implement server eps bvar

---

test/Makefile

问题的原因是在test目录中make的时候，并行启动了两个make子进程：
导致make的时候bvar下的源文件（如src/bvar/detail/sampler.dbg.o）可能存在并发编译写入同一个.dbg.o文件：
导致最终生成的libbvar.dbg.a缺乏符号：

Fix unstable UT link error

---

src/bvar/latency_recorder.cpp
test/Makefile
test/bvar_recorder_unittest.cpp

LatencyRecorder里面的qps，get_window_recorder_qps 函数里面，static_cast<RecorderWindow*>(arg)->get_span(1, &s);  
get_span的windows是1的，这样有个问题，如果10s中采集一次，前5s的qps=1000，后5s的qps=0，那么得到的qps就是0。
另外就是get_span的window>1时，会出现qps可能取到小数，比如0.1，然后返回类型就是int64_t，这样就强转成0了，导致没数据。

Fix LatencyRecorder qps not accurate

---

src/brpc/input_messenger.cpp

*Client Ptotocol Rule*: Ptotocol in client-side is fixed except `baidu_std`, because of `streaming_rpc` need create by `baidu_std` ptotocol. 
But in current implementation， there is a chance that client will accept message but not match with current protocol.
Case:
Client issue two RPC names `A` (use `hulu` protocol) and `B`(use` baidu_std` protocol) to server in the same connection, If A is sent before B,  client will set preferred protocol to `baidu_std`,  server will accept these two request and response. Then if response of B received by client  before A, B will be parsed success, because it is matched with current protocol(`baidu_std`). When parse response of A by current preferred ptotocol(`baidu_std`) will fail, according to *Client Ptotocol Rule*, client think this response is …

fix(input_messenger) client side retry policy

---

src/brpc/policy/baidu_rpc_protocol.cpp
src/brpc/policy/esp_protocol.cpp
src/brpc/policy/http_rpc_protocol.cpp
src/brpc/policy/hulu_pbrpc_protocol.cpp
src/brpc/policy/memcache_binary_protocol.cpp
src/brpc/policy/nova_pbrpc_protocol.cpp
src/brpc/policy/nshead_mcpack_protocol.cpp
src/brpc/policy/nshead_protocol.cpp
src/brpc/policy/public_pbrpc_protocol.cpp
src/brpc/policy/redis_protocol.cpp
src/brpc/policy/sofa_pbrpc_protocol.cpp
src/brpc/policy/thrift_protocol.cpp
src/brpc/policy/ubrpc2pb_protocol.cpp

When I go through code in `Span`, I found there are typo in `release resource`, so I changed it here.

Typo Fix: Change Resourse to Resource

---

.travis.yml

thrift download url  `https://downloads.apache.org/thrift/0.11.0/thrift-0.11.0.tar.gz` has moved to `https://archive.apache.org/dist/thrift/0.11.0/thrift-0.11.0.tar.gz`

Update Thrift download url to avoid pr build failed

---

docs/cn/client.md
docs/cn/endpoint.md
docs/cn/server.md
docs/cn/streaming_log.md
example/echo_c++/server.cpp
src/brpc/acceptor.cpp
src/brpc/builtin/index_service.cpp
src/brpc/channel.cpp
src/brpc/policy/consistent_hashing_load_balancer.cpp
src/brpc/policy/domain_naming_service.cpp
src/brpc/policy/http_rpc_protocol.cpp
src/brpc/server.cpp
src/brpc/server.h
src/brpc/socket.cpp
src/butil/details/extended_endpoint.hpp
src/butil/endpoint.cpp
src/butil/endpoint.h
test/brpc_load_balancer_unittest.cpp
test/endpoint_unittest.cpp

Solve #381, #879, #1403, #1462, #1552, #1561
Partially solve: #207
这里补充说明一下EndPoint扩展支持IPV6和UDS的思路：
整体上是遵循了@jamesge在 #207 中提到的思路，即EndPoint保持ABI兼容，不修改EndPoint的size，引入标志位（在port字段），然后ip字段是一个指向ExtendedEndPoint结构的ResourceId (使用butil::ResourcePool）。这样的好处就是对于现存的IPV4业务，是完全ABI兼容。
在ExtendedEndPoint结构中，引入了引用计数，这样拷贝EndPoint时会增加引用，释放EndPoint时会减少引用。
str2endpoint/endpoint2str都支持了IPV6和UDS。但是str2ip无法支持，因为ip_t结构没法在保持ABI兼容的情况下再扩展了。
tcp_connect/tcp_listen等方法也对扩展类型的EndPoint进行了支持，从而最小化对上层的改动。
另外由于EndPoint结构很多时候被直接当作值来使用（比如基于EndPoint的值进行排序、作为map/hash map的key等），为了兼容这些用法 ，我们需要保证同一个IPV4/IPV6/UDS的值，生成的EndPoint的值相同，因此做一个全局的去重，即值相同的EndPoint都指向同一个ExtendedEndPoint结构。这样对于内存也有一些节省（由于前面用了32位的ip字段来存储ResourceId，最多只能同时保存2^32个不同的EndPoint）。

Support IPV6 and Unix domain socket

---

src/brpc/policy/baidu_rpc_protocol.cpp
src/brpc/policy/hulu_pbrpc_protocol.cpp
src/brpc/policy/public_pbrpc_protocol.cpp
src/brpc/policy/sofa_pbrpc_protocol.cpp
src/brpc/policy/streaming_rpc_protocol.cpp
src/brpc/protocol.h

Fix build warning, protobuf ByteSize() is deprecated, use ByteSizeLong() instead

Fix build warning, ByteSize() is deprecated, use ByteSizeLong() instead

---

src/brpc/policy/redis_protocol.cpp

issue: https://github.com/apache/incubator-brpc/issues/1743
in brpc redis protocol, set failed and return error message when byte size is empty in redis request.

Redis empty request

---

src/bthread/unstable.h

solve this error. make it the same as bthread.h

[UPDATE] fix c struct compile error

---

src/brpc/channel.cpp

[文章](https://github.com/apache/incubator-brpc/blob/master/docs/cn/client.md#%E5%BC%80%E5%90%AFssl) 文档中提到“Channel.Init能自动识别https”，相关功能在去年重构代码中引入了 bug，目前此功能已失效。这个 pt 是为了修复这个问题

fix auto https check

---

docs/cn/client.md

https:// 后面补一个空格，防止后面的中文被网页识别成链接的一部分，引起误解（以为是引用了其他文档）。当前网页上显示效果如下：

client.md 文档优化

---

src/bthread/butex.cpp
src/bthread/butex.h
src/bthread/countdown_event.cpp
src/bthread/countdown_event.h

butex_wake_all support nosignal flag

---

src/brpc/redis_command.h

fix compile error like `incubator-brpc/src/brpc/redis_command.cpp:411:29: error: ‘numeric_limits’ is not a member of ‘std’`

Fix compile error due to std limits header absent

---

src/brpc/policy/http2_rpc_protocol.cpp
src/brpc/policy/http2_rpc_protocol.h

Change:
* Fix a deadlock
* Rename RemoveStream to RemoveStreamAndDeferWU and change the impl of original RemoveStreamAndDeferWU
* Remove ClearAbandonedStreamsImpl because it reads protected vars without lock

Fix a deadlock happened in ClearAbandonedStreamsImpl path(issues/1778)

---

src/brpc/policy/http2_rpc_protocol.cpp
src/brpc/policy/http2_rpc_protocol.h

Follow-up of https://github.com/apache/incubator-brpc/pull/1781
在ClearAbandonedStreams的时候更新Windowsize，否则这些streams消耗的windowsize无法正确复原。原issue中的死锁问题已通过在ClearAbandonedStreams调用RemoveStreamAndDeferWU前，释放锁的方式解决。

BugFix: Send WindowUpdate when ClearAbandonedStreams is called

---

src/bthread/mutex.cpp

Fix _dl_sym undefined reference

---

src/brpc/policy/discovery_naming_service.cpp

Fix discovery naming service core

---

CMakeLists.txt
src/CMakeLists.txt

protoc-gen-mcpack dependent on shared libraries. so when I build with `-DBUILD_SHARED_LIBS=OFF`. I'll got a link error

Fix Brpc build tools error when only build static

---

tools/rpc_press/rpc_press.cpp
tools/rpc_press/rpc_press_impl.cpp

项目中利用rpc_press进行压测，出现服务衰减问题，即压测过程中服务性能越变越差。后来通过分析发现rpc_press压测工具的实现存在问题，网络或者CPU抖动造成的发送请求不均匀会一直保存在窗口中，并影响后续请求，随程序运行时间变长，抖动出现的次数越来越多，发送地请求会越来越不均匀。具体分析如下：
举例说明：假设 QPS: 100，异步发送请求平均耗时 1ms，为方便画图，假设队列最大长度为10。
图(1) 中发送编号为4的请求时CPU或者网络抖动，造成本应在t+31发出的请求滞后了15ms，按照代码逻辑，编号为5/6的请求分别在t + 47 和 t + 51发出
图(2) 我们假设队列最大长度为10，按照图上的计算过程可以得到，发送完请求14后会sleep 24ms，这样就导致发送请求4时的抖动，对请求15发送时间造成了影响，抖动会在队列中一直存在。QPS越高，请求间隔越短，这个问题越容易出现。
本pull request利用一种更简单的方式来计算请求间隔，来解决上述问题。

fix rpc_press can't send request equably

---

src/brpc/policy/baidu_rpc_protocol.cpp

Check append return code

---

.travis.yml
build_in_travis_ci.sh

MesaLink deb 下载地址不可用, 也未找到其他官方可替代地址. 由于 MesaLink 声明和 OpenSSL 兼容, 集成到 CI 中进行测试不是必须的.

CI: disable unstable MesaLink

---

src/butil/endpoint.cpp

使用Channel::Init("http://hostname", options)时，会在hostname2ip中通过gethostbyname_r获取dns的节点信息。如果hostname在dns中配置了很多节点，hostname2ip会因为aux_buf长度不够导致调用失败，从而导致Channel::Init失败。
解决方法：参考DomainNamingService获取节点信息的方法，当gethostbyname_r返回ERANGE，表示aux_buf长度不足时，将aux_buf长度增大一倍，重新调用gethostbyname_r获取节点信息，直到获取成功为止。

fix hostname2ip fails when aux_buf is not long enough

---

src/brpc/policy/streaming_rpc_protocol.cpp

我们发现通过Streaming RPC协议发送数据存在丢失数据的可能，以下是丢失的过程：
假设两个进程通过brpc stream通信，我们把发送数据的进程称为sender，接受数据的进程为receiver。
1. sender连续三次调用StreamWrite，发送了三次数据，分别为A，B，C；然后调用StreamClose；
2. receiver收到sender的数据帧A之后，返回FEEDBACK数据帧给sender；
3. sender收到数据帧A对应的FEEDBACK，但是因为对应stream_id在步骤1调用完StreamClose后已经没有办法通过Socket::Address获取到，找不到stream_id对应的stream于是sender返回RST给receiver（调用SendStreamRst）; 
```cpp
/// streaming_rpc_protocol.cpp 106 行
if (Socket::Address((SocketId)fm.stream_id(), &ptr) != 0) {
RPC_VLOG_IF(fm.frame_type() != FRAME_TYPE_RST
&& fm.frame_type() != FRAME_TYPE_CLOSE
&& fm.frame_type() != FRAME_TYPE_FEEDBACK)
<< "Fail to find stream=" << fm.stream_id();
if (fm.has_source_stream_id()) {
SendStreamRst(socket, fm.source_stream_id());
}
break;
}
```
4. …

Fix stream will respond received feedback frame with RST frame when closed

---

src/bthread/execution_queue.cpp
src/bthread/execution_queue.h
src/bthread/execution_queue_inl.h
tools/rpc_press/rpc_press_impl.cpp

When compiling `rpc_press` using Apple M1 Pro and clang14, `std::max(10000000L, 10 * interval);` tells that `long` and `long long` conflict, so I change it to `10000000LL`, which represents "long long".
Also, I fix some typos in execution-queue mod.

Fixing compilation in rpc_press, and fixing typo in execution-queue

---

community/apache-package-validator.sh

Related #1839
```
./apache-package-validator.sh https://dist.apache.org/repos/dist/dev/incubator/brpc/1.2.0
gpg: key D524DB15A50644A9: "jiashunzhu <jiashunzhu@apache.org>" not changed
gpg: key 4A5F6E2C8B4ED2FF: "LeiHe (Lei He's key) <leander@apache.org>" not changed
gpg: key BBFCA2FFA756B3FB: "lorinlee (lorinlee's key) <lorinlee@apache.org>" not changed
gpg: key 12B5FBD08D58CF0C: "Wang Weibing (wwbmmm's key) <wwbmmm@apache.org>" not changed
gpg: key EB29FB0E46BDC206: "serverglen (serverglen' key) <serverglen@apache.org>" not changed
gpg: Total number processed: 5
gpg:              unchanged: 5
gpg: assuming signed data in 'apache-brpc-1.2.0-incubating-src.tar.gz'
gpg: Signature made Mon 11 Jul 2022 12:14:26 PM HKT
gpg:                using RSA key D690E8E27620154DADAA5869EB29FB0E46BDC206 …
```

Add apache package validator

---

src/brpc/details/health_check.cpp
src/brpc/socket.cpp
src/brpc/socket.h

fix #1773 
#1774 的pr是使用了加锁的方案，该pr实现了@wwbmmm在 #1774 提到的[方案](https://github.com/apache/incubator-brpc/pull/1774#issuecomment-1147009406)：
_recycle_flag增加reviving状态。如果ReleaseAddtionalReference发现状态是reviving就一直等，直到遇到其它两个状态再继续释放additional refrerence。

fix additional refrerence can not release when socket is reviving

---

src/brpc/details/health_check.cpp

#1817 中有个分支没有覆盖到。WaitAndReset失败后也要调用一下AfterHCCompleted。
@zyearn 麻烦看看。

call AfterHCCompleted when WaitAndReset fails

---

docs/cn/bvar.md
docs/cn/bvar_c++.md
docs/cn/mbvar_c++.md
docs/cn/vars.md
src/bvar/multi_dimension.h
src/bvar/multi_dimension_inl.h
src/bvar/mvariable.cpp
src/bvar/mvariable.h
src/bvar/variable.cpp
src/bvar/variable.h
test/bvar_multi_dimension_unittest.cpp
test/bvar_mvariable_unittest.cpp

Implement multi bvar feature

---

src/bthread/key.cpp

fix #1714 
优雅退出时能只清理pthread创建的keytable，bthread创建的keytable不需要在cleanup_pthread中清理，这些keytable会在return_keytable或者bthread_keytable_pool_destroy中清理。

fix the first bthread keytable on worker pthread will be deleted twice

---

src/brpc/server.cpp
src/brpc/server.h

通过ServerOption自定义Server的Bvar prefix。
目前bvar默认的前缀是rpc_server_{server监听的port}，但是存在如下问题：
1. 由于port改变（如使用range port或者其他port可能会改变的场景)导致bvar name变化，使得配置的dashboard和监控失效
2. 为了支持IPV6和Unix Domain socket，引入了ExtendedEndPoint，不过生成prefix存在BUG，会固定用EXTENDED_ENDPOINT_PORT（123456789）生成前缀（rpc_server_123456789），导致不同的Server bvar前缀相同。虽然修复不难，但是Unix Domain socket不太好处理，因为没有port信息，如果用file_path的话又太长。
基于以上考虑，最好还是用户通过ServerOption传入Server name生成prefix，如果name为空，则保持原来的逻辑。

support customized server bvar prefix

---

src/bvar/mvariable.h

warning: class 'DumpOptions' was previously declared as a struct

fix compile warning

---

tools/rpc_replay/rpc_replay.cpp

修复rpc_replay长时间压测，压力趋于不均匀的问题。该问题和rpc_press中已修复的问题相同，参见#1763

fix rpc_replay can't send request equably

---

src/brpc/builtin/hotspots_service.cpp

Url from web browser request like 'host:port/hotspots/growth_non_responsive?console=abc' will cause coredump.
ref https://github.com/apache/incubator-brpc/issues/1112

fix coredump cause by bad growth_non_responsive http request

---

src/butil/errno.cpp

Do not abort when comparing the errorno message with the string and just print the warning.
Resolved https://github.com/apache/incubator-brpc/issues/863 .

Fix not to abort when checking the errorno with unicode string

---

docs/cn/getting_started.md
docs/en/getting_started.md

`brpc` is available as a port in [vcpkg](https://github.com/microsoft/vcpkg), a C++ library manager that simplifies installation for `brpc` and other project dependencies. Documenting the install process here will help users get started by providing a single set of commands to build `brpc`, ready to be included in their projects.
We also test whether our library ports build in various configurations (dynamic, static) on various platforms (OSX, Linux, Windows: x86, x64) to keep a wide coverage for users.
I'm a maintainer for vcpkg, and [here is what the port script looks like](https://github.com/microsoft/vcpkg/blob/master/ports/brpc/portfile.cmake). We try to keep the library maintained as close as possible to the original library. :)

[document] Add vcpkg instruction step

---

src/bvar/variable.cpp

bvar_dump_tabs默认值包含空格，导致创建的文件名字里有空格。
个人感觉也没有必要trim一下，严格要求不包含空格就行。

bvar_dump_tabs默认值的问题

---

src/brpc/policy/http_rpc_protocol.cpp
test/brpc_server_unittest.cpp

背景：
目前brpc上游收到http回包后，会将http异常状态码归结为EHTTP这个错误码。如果下游限流了，brpc上游也不会重试，因为brpc不会对EHTTP这个错误码进行重试，即使下游是brpc框架实现的。
实现：
brpc上游将下游回的x-bd-error-code这个header设置为error code。如果下游通过x-bd-error-code回了ELIMIT，brpc上游就会重试。

http response uses brpc error code

---

src/bvar/mvariable.cpp
src/bvar/variable.cpp

I encountered a problem about compiling brpc on Centos7.9 by using config_brpc.sh, for example:
```
src/bvar/variable.cpp:923:46: error: '::google' has not been declared
const bool ALLOW_UNUSED dummy_mbvar_dump = ::google::RegisterFlagValidator(
^~~~~~
src/bvar/variable.cpp:925:53: error: '::google' has not been declared
const bool ALLOW_UNUSED dummy_mbvar_dump_prefix = ::google::RegisterFlagValidator(
^~~~~~
src/bvar/variable.cpp:927:50: error: '::google' has not been declared
const bool ALLOW_UNUSED dump_mbvar_dump_file = ::google::RegisterFlagValidator(
^~~~~~
src/bvar/variable.cpp:943:53: error: '::google' has not been declared
const bool ALLOW_UNUSED dummy_mbvar_dump_format = ::google::RegisterFlagValidator(
```
Fix: Replace `::google::RegisterFlagValidator` with …

fix bvar compile error

---

docs/en/getting_started.md

I'm a contributor for the brpc vcpkg port. I found a typo in the doc.
related PR
https://github.com/apache/incubator-brpc/pull/1925

fix typo in getting_started doc

---

tools/rpc_replay/rpc_replay.cpp

rpc_replay 在 `ChannelGroup` 初始化时，即使有channel Init 失败（预期行为）应该直接 continue， 而不是返回 -1,  否则会导致程序直接退出，无法继续向下执行。
例如当 `-connection_type=pooled`， rtmp 协议由于不支持 pooled 模式，导致程序退出。本来的 rpc_data 中只有 `baidu_std` 协议，导致无法正常使用。

fix(rpc_replay) continue when failed to init channel

---

src/butil/class_name.h

Recently, I met some linkage errors while using `LLD` linker to compile the source code of Apache Doris. The issue looks like #1809 .
**src/butil/class_name.h**
```cpp
namespace detail {
template <typename T> struct ClassNameHelper { static std::string name; };
template <typename T> std::string ClassNameHelper<T>::name = demangle(typeid(T).name());
}
```
The linkage of ```ClassNameHelper<T>::name``` here is external due to it is variable template and it may cause the duplicate symbols error.
Some ways to fix it:
1. In C++ 17, use `inline variable`.
2. Before C++ 17, use unnamed namespace to make the linkage of ```ClassNameHelper<T>::name``` internal.
In this PR, I suggest using the second way to fix it.

Fix the linkage errors caused by duplicate symbols

---

src/bthread/task_group.cpp

修复在Linux aarch64平台上用Clang编译器编译，运行时报出来的`sched_to itself`错误。
项目：Apache Doris
平台：Ubuntu 22.04 aarch64
编译器：Ubuntu clang version 14.0.0-1ubuntu1
验证：用clang编译后跑UT，`./run-be-ut.sh` --run

Fix "sched_to itself" error when building by Clang on Linux aarch64

---

src/brpc/policy/redis_protocol.cpp
src/brpc/redis_command.cpp
src/brpc/redis_command.h

当 RedisCommandParser::Consume 返回 PARSE_ERROR_NOT_ENOUGH_DATA 时，已经 parse 过的数据可能被  ctx->arena.clear() 掉，下次继续parse时，解析过的 _args 内存已经被释放了。

fix arena cleared early when parse redis message

---

community/release_cn.md
src/bvar/mvariable.cpp

Issue Number:
Changed:
Side effects:
---

avoid std::string copy

---

.github/workflows/ci_macos.yml
test/bvar_recorder_unittest.cpp

will close #1842 
目前有两个小问题。一个是bazel无法构建，需要rework bazel的那个PR合入。#1657
另外一个是macos上test_bvar的UT失败，这个已经提了issue介绍 ： #1897

Macos workflow 

---

src/brpc/rdma/rdma_helper.cpp

Issue Number: #1966
When brpc is not compiled with rdma, a binary may not be linked correctly if the application invoke it.
Changed:
Add warning and force exit in GlobalRdmaInitializeOrDie if BRPC_WITH_RDMA is not defined.
Side effects: 
- Performance effects(性能影响): None
- Breaking backward compatibility(向后兼容性): None
---

add warning for rdma invoke when brpc is not compiled with rdma

---

docs/cn/rdma.md
docs/en/rdma.md
example/BUILD.bazel

Issue Number:
Changed:
Side effects:
---
Support `rdma_performance` build with bazel

Add rdma_performance bazel support

---

docs/cn/rdma.md
docs/en/rdma.md
src/brpc/rdma/rdma_helper.cpp

Issue Number:
Changed:
Side effects:
---
`libibverbs.so` is provided by `libibverbs-dev` and it is a symbol link to `libibverbs.so.1` which is provided by `libibverbs1`.
We do not need `-dev` package in production environment. So linking to `libibverbs.so.1` is a better solution.
```bash
lrwxrwxrwx 1 root root   15 Jan 28  2022 /usr/lib/x86_64-linux-gnu/libibverbs.so -> libibverbs.so.1
lrwxrwxrwx 1 root root   23 Jan 28  2022 …
```

Fall back to libibverbs.so.1

---

docs/cn/http_client.md
docs/en/http_client.md
src/brpc/channel.cpp
src/brpc/channel.h

Issue Number:
https://github.com/apache/incubator-brpc/issues/1940
Invalid host in HTTP header if setting host via service_name for channel inited by list or file
Changed:
check if ns_url shceme is 'http' or 'https', if true, set host field by service_name
Side effects:
NO impact
NO impact
---

fix HTTP invalid host issue for channel not inited by http(s)

---

src/brpc/socket.cpp
src/brpc/socket.h
src/brpc/stream.cpp
src/brpc/stream.h
src/brpc/stream_impl.h

1. Add **socket_max_streams_unconsumed_bytes** to socket for limiting max bytes in stream comsume queue with the same host socket.
2. Add **min_buffer_size** to stream options and remain_buffer_size to message Feedback for stream buffer control.

limiting max bytes in stream comsume queue with the same host socket

---

src/bvar/detail/sampler.cpp

Issue Number: #1891
Problem Summary: there is currently no gflag to control the switch of the sampler thread
Changed: add `--bvar_enable_sampling` flag to control the switch of the sampler thread. if flag is false, does not create a global singleton SamplerCollector object.
Side effects:
- Performance effects(性能影响):  setting the flag to false will reduce the creation of one thread and the usage of CPU and memory
- Breaking backward compatibility(向后兼容性):  yes
---

add gflag to disable sampler thread

---

src/brpc/rdma/rdma_helper.h

Issue Number:
Changed:
Side effects:
---
`bool SupportedByRdma(std::string protocol);` use `std::string` but forgets to `#include <string>`
See https://github.com/apache/incubator-brpc/blob/7998e68b89164d806933a8deddaa0b8b8f125f1b/src/brpc/rdma/rdma_helper.h#L77
Compile error like this can happen
```bash
external/brpc/src/brpc/rdma/rdma_helper.h:77:27: error: ‘string’ is not a member of ‘std’
77 | bool SupportedByRdma(std::string protocol);
| …
```

Include directly dependent header

---

example/asynchronous_echo_c++/server.cpp
example/auto_concurrency_limiter/server.cpp
example/backup_request_c++/server.cpp
example/cancel_c++/server.cpp
example/cascade_echo_c++/server.cpp
example/dynamic_partition_echo_c++/server.cpp
example/echo_c++/server.cpp
example/grpc_c++/server.cpp
example/http_c++/http_server.cpp
example/multi_threaded_echo_c++/server.cpp
example/multi_threaded_echo_fns_c++/server.cpp
example/nshead_pb_extension_c++/server.cpp
example/parallel_echo_c++/server.cpp
example/partition_echo_c++/server.cpp
example/rdma_performance/server.cpp
example/selective_echo_c++/server.cpp
example/streaming_echo_c++/server.cpp
src/brpc/socket.h
src/brpc/thrift_message.h
src/bvar/recorder.h
tools/rpc_view/rpc_view.cpp
tools/trackme_server/trackme_server.cpp

Changed: fix bad smell of C++ code
Side effects: 
- Performance effects(性能影响): no
- Breaking backward compatibility(向后兼容性):  no
---

remove unnecessary semicolon

---

src/butil/iobuf.cpp

Issue Number:
Changed:
Side effects:
---
As pointed out by @Tuvie https://github.com/apache/incubator-brpc/issues/1995#issuecomment-1323723025, when `IOBuf::append_user_data` is called with size 0, we can do early return. This avoids unnecessary block memory allocation in the later.

Early return when size == 0

---

src/butil/third_party/rapidjson/document.h

Make BUTIL_RAPIDJSON_NAMESPACE_BEGIN::GenericDocument's handler method public to enable outside custom parser/writer
Issue Number: None
Problem Summary: None
Changed: Handler methods of `GenericDocument` changed to public, to enable user customized parser/writer to iterator over the document
Side effects:
- Performance effects(性能影响): None
- Breaking backward compatibility(向后兼容性): None
---

Make GenericDocument's handler public to enable ouside parser/writer

---

src/butil/endpoint.cpp
src/butil/endpoint.h

Issue Number: #1911 
Problem Summary: hostname2endpoint implement is not compatite with domain RFCs.
Changed: change the buf length as 256, and use MAX_DOMAIN_LENGTH to check the domain name valid. But I don't have an exists domain to test it.
Side effects:
- Performance effects(性能影响): hostname2endpoint will allocate more 192 byte memory in stack.
- Breaking backward compatibility(向后兼容性):  yes
---

fix: domain name length

---

.github/workflows/ci-linux.yml

Issue Number:
Changed:
Side effects:
---

change os tag of Linux workflow from ubuntu-latest to ubuntu-20.04

---

src/json2pb/json_to_pb.cpp

Issue Number:
目前打开single_repeated_to_array开关后，pb转json只支持root case，但是打开array_to_single_repeated开关，json转pb没有限制root case。这样会导致json转pb，pb再转回json，前后的json结构发生了变化，不符合预期。例如：
```
meesage Single {
repeated int ids;
}
message Test {
Single single;
}
{
"single": [1,2,3]
}
{
single: {
"ids": [1,2,3]
}
}
```
Changed:
Side effects:
- Breaking backward compatibility(向后兼容性):  如果旧代码希望array_to_single_repeated将非root array转成single  @repedted的话，使用此PR代码后，会导致json转pb失败。
---

only allow to convert root array to single repeated pb

---

src/brpc/rdma/rdma_endpoint.cpp
src/butil/iobuf.cpp

What problem does this PR solve?
Issue Number:
Problem Summary: fix a QP leak bug
What is changed and the side effects?
Changed: Modify the condition to move QP back to QP pool when connection destroyed. The QP pool is used as a cache for the QPs in order to reduce the overhead to create a QP during the connection establishment.
Side effects:
Performance effects(性能影响):
Breaking backward compatibility(向后兼容性):
Check List:
Please make sure your changes are compilable(请确保你的更改可以通过编译).
When providing us with a new feature, it is best to add related tests(如果你向我们增加一个新的功能, 请添加相关测试).
Please follow [Contributor Covenant Code of Conduct](https://github.com/apache/master/CODE_OF_CONDUCT.md).(请遵循贡献者准则).

fix bug: QP cannot be put back to QP pool

---

src/butil/class_name.cpp

Issue Number: #2025
Problem Summary: Segfault in demangle
Changed: verify pointer before calling free()
Side effects:
- Breaking backward compatibility(向后兼容性): No
---

Fix demangle core

---

example/asynchronous_echo_c++/server.cpp
example/auto_concurrency_limiter/server.cpp
example/backup_request_c++/server.cpp
example/cancel_c++/server.cpp
example/dynamic_partition_echo_c++/server.cpp
example/echo_c++/server.cpp
example/grpc_c++/server.cpp
example/http_c++/http_server.cpp
example/multi_threaded_echo_c++/server.cpp
example/multi_threaded_echo_fns_c++/server.cpp
example/parallel_echo_c++/server.cpp
example/partition_echo_c++/server.cpp
example/selective_echo_c++/server.cpp
example/session_data_and_thread_local/server.cpp
example/streaming_echo_c++/server.cpp

Issue Number: #2060
Problem Summary: logoff_ms gflag in example is not used.
Changed: delete deprecated logoff_ms gflag in example folder.
Side effects:
- Performance effects(性能影响): no
- Breaking backward compatibility(向后兼容性): yes
---

delete deprecated logoff_ms gflag in example folder

---

CONTRIBUTING.md
README.md
README_cn.md
community/release_cn.md
community/release_en.md
config_brpc.sh
docs/cn/auto_concurrency_limiter.md
docs/cn/getting_started.md
docs/en/bvar_c++.md
docs/en/getting_started.md
example/build_with_bazel/brpc_workspace.bzl
example/rdma_performance/client.cpp
example/rdma_performance/server.cpp
package/rpm/brpc.spec
src/brpc/builtin/pprof_service.cpp
src/brpc/rdma/rdma_helper.cpp
src/butil/errno.h

Since bRPC has graduated, we can remove `incubator` in the source code.

Remove incubator

---

src/bthread/task_group.cpp
src/bthread/task_group.h

Issue Number: #2042
Problem Summary: bthread::TaskGroup add a new member _sched_recursive_guard if NDEBUG is not defined, this cause abi incompatible.
Changed: define the _sched_recursive_guard whether NDEBUG is defined or not
Side effects:
- Breaking backward compatibility(向后兼容性): No
---

Keep bthread TaskGroup abi compatible with NDEBUG macro

---

src/brpc/policy/timeout_concurrency_limiter.cpp
src/brpc/policy/timeout_concurrency_limiter.h

基于延迟的并发控制，在average latency的统计还没有刷新的时候，有可能因为一些慢请求导致服务排队很多请求，这个最大并发的设置，可以在这种情况下保护服务不被太多的请求压垮。
@wwbmmm 请PR

add max concurrency for timeout concurrency limiter

---

docs/cn/timeout_concurrency_limiter.md

添加timeout concurrency limiter的文档

add timeout concurrency limiter doc

---

src/brpc/builtin/status_service.cpp
src/brpc/server.cpp
src/brpc/server.h

Issue Number:
Problem Summary: 内置服务目前只展示了方法级别的并发数，并未展示server级别的并发数。
Changed:
增加bvar统计server级别的并发数，同时在内置服务页面展示该并发数。
Side effects:
---

show server concurrency in status service

---

src/brpc/server.cpp
test/brpc_server_unittest.cpp

Issue Number:
Problem Summary: 目前未判断PortRange和internal_port的合法性，即使实际的port大于65535（不合法的port），Server::Start()也会返回成功。
Changed: 检查PortRange和internal_port是否合法，不合法则返回-1表示失败。
Side effects:
---

check invalid port

---

src/brpc/channel.h
src/brpc/server.h
src/butil/ptr_container.h

Issue Number:
Changed: 重载了一些函数，期望PtrContainer可以像std::unique_ptr一样可以直接操作指针。
Side effects:
---

add some functions of PtrContainer

---

src/brpc/policy/timeout_concurrency_limiter.cpp

极端情况下average latency可能会大于请求的timeout，校验在currency_concurrency是1的时候可以通过，这样能保证在average latency大于请求的timeout的情况下，至少有一个请求可以被处理，这样average latency才能得到更新。

make sure we can receive at least one request

---

src/brpc/builtin/prometheus_metrics_service.cpp

Issue Number:
Changed:
Side effects:
---

add avg latency for prometheus metrics

---

src/brpc/periodic_naming_service.cpp
src/brpc/periodic_naming_service.h
src/brpc/policy/consul_naming_service.cpp
src/brpc/policy/consul_naming_service.h

Issue Number: #584
Problem Summary: 继承自PeriodicNamingService的ns，例如DiscoveryNamingService、NacosNamingService、RemoteFileNamingService，在GetServers中通过rpc拉取节点的时候，NamingServiceThread析构调用bthread_stop并不能中断CallMethod，CallMethod只是被唤醒了一下，而且将interrupted置会为false，CallMethod依然会等到rpc结束。但是这时候bthread_usleep已经不能感知到bthread_interrupt而退出了。
1. PeriodicNamingService通过判断bthread_stopped来退出。
2. ConsulNamingService本质上是一个PeriodicNamingService，将其抽象为PeriodicNamingService的派生类。
Changed:
Side effects:
--- …

Periodic ns quit

---

.github/actions/init-make-config/action.yml

Issue Number:
CI流水线make编译会报错：`Fail to find libprotoc`
原因是config_brpc.sh脚本在寻找protobuf的时候找到了这个目录`/usr/local/lib/android/sdk/emulator/lib64` 中的protobuf，而这个目录中并没有libprotoc，应该找`/usr/lib/x86_64-linux-gnu` 中的protobuf。
Changed:
Side effects:
---

修复CI流水线编译失败的问题

---

src/brpc/periodic_naming_service.cpp
src/brpc/policy/consul_naming_service.cpp
src/brpc/policy/consul_naming_service.h

Issue Number: #2123 
ConsulNamingService其实不是PeriodicNamingService，不是简单的轮询，而是[长轮询](https://brpc.incubator.apache.org/zh/docs/client/basics/#consulservice-name)，每次rpc成功后，立即发起下一次长轮询。只有失败了，才会sleep。
[Blocking Queries](https://developer.hashicorp.com/consul/api-docs/features/blocking)：
> Many endpoints in Consul support a feature known as "blocking queries". A blocking query is used to wait for a potential change using long polling.
Changed:
回退#2123 ConsulNamingService的改动
Side effects:
--- …

revert consul naming service

---

src/brpc/details/usercode_backup_pool.cpp
src/bthread/task_control.cpp
src/bthread/task_control.h
src/bthread/timer_thread.cpp
src/bvar/collector.cpp
src/bvar/detail/sampler.cpp
src/bvar/variable.cpp

Issue Number: https://github.com/apache/brpc/issues/1923
Problem Summary: Naming threads for debugging.
线程命名方式： `brpc` 开头 + `线程用途`。
其中 worker 线程以 id 作为区分。
No
Changed:
Naming sampling, timer and worker threads.
Side effects:
No
No
---

naming timer sampling and worker threads

---

src/butil/strings/string_piece.h

add type BasicStringPiece::const_pointer, make it like [string_view](https://en.cppreference.com/w/cpp/string/basic_string_view) and more convenient.
e.g. we can using butil::StringPiece as a  key to invoking folly::F14FastMap [heterogeneous accessing method](https://github.com/facebook/folly/blob/main/folly/container/HeterogeneousAccess.h#L158-L183) by this mr make butil::StringPiece like string_view which can implicitly convert to [folly::StringPiece](https://github.com/facebook/folly/blob/main/folly/Range.h#L278-L333)
Changed:
Side effects:
none
none
---

add type BasicStringPiece::const_pointer, make it like string_view and more convenient

---

docs/cn/getting_started.md
docs/en/getting_started.md

Issue Number: N/A
Original cmd `sudo apt-get install -y cmake libgtest-dev && cd /usr/src/gtest && sudo cmake . && sudo make && sudo mv libgtest* /usr/lib/ && cd -` does not work:
```
➜  /usr/src/gtest $ sudo make && sudo mv libgtest* /usr/lib
[ 25%] Building CXX object CMakeFiles/gtest.dir/src/gtest-all.cc.o
[ 50%] Linking CXX static library lib/libgtest.a
[ 50%] Built target gtest
[ 75%] Building CXX object CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
[100%] Linking CXX static library lib/libgtest_main.a
[100%] Built target gtest_main
zsh: no matches found: libgtest*
```
Changed:
Fix the gtest library path to `sudo mv lib/libgtest* /usr/lib` from `sudo mv libgtest* /usr/lib`.
Side effects: …

fix gtest build cmd in doc

---

src/butil/containers/flat_map.h
src/butil/containers/flat_map_inl.h
src/butil/single_threaded_pool.h

Issue Number:
Changed: FlatMap/FlatSet添加Allocator参数，默认为malloc/free
Side effects:
- Breaking backward compatibility(向后兼容性): 兼容
---

Add _Alloc template parameters for FlatMap and FlatSet

---

src/butil/containers/flat_map_inl.h
src/butil/single_threaded_pool.h

Issue Number:
Changed:  
Bug fix to swap allocator in FlatMap::resize
Side effects:
---

[BUG FIX] Swap allocator in FlatMap::resize

---

src/brpc/policy/baidu_rpc_protocol.cpp
src/brpc/policy/nshead_protocol.cpp
src/brpc/policy/thrift_protocol.cpp
src/butil/popen.cpp

Fix some codes that violates the C++ One Definition Rule, which stop us to enable [LTO](https://gcc.gnu.org/wiki/LinkTimeOptimization) feature
Changed:
Side effects:
none
none
---

fix some codes that violates the C++ One Definition Rule [-Wodr]

---

src/brpc/details/naming_service_thread.cpp
src/brpc/details/naming_service_thread.h

Issue Number:
当channel并发Init的时候，其中一个线程负责Start ns，其他线程则WaitForFirstBatchOfServers。这时候如果Start失败了，并没有唤醒其他线程，其他线程则会一直在等。
Start失败则通过EndWait唤醒其他线程。
Changed:
Side effects:
---

Fix not end wait when ns fails to start

---

.github/workflows/ci-linux.yml
.github/workflows/ci-macos.yml

Issue Number: N/A
- The entire GitHub workflow is run, even for changes that do not require a build, such as for markdown file changes. This [PR](https://github.com/apache/brpc/pull/2153) is an example of the entire workflow being run for an update to the `oncall.md` file. It takes approximately 30 minutes for the entire Github CI workflow to run and developers commit a standalone markdown file change at least 2 times per month.
Changed:
- Update GitHub workflow files to skip the `ci-linux` and `ci-macos` workflows for pushes and pull requests when the only changes are to markdown files. The result is less time spent waiting for builds to pass on both pushes and pull requests for Markdown file changes, which currently takes 30 minutes. Now, only the license check should …

Update workflows to skip builds for markdown-file-only changes

---

CONTRIBUTING.md

Issue Number: N/A
- A Travis CI build was last run 4 months ago, however, it is still mentioned in the contributing guidelines. The new process is to check that GitHub Actions pass.
Changed:
- Update `CONTRIBUTING.md` to specify checking GitHub Actions instead of checking Travis CI.
Side effects:
---

Update CI check in CONTRIBUTING.md

---

src/brpc/policy/domain_naming_service.cpp

Issue Number:https://github.com/apache/brpc/issues/1911
hostname maybe exceed to 128 bytes according to [RFC 1035 section 2.3.4](http://www.freesoft.org/CIE/RFC/1035/9.htm).
https://github.com/apache/brpc/pull/1965 has fixed this problem, but missing `src/brpc/policy/domain_naming_service.cpp` .
Changed:
Side effects:
---

Fix domain naming service host name buffer length

---

example/rdma_performance/CMakeLists.txt

compile failed with error "error: macro "__has_attribute" requires an identifier".
Issue Number:
Changed:
Side effects:
---

fix the issue of const unused in the example of RDMA

---

README.md
README_cn.md

Issue Number: #2211
Problem Summary: README h2 link is invalid
Changed: Replace https://http2.github.io/http2-spec to https://httpwg.org/specs/rfc9113.html
Side effects:
---

update h2 link in README and README_cn

---

src/brpc/rdma/rdma_helper.cpp

Issue Number: https://github.com/apache/brpc/issues/2213
Problem Summary: rdma::GlobalRelease runs before event dispatcher is stopped. It may incur coredump during program exit.
Changed: the order of atexit on rdma::GlobalRelease
Side effects:
---

avoid rdma::GlobalRelease before event dispatcher is stopped

---

src/butil/containers/flat_map_inl.h

Issue Number:
Changed:
精简FlatMap的operator[]函数的重复代码。
Side effects:
---

refactor: reduce code for operator[] of FlatMap

---

src/brpc/policy/http_rpc_protocol.cpp
src/brpc/policy/http_rpc_protocol.h

Issue Number:
Changed:
Side effects:
---

Set http default method to "/"

---

CMakeLists.txt
src/bthread/task_group.cpp
src/butil/thread_local.h

Issue Number:https://github.com/apache/brpc/issues/1776, https://github.com/apache/brpc/issues/1407, https://github.com/apache/brpc/issues/845,https://github.com/apache/brpc/issues/1860, https://github.com/apache/brpc/issues/1860, https://github.com/apache/doris/pull/13270 
一些编译器会优化 thread_local 的变量的读写，在同一个函数中间如果再次获取相同变量的值时，会直接从缓存的地址里面进行加载。但是如果在函数过程中间，线程发生切换（ bthread 切换到另一个线程执行)，那么 thread_local 变量需要重新获当前运行线程的，而不应该使用之前的旧值。
经测试，Apple M1 Apple clang version 14.0.0, 编译依然存在该问题：
task_runner 函数的部分汇编代码：
```
1923 00000000000017cc <__ZN7bthread9TaskGroup11task_runnerEl>:
1924 ; void TaskGroup::task_runner(intptr_t skip_remained) {
1925     17cc: ff c3 03 d1   sub     sp, sp, #240
1926     17d0: fd 7b 0e a9   stp     x29, x30, [sp, #224]
1927     17d4: fd 83 03 91   add     x29, sp, …
```

fix compiler optimize thread local variable access

---

src/brpc/interceptor.h
src/brpc/policy/baidu_rpc_protocol.cpp
src/brpc/policy/http_rpc_protocol.cpp
src/brpc/policy/hulu_pbrpc_protocol.cpp
src/brpc/policy/nshead_protocol.cpp
src/brpc/policy/sofa_pbrpc_protocol.cpp
src/brpc/policy/thrift_protocol.cpp
src/brpc/server.cpp
src/brpc/server.h
test/brpc_interceptor_unittest.cpp

Issue Number: #2134
支持自定义服务端拒绝（拦截器）
Changed:
Side effects:
---

Support user interceptor of server

---

docs/cn/http_client.md
docs/en/http_client.md

Issue Number: #1927
Changed:
Side effects:
---

HTTP error code doc

---

src/bthread/butex.cpp
test/bthread_butex_unittest.cpp

wait_pthread处理被信号中断的情况。
没有这个处理之前，假设butex_wait_from_pthread的timeout设置为100s，但是这个线程每隔10s会被信号中断（如正在进行profile，会定时中断采集线程堆栈），futex_wait_private会返回EINTR，导致butex_wait_from_pthread永远不会超时返回。

Fix butex wait_pthread handle EINTR

---

src/bvar/multi_dimension_inl.h
test/bvar_multi_dimension_unittest.cpp

Issue Number:  #2237 
The delete_stats() function of MultiDimension may casue segment fault.
Changed:Fix bug of delete_stats() function of MulitDimension.
Side effects:
---

Fix possible segment fault in delete_stats() of MultiDimension. (#2237)

---

src/brpc/rdma/rdma_helper.cpp

Issue Number:
If host has multiple HCAs and no explicit device name was given. The last one is actually used. See https://github.com/apache/brpc/blob/da5468a424eb75c044362f147eba528776af4bbe/src/brpc/rdma/rdma_helper.cpp#L430-L435
Changed:
Side effects:
---

Correct RDMA device logging

---

src/brpc/input_messenger.cpp

线上升级到brpc-1.3后偶现一些随机的coredump，最后定位到bthread栈上数据被踩了

Fix stack buffer overflow issue when calling copy_to_cstr

---

src/brpc/rdma/rdma_helper.cpp

When there are multiple HCAs, current implementation defaults to the last device. Previous opened device was not closed. 
Issue Number:
Changed:
Side effects:
---

Fix resource leak when there are multiple HCAs

---

WORKSPACE
bazel/BUILD.bazel
test/BUILD.bazel

Replace deprecated bazel compile commands extractor. We have been using [ Hedron's extractor](https://github.com/hedronvision/bazel-compile-commands-extractor) for years. Works perfectly for large projects. Also it's active maintained
> https://github.com/grailbio/bazel-compilation-database#status
This repository is now in maintenance mode. 
Issue Number:
Changed:
Side effects:
---

Use Hedron's Compile Commands Extractor for Bazel

---

test/brpc_socket_unittest.cpp

Issue Number:
Problem Summary: fd通过SocketOption传入，成功创建Socket之后，fd的所有权就转移到Socket了，因此不需要再通过fd_guard释放
Changed:
Side effects:
---

Fix unstable keepalive ut

---

src/brpc/input_messenger.cpp
src/brpc/input_messenger.h

高版本编译器编译的brpc，用户异常抛到brpc框架内部导致core栈不完整
Issue Number:
[程序内部core但是core栈不完整 #1997](https://github.com/apache/brpc/issues/1997)
[运行一段时间，就会core在brpc内部 #1437](https://github.com/apache/brpc/issues/1437)
[crash #985](https://github.com/apache/brpc/issues/985)
高版本GCC编译器(如GCC12)对于析构函数默认是noexcept的（也有人说是因为C++标准的问题 比如C++11之后才默认noexcept，但是GCC12下我使用C++11和C++17都是默认noexcept的）, 低版本的GCC82默认就是noexcept（false）的。
所以当你使用了高版本GCC编译程序的时候，业务代码抛出异常，在进行栈回溯之前会先沿着调用栈寻找处理异常的代码块(专业名词是Landing pad)，如果找到Landing pad，那么就会进行栈回溯到Landing pad进行异常处理。找不到Landing pad就会原地调用std::terminate终止程序，这个时候你的core栈就是完整的，不会回溯陷入brpc框架。
从我的测试看，Landing pad 一种是真正的 try catch 块，另一种就是整个调用链上有noexcept属性的函数结束的代码段地址(汇编代码就是一块Unwind_Resume代码块)，brpc整个调用链上没有try catch 非 bthread::ExitException 异常的Landing pad。 …

fix coredump stack uncomplete when usercode throw exceptions

---

src/brpc/details/hpack.cpp
src/brpc/span.cpp
src/bvar/detail/sampler.cpp

Issue Number:
#2242 
(warning: variable 'nremoved' set but not used [-Wunused-but-set-var)
remove not used variable to fix the compile warnnings
Changed:
Side effects:
No impact
No compatibility issue
---

Fix compilation errors reported by clang-14 (#2242)

---

src/butil/thread_local.h

Issue Number: #845
使用Clang-16去编译BRPC，在x86_64平台上也会出现"sched_to itself"的问题。在Linux x86_64以及macOS x86_64上均能复现。
Changed: 在x86_64平台上用Clang编译器的时候禁用thread local变量的优化。
Side effects:
- Performance effects(性能影响): 使用Clang编译器的时候不采用thread local变量优化。
- Breaking backward compatibility(向后兼容性): 无
---

fix compiler optimize thread local variable access on x86_64

---

src/butil/logging.cc
src/butil/logging.h
test/logging_unittest.cc

Issue Number:
打印日志所在函数的函数名，形如：
```shell
E0711 15:14:01.830110 12735 server.cpp:752 StartInternal] xxxx
```
Changed:
Side effects:
---

Log function name

---

src/brpc/controller.cpp

Issue Number:
Changed: Add graceful exit GFLAG for SIGHUP
Side effects:
- Performance effects(性能影响): no
- Breaking backward compatibility(向后兼容性):  no
---

Add graceful exit GFLAG for SIGHUP

---

src/butil/string_printf.cpp
src/butil/string_printf.h
test/string_printf_unittest.cpp

Issue Number:
Changed:
增加一个string_printf重载函数，支持用户传入格式化字符串的长度，避免调用两次vsnprintf。
Side effects:
---

Support hint size of formatted string for string_printf 

---

src/brpc/socket.cpp
src/brpc/socket.h

OpenSSL does not guarantee that any of its objects can be used concurrently by multiple threads:
https://github.com/openssl/openssl/issues/2165
https://github.com/openssl/openssl/issues/20446
Related issue with this PR: #2166
And this PR is not the best solution for this core issue.
The best way is put SSL obj's read/write operate in same event loop but this changes too much of the current code structure, i'm too lazy to do it.

Fix core when ssl is enabled

---

src/brpc/global.cpp

Issue Number:
There is a crash issue that at beginning many library concurrently ignore SIGPIPE to assert failed.
none
Changed:
none
Side effects:
none
none

fix ignore SIGPIPE signal concurrent issue with other library

---

src/brpc/policy/round_robin_load_balancer.cpp

Issue Number:
如果每次都是在新线程去使用rr的client，tls.offset会清空，然后重新选一个质数去取模机器数，极端情况下会出现有些机器永远都选不中的情况，server端的qps会出现明显倾斜的情况
****
Changed:
tls.offset = butil::fast_rand_less_than(n);
在第一次使用offset时使用随机数而不是取值为0，这样可以避免第一次使用的质数的个位数只能是（1,3,7,9）这些数字的问题
Side effects:
很小
无
---

round robin load_balancer优化：在第一次初始化时offset使用随机数，以适配每次都是在新线程使用的场景

---

src/butil/containers/flat_map.h

Issue Number:
`FlatMap` 中 `Bucket` 的 `Element` 用于存放用户的 key 和 value，初始化 element 的空间（`element_space`) 地址要满足 Element 的对齐要求。
未修改前，可以看到 element_space 的起始地值，并未满足 Element 的对齐要求：
```
249      struct Bucket {
250          explicit Bucket(const _K& k) : next(NULL)
-> 251          { new (element_spaces) Element(k); }
...
(lldb) p &element_spaces
(char (*)[128]) $1 = 0x0000000000385428
(lldb) p alignof(Element)
(unsigned long) $2 = 16
```
> 5.3.4 New [expr.new] 
[14] Note: when the allocation function returns a value other than null, it must be a pointer to a block of storage in which space for the object has been reserved. The block of storage is assumed to be appropriately aligned and of the requested size.
一些编译器在开启优化选项后，会根据数据的对齐字节，而选择更高效的指令，例如 `movaps`, …

fix flatmap element space should align with usertype

---

src/butil/thread_local.h

Issue Number: https://github.com/apache/brpc/issues/2318
Problem Summary: 在arch64下使用gcc编译，运行单测会报错。
Changed: 在arch64 + gcc的环境中禁止thread_local访问优化。
Side effects:
- Breaking backward compatibility(向后兼容性):  是
---

Fix unit test running error under arch64

---

CMakeLists.txt
example/asynchronous_echo_c++/CMakeLists.txt
example/auto_concurrency_limiter/CMakeLists.txt
example/backup_request_c++/CMakeLists.txt
example/cancel_c++/CMakeLists.txt
example/cascade_echo_c++/CMakeLists.txt
example/dynamic_partition_echo_c++/CMakeLists.txt
example/echo_c++/CMakeLists.txt
example/grpc_c++/CMakeLists.txt
example/http_c++/CMakeLists.txt
example/memcache_c++/CMakeLists.txt
example/multi_threaded_echo_c++/CMakeLists.txt
example/multi_threaded_echo_fns_c++/CMakeLists.txt
example/nshead_extension_c++/CMakeLists.txt
example/nshead_pb_extension_c++/CMakeLists.txt
example/parallel_echo_c++/CMakeLists.txt
example/partition_echo_c++/CMakeLists.txt
example/rdma_performance/CMakeLists.txt
example/redis_c++/CMakeLists.txt
example/selective_echo_c++/CMakeLists.txt
example/session_data_and_thread_local/CMakeLists.txt
example/streaming_echo_c++/CMakeLists.txt
src/CMakeLists.txt

Issue Number: fix typo of 
THRIFTNB_LIB was removed in #888 
BRPC_WITH_THRIFT BRPC_WITH_GLOG was renamed to WITH_THRIFT WITH_GLOG in #383
Contribute previous [modifications](https://github.com/microsoft/vcpkg/pull/32705/files) to upstream
Problem Summary: remove unnecessary libthriftnb
Changed:None
Side effects:
- Performance effects(性能影响):None
- Breaking backward compatibility(向后兼容性): None
---

remove unnecessary libthriftnb

---

BUILD.bazel

Issue Number:
#2306 introduced a new include in butil/macros.h, this dependency is missing in bazel macos_lib rule.
Changed:
- Added butil/string_printf.h to macos_lib header list.
Side effects:
n/a
n/a
---

Fix macOS bazel build

---

test/iobuf_unittest.cpp

Issue Number: #2345
由于iobuf_unittest.cpp文件中append_store_append_cut测试用例删除/dev/null，导致在for循环中在执行open时重新创建了一个文件类型的/dev/null，从而引发系统问题
Changed: 当检测到是/dev/null, 不对其进行删除
Side effects:
无
无
---

Don't delete when the file is /dev/null

---

src/brpc/redis_reply.h

redis response swap operation may cause memory leaks
Issue Number:
redis reply _arena address should be the same as respone, otherwise, there may be a memory leak.
> test code
```
brpc::RedisResponse resp1;
std::cout << "response 1 arena address:"<< &(resp1._arena) << std::endl;
std::cout << "first reply arena address:" << (resp1._first_reply._arena) << std::endl;
brpc::RedisResponse resp2;
std::cout << "response 2 arena address:"<< &(resp2._arena) << std::endl;
std::cout << "first reply arena address:" << (resp2._first_reply._arena) << std::endl;
resp1.Swap(&resp2);
std::cout << "========= swap ============" << std::endl;
std::cout << "response 1 arena address:"<< &(resp1._arena) << std::endl;
std::cout << "first reply arena address:" << (resp1._first_reply._arena) << …
```

fix-redis-response-swap-mem-leak

---

src/brpc/esp_message.cpp
src/brpc/memcache.cpp
src/brpc/nshead_message.cpp
src/brpc/redis.cpp
src/brpc/thrift_message.cpp

GOOGLE_CHECK_NE 源自 protobuf，但是最新版本的 protobuf 去掉了这个宏定义，因此会导致编译出错。
Changed:
Side effects:
无影响
无影响
---

将 GOOGLE_CHECK_NE 替换成 CHECK_NE

---

src/brpc/http_header.cpp
src/brpc/http_header.h

Issue Number:
https://github.com/apache/brpc/blob/2729272ae5ee69e4c4142d14b7fafbf800944316/src/brpc/details/http_message.cpp#L576-L583
如果一次http请求中，同时调用了`set_content_type`和`SetHeader("Content-Type")`，那么`MakeRawHttpRequest`后的http包中会有两个`Content-Type` header。
Changed:
Side effects:
---

Fix duplicate content type

---

src/brpc/selective_channel.cpp

测试发现，channel类型是selective_channel时client收不到server填充的response_attachment。

selective_channle支持返回response_attachment

---

src/brpc/controller.cpp
src/brpc/controller.h
src/brpc/socket.cpp
src/brpc/socket.h
src/brpc/stream.cpp
src/brpc/stream.h
src/brpc/stream_impl.h

Add write_in_background option to Socket::StartWrite.
StreamWrite and async RPC call could pass write_in_background option to create background bthread to write to socket so that current thread won't block for 10-20us writing to socket.

Add option for StreamWrite and Async RPC to write to socket in background bthread.

---

docs/cn/server.md
docs/en/server.md
src/brpc/adaptive_protocol_type.h
src/brpc/details/ssl_helper.cpp
src/brpc/details/ssl_helper.h
src/brpc/server.cpp
src/brpc/server.h
src/brpc/ssl_options.h
test/brpc_alpn_protocol_unittest.cpp
test/brpc_ssl_unittest.cpp

Issue Number: #1991
Problem Summary: 当前bRPC中进行SSL/TLS握手阶段没有支持ALPN扩展协议。
Changed:  在ServerSSLOptions中扩展ALPN配置项。
Side effects:
- Performance effects(性能影响):  当用户在ServerSSLOptions中设置ALPN选项时，server启动时会将ALPN选项序列化为标准格式并设置好回调函数。在SSL/TLS握手阶段会调用回调函数选择匹配的协议并返回给客户端。
- Breaking backward compatibility(向后兼容性): 是
---

Server support ALPN with OpenSSL

---

src/bvar/multi_dimension_inl.h

Issue Number:
I found a coredump in ut MultiDimensionTest:mlatencyrecorder and the asan prompt:
Changed:
Side effects:
---

fix ut MultiDimensionTest:mlatencyrecorder coredump

---

example/redis_c++/redis_server.cpp

Issue Number:
Redis service handler should be released after server stopped.
Changed:
Using `unique_ptr` wrap `GetCommandHandler` and `SetCommandHandler` pointer.
Side effects:
No
No
---

fix redis server example handler memory leak

---

CMakeLists.txt
config_brpc.sh
example/thrift_extension_c++/native_client.cpp
example/thrift_extension_c++/native_server.cpp
src/CMakeLists.txt
src/brpc/policy/thrift_protocol.cpp

Issue Number: #1328 
When using thrift version greater than 0.13.0, brpc can't compile correctly due to deprecate of boost.
Changed:
Now compile logic works as follow:
For version < 0.11, set _THRIFT_VERSION_LOWER_THAN_0_11_0_ in cmake and using boost
For 0.11 <= version < 0.13, _THRIFT_STDCXX_H_ is set inside thrift/stdcxx.h and use apache::thrift::stdcxx
For later, just use std
Side effects:
No
No, later version of thrift use std as well.
---

fix thrift version gt 0.13.0

---

src/brpc/details/http_message.cpp
src/brpc/details/http_message.h
src/brpc/policy/http_rpc_protocol.cpp
src/brpc/policy/http_rpc_protocol.h
src/brpc/socket.cpp
src/brpc/socket.h
test/brpc_http_message_unittest.cpp
test/brpc_http_rpc_protocol_unittest.cpp
test/echo.proto

Issue Number: fix #764
解析HTTP HEAD请求的回包时，如果回包header中content-length不为0或者transfer-encoding为shunked，on_headers_complete未返回1，则parser会继续解析body。但是HTTP回包是不包含body部分的，就导致会parser一直等到rpc超时。
https://github.com/apache/brpc/blob/4fa4bcda3cf9ae28a3036a564bd1085581c0263c/src/brpc/details/http_parser.cpp#L1744-L1752
https://github.com/apache/brpc/blob/4fa4bcda3cf9ae28a3036a564bd1085581c0263c/src/brpc/details/http_parser.cpp#L1753-L1766
Changed:
Side effects:
---

Fix HTTP HEAD method

---

src/brpc/stream.cpp

fix stream logic while options.max_buf_size < 0
_cur_buf_size is size_t, options.max_buf_size is int.  options.max_buf_size 赋值 会导致错误的含义。
Issue Number:
Changed:
Side effects:
---

fix stream while max_buf_size < 0

---

docs/cn/http_service.md
docs/en/http_service.md
example/http_c++/http.proto
example/http_c++/http_server.cpp

Issue Number:
NA
添加了使用brpc 实现HTTP SSE功能的例子，可以用于brpc支持如大语言模型推理服务化等功能
Changed:
在example/http_c++中添加了一个HttpSSEServiceImpl实现。
具体而言，server端依次发送以下内容
1. 发送包含如下头部信息的HTTP response
```
Content-Type: text/event-stream
Cache-Control: no-cache
Connection: keep-alive
```
2. 后续HTTP server基于`ProgressiveAttachment`向客户段发送SSE的消息，格式：
```
[field]: value\n
```
其中， field可以取四个值，它们分别是：data、event、id、retry
Side effects:
NO impact
NO compatibiltiy issue
---

add HTTP server-sent-events(SSE) example in brpc http server

---

src/brpc/policy/http2_rpc_protocol.cpp
test/brpc_http_rpc_protocol_unittest.cpp

Issue Number:
Changed:
Side effects:
---

use AppendHeader for http2

---

src/brpc/socket_map.cpp
src/brpc/socket_map.h

Issue Number:
Changed:
尽快创建_this_map_bvar，便于调试。
Side effects:
---

Fast show socket map in vars

---

src/butil/third_party/dynamic_annotations/dynamic_annotations.c
src/butil/third_party/dynamic_annotations/dynamic_annotations.h

fixes #1931 
Issue Number:
Changed:
Side effects:
---

changed long to size_t in AnnotateBenignRaceSized function 

---

BUILD.bazel
CMakeLists.txt
Makefile
src/butil/thread_key.cpp
src/butil/thread_key.h
test/BUILD.bazel
test/CMakeLists.txt
test/Makefile
test/thread_key_unittest.cpp

Issue Number:
对于pthread_key使用比较多的场景，pthread_key的硬上限（1024）太小了，不能满足需求。
Changed:
参考bRPC中WrapperTLSGroup和pthread_key，实现了thread_key_xxx，解决pthread_key硬上限（1024）太小的问题。
thread_key_xxx接口与pthread_key_xxx接口一一对应。同时在thread_key_xxx的基础上封装了ThreadLocal模板类，方便用户使用tls。
Side effects:
---

Thread local without limit by _SC_THREAD_KEYS_MAX

---

src/butil/files/dir_reader_unix.h

Issue Number:
`DirReaderPosix` 析构时关闭只应调用 `closedir(dir_)` ， 不应同时调用 `close(fd_)`, 否则会导致同一个 `fd` 被close 两次。
> Upon	calling	closedir() the file descriptor is closed. 
https://man.freebsd.org/cgi/man.cgi?query=fdopendir&sektion=3
https://pubs.opengroup.org/onlinepubs/9699919799/functions/fdopendir.html
PoC : 
如果在 `close(fd_)` 和 `closedir(dir_)` 之间有新的 `open` 操作，`fd_` 可能会被复用，则 `closedir(dir_)` 导致该新 open 的 `fd_` 失效，后续对 `fd_` 的操作将会导致 `errno = 9 (Bad File Descriptor)` 错误。
ps: 实际情况可能是在多个线程中触发，这里以单线程代码说明：
``` c++
#include <stdio.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdlib.h>
#include <errno.h>
#include <unistd.h>
#include <assert.h>
#include <string.h>
int main(int argc, char *argv[])
{
DIR *d;
struct dirent *dp;
int dfd = 0;
if ((d = …
```

fix DirReaderPosix close same fd twice

---

src/brpc/rdma/rdma_endpoint.cpp
src/brpc/rdma/rdma_endpoint.h
test/brpc_rdma_unittest.cpp

It has no effect for `huge` type of recv_block_size
which is as large as 2^21, because the `block_size`
variable is defined as type `uint16_t`, its maximum
value is 2^16. So, change the type of `block_size`
to `uint32_t` with relevant updates.
Issue Number:
Changed:
Side effects:
---

fix `huge` rdma_recv_block_type no effect issue.

---

example/asynchronous_echo_c++/server.cpp
example/echo_c++/server.cpp
example/http_c++/http_server.cpp
src/brpc/controller.cpp
src/brpc/controller.h
src/brpc/policy/baidu_rpc_protocol.cpp
src/brpc/policy/http_rpc_protocol.cpp
test/brpc_channel_unittest.cpp

1.我们的场景希望将响应时间减少到最小，所以希望将一些类似数据上报的耗时操作（是的，特别耗时）放在response返回之后、request/response析构之前做
2.本pr借鉴了 #1433 ，看这个pr一直没合入且测试发现有些问题&不太满足我们的需要，所以另提一个。 #1433  的问题主要是：
（1）太多无关topic的改动
（2）仅在SendRpcResponse成功时才调用call_after_rpc_resp函数，失败时没有调用（我们需要无论成功或失败都要调用）
（3）定义的after_resp_fn_t不包含controller指针，我们需要拿到controller对象（进而拿到session data指针，所以声明为非const指针）
3.同样在目前在常用的 baidu_std/http/http2 协议上支持。其他协议未开发。
4.将Controller与req、res的析构顺序进行了修改，依赖关系应该是controller依赖req、res，所以应该先析构controller，后析构req、res
麻烦maintainers看看有什么不妥之处~

send response之后，request/response对象析构之前执行一些自定义逻辑

---

.licenserc.yaml
BUILD.bazel
CMakeLists.txt
LICENSE
Makefile
src/butil/base64url.cc
src/butil/base64url.h
test/BUILD.bazel
test/CMakeLists.txt
test/Makefile
test/base64url_unittest.cc

Issue Number:
目前有将url参数进行base64编码的需求，需要bRPC支持url safe base64。
Changed:
引入chromium base64url（为适配bRPC，存在少量改动），参考：
- https://github.com/webrtc-uwp/chromium-base/blob/master/base64url.cc
- https://github.com/webrtc-uwp/chromium-base/blob/master/base64url.h
- https://github.com/webrtc-uwp/chromium-base/blob/master/base64url_unittest.cc
Side effects:
---

Support url safe base64

---

src/brpc/policy/http2_rpc_protocol.cpp

when use h2:grpc protocol pass nginx,  if nginx not support dynamic HPACK,  it will set SETTINGS_HEADER_TABLE_SIZE value to 0，now brpc not address this case.
https://trac.nginx.org/nginx/ticket/1538
rfc reference: https://datatracker.ietf.org/doc/html/rfc9113 4.3.1
Issue Number:
https://github.com/apache/brpc/issues/2286
https://github.com/apache/brpc/issues/2176
ignore a h2 protocol param set case
Changed:
add a if check when encode h2 header
Side effects:
It hardly makes a difference
completely compatible
---
- Please follow [Contributor …

fix h2 protocol abnormal  case when SETTINGS_HEADER_TABLE_SIZE set to zero

---

src/brpc/socket_map.cpp

Issue Number:
目前brpc会将连接池里空闲的连接关闭，这样对于比较低频的rpc来说，如果rpc周期大于FLAGS_idle_timeout_second，那每次都要新建连接，不太友好。
Changed:
支持连接池保留至少一个空闲连接。
Side effects:
---

Reserve at least one idle socket

---

src/brpc/builtin/prometheus_metrics_service.cpp
test/brpc_prometheus_metrics_service_unittest.cpp

Issue Number: #2082
Changed:
Side effects:
---

Fixup mbvar convert prometheus metrics format issue (#2082)

---

src/brpc/channel.h

Issue Number:
禁用Channel拷贝和赋值操作：
1. 拷贝得到Channel并一定能使用（不知道是否Init）
2. 拷贝后，未再次执行SocketMapInsert令_server_id的引用计数加一。这样，只要有一个Channel析构了，就会将_server_id从SocketMap里删除，其他Channel副本的RPC调用都会失败。
Changed:
Side effects:
---

Disallow copy and assign of Channel

---

src/brpc/stream.cpp

Issue Number:
#2280 中Socket::StartWrite的write_in_background并未生效。
Changed:
Side effects:
---

Fix stream write in background not work

---

src/brpc/details/http_parser.h
src/brpc/policy/baidu_rpc_protocol.cpp

Issue Number:
http_parser.content_length有误，应该修改为以下：
https://github.com/nodejs/http-parser/blob/ec8b5ee63f0e51191ea43bb0c6eac7bfbff3141d/http_parser.h#L311-L313
Changed:
Side effects:
---

Fix comment of http parser and some typos

---

src/brpc/policy/locality_aware_load_balancer.cpp

Issue Number:
[#2427](https://github.com/apache/brpc/issues/2427)
lalb在有可用节点的情况下仍可能触发“[E112]Fail to select server...”
Changed:
Side effects:
可能会增加lalb的长尾
---

lalb try left server nodes

---

src/brpc/socket.cpp
src/butil/iobuf.cpp

Issue Number: #977
对端发送完数据后关闭连接或者shutdown ssl，就有可能出现ssl_error=SSL_ERROR_SYSCALL/SSL_ERROR_ZERO_RETURN、nr>0、e=0，这应该是正常情况，没有必要打印WARNING日志。
Changed:
Side effects:
---

Opt ssl read log

---

src/bthread/task_group.cpp

Issue Number:
_add_sleep_event失败后，bthread_usleep并没有真正sleep，只是重新调度了，这时候应该返回错误。一些场景下会有死循环风险，例如：
https://github.com/apache/brpc/blob/13a07174eab6ce4ae898ecf2bdb5e1144f7df313/src/brpc/periodic_naming_service.cpp#L64-L71
Changed:
Side effects:
---

usleep returns ESTOP when schedule timer failed

---

src/brpc/details/http_message.h

Issue Number: 2473
Changed: add #include <memory> in brpc/details/http_message.h
Side effects:
None
None
---

add #include <memory> in brpc/details/http_message.h for compilation in CentOS8

---

src/brpc/parallel_channel.cpp
src/brpc/parallel_channel.h

Issue Number:Closes-https://github.com/apache/brpc/issues/2466
Changed:
Side effects:
---

Optimize ParallelChannel AddChannel Interface

---

src/butil/memory/ref_counted.h
test/ref_counted_unittest.cc

Issue Number:
scoped_refptr 使用 nullptr 移动构造时会导致 ptr_ 未初始化，从而有可能导致内存问题
Changed:
Side effects:
- Breaking backward compatibility(向后兼容性): 无
---

Fix scoped_refptr leave ptr_ uninit when move construct by nullptr

---

test/CMakeLists.txt

Problem Summary: when passing `-DCMAKE_CPP_FLAGS="-D_FORTIFY_SOURCE=2"` (for example, in Debian packaging), this doesn't get propagated in the `tests/` directory
Changed: pass the command-line `CMAKE_CPP_FLAGS` into tests/ compilation…
Side effects:
- None

tests: use global CMAKE_CPP_FLAGS

---

src/brpc/acceptor.cpp
src/brpc/details/http_message.h
src/brpc/server.cpp
src/bthread/bthread.cpp
src/bthread/task_group.cpp
src/bthread/types.h

Issue Number:
Changed:
Side effects:
---

modify bthread attribute with tag

---

src/brpc/details/http_message.cpp
src/brpc/policy/http_rpc_protocol.cpp
src/brpc/policy/http_rpc_protocol.h
test/brpc_http_rpc_protocol_unittest.cpp
test/echo.proto

Issue Number:
客户端使用libcurl请求brpc http服务端，偶现耗时超过1秒。经排查，发现是libcurl当使用Post或者Put方法，请求体超过一定大小(一般是 1024 字节)时，libcurl 自动添加”Expect: 100-continue”请求头，先发送header，等到服务端确认能接收body，收到服务端的100 continue response或者超过1秒，才发送body部分数据给服务端。
详细见[libcurl Expect 100-continue](https://everything.curl.dev/http/post/expect100) 和[rfc7231](https://datatracker.ietf.org/doc/html/rfc7231#section-5.1.1)。
Changed:
1. 客户端组包的时候移除expect: 100-continue header。请求带上expect: 100-continue后，服务端可能会在收完header后先回100 continue response，等到收完body处理完再回200 ok response。brpc客户端不支持一个请求对应两个回包的场景。
2. 服务端解包时之解析出header，未收到body，先回100 continue response，等到收完body处理完再回200 ok response。
Side effects:
---
- …

Support 100-continue of server and remove expect header of request

---

src/brpc/channel.cpp

Issue Number:
lb (`LoadBalancerWithNaming`) 可能内存泄漏当 `CreateSocketSSLContext` 失败时。
Changed:
使用 `unique_ptr` 包裹 `lb` 临时对象，并在成功完成初始化后，将其生命周期转移给 `_lb`.
Side effects:
无
无
---

fix LoadBalancerWithNaming memory leak when ssl init failed

---

src/brpc/details/http_message.cpp
src/brpc/policy/http_rpc_protocol.cpp
test/brpc_http_message_unittest.cpp

Issue Number:
1. #2366 修复了HEAD请求的问题，但是一般情况下http service不会设置Content-Length，响应就不会包括Content-Length，没有达到HEAD请求的预期。
2. #2319 保证了Content-Type在HttpHeader是唯一的，那么在解包的时候，就不需要设置两次Content-Type了。https://github.com/apache/brpc/blob/dc9e786fbb5fd79f08b49fa8d55ec4e1a35f2125/src/brpc/details/http_message.cpp#L139-L143
Changed:
1. 当响应HEAD请求时，优先使用用户设置的Content-Length。如果用户没有设置Content-Length，则使用content的长度作为Content-Length的值。
2. 删除HttpMessage::on_headers_complete中重复设置Content-Type的重复逻辑。
Side effects:
--- …

Opt Content-Length in response to HEAD request

---

BUILD.bazel
CMakeLists.txt
config_brpc.sh
example/asynchronous_echo_c++/CMakeLists.txt
example/auto_concurrency_limiter/CMakeLists.txt
example/backup_request_c++/CMakeLists.txt
example/bthread_tag_echo_c++/CMakeLists.txt
example/cancel_c++/CMakeLists.txt
example/cascade_echo_c++/CMakeLists.txt
example/dynamic_partition_echo_c++/CMakeLists.txt
example/echo_c++/CMakeLists.txt
example/grpc_c++/CMakeLists.txt
example/http_c++/CMakeLists.txt
example/memcache_c++/CMakeLists.txt
example/multi_threaded_echo_c++/CMakeLists.txt
example/multi_threaded_echo_fns_c++/CMakeLists.txt
example/nshead_extension_c++/CMakeLists.txt
example/nshead_pb_extension_c++/CMakeLists.txt
example/parallel_echo_c++/CMakeLists.txt
example/partition_echo_c++/CMakeLists.txt
example/rdma_performance/CMakeLists.txt
example/redis_c++/CMakeLists.txt
example/selective_echo_c++/CMakeLists.txt
example/session_data_and_thread_local/CMakeLists.txt
example/streaming_echo_c++/CMakeLists.txt
src/brpc/builtin/index_service.cpp
src/bthread/mutex.cpp
src/butil/debug/stack_trace_posix.cc

Issue Number:
Problem Summary: SampledContention的哈希值只需要计算一次。
Changed:
Side effects:
---

Opt contention: support tcmalloc GetStackTrace and reduce hash calculations

---

tools/gdb_bthread_stack.py

Issue Number:
当 brpc 使用 libc++ 编译时，使用当前 gdb bthread 调试脚本会出现找不到符号错误（ `_M_i`, `._M_b._M_p` 等变量），这些变量应该是来自 [libstdc++](https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/std/atomic)  实现 `std::atomic` 的中的，而当使用 [libc++](https://github.com/llvm-mirror/libcxx/blob/master/include/atomic) 时没有这些变量，所以会出现此类错误。
```python
(gdb) bthread_begin 
Python Exception <class 'gdb.error'>: There is no member or method named _M_i.
Error occurred in Python: There is no member or method named _M_i.
```
Changed:
使用类型强转实现从 `atomic<T> ` -> `T` 的转化，避免使用特定标准库实现中的变量。
Side effects:
---
- When providing us with a new feature, it is best to add related …

fix gdb bthread stack lookup symbol error when using libc++

---

tools/lldb_bthread_stack.py

Issue Number:
新增支持 lldb 的 bthread 堆栈调试工具，使用方法和命令和 gdb 脚本保持一致。
1. lldb attach <pid>
2. command script import lldb_bthread_stack.py
3. bthread_begin
4. bthread_list
5. bthread_frame 0
6. bt / up / down
7. bthread_end
Changed:
Side effects:
---

add lldb bthread stack debug script

---

src/brpc/policy/http_rpc_protocol.cpp

Issue Number:
HttpResponseSender移动后，重置成员变量，合理一些。
Changed:
Side effects:
---

Opt HttpResponseSender move constructor

---

CMakeLists.txt
src/brpc/builtin/grpc_health_check_service.cpp
src/brpc/builtin/grpc_health_check_service.h
src/brpc/grpc_health_check.proto
src/brpc/server.cpp
test/brpc_builtin_service_unittest.cpp

支持grpc的健康检查协议
Issue Number:
Changed:
Side effects:
---

support grpc health check

---

src/butil/containers/mpsc_queue.h
src/butil/thread_key.h
test/BUILD.bazel
test/CMakeLists.txt
test/Makefile
test/mpsc_queue_unittest.cc

Issue Number:
Changed:
使用[ExecutionQueue](https://github.com/apache/brpc/blob/master/src/bthread/execution_queue.h)的相关技术实现一个多生产者单消费者的无锁队列。
Side effects:
---

Support A Multiple Producer, Single Consumer Queue

---

src/butil/iobuf.cpp
src/butil/iobuf.h
src/butil/iobuf_inl.h
test/iobuf_unittest.cpp

#2430
`IOBuf` is brpc's buffer type, which is designed to be compatible with many forms of the underlying data. For example, the `append_user_data` can append a piece of user data into an `IOBuf` without making any copy.
But this interface still has a limitation. Because it accepts deleter of type `void(*)(void*)` only, so that the deleter is unable to save any state or context.
Assume that the user uses a custom memory resource, such as c++17's pmr or some implementations of arena. User requests a large chunk of memory at once, then allocates the memory block monotonically from this chunk. It won't releases any memory unless the chunk is exhausted and all the allocated blocks are marked as "deleted". The usage `std::pmr::monotonic_buffer_resource` could have such behaviour.
However, …

change UserDataDeleter type from function ptr to std::function

---

src/butil/logging.cc
test/logging_unittest.cc

Issue Number:
Changed:
使用ExecutionQueue的相关技术支持异步日志
Side effects:
---

Support async logging

---

src/brpc/details/http_message.cpp
src/brpc/details/http_parser.cpp
src/brpc/details/http_parser.h
test/brpc_http_message_unittest.cpp

Issue Number:
1. [RFC 7230 3.3.3](https://datatracker.ietf.org/doc/html/rfc7230#section-3.3.3)规范：Content-Length和Transfer-Encoding: chunked不能一起使用，或者忽略Content-Length。目前brpc使用的http-parser版本比较旧，允许Content-Length和Transfer-Encoding: chunked一起使用，存在请求走私（Request Smuggling）和响应拆分（response splitting）的风险。
2. [RFC 7233 3.3.2](https://datatracker.ietf.org/doc/html/rfc7230#section-3.3.2)规范：有Transfer-Encoding的时候，发送者不能发送Content-Length。
Changed:
1. 引入最新[http-parser](https://github.com/nodejs/http-parser/blob/main/http_parser.c#L1808)中Content-Length和Transfer-Encoding相关的代码。解析http包时，默认拒绝同时存在Content-Length和Transfer-Encoding的http包。如果打开开关且Transfer-Encoding的最后一个编码是chunked时，则移除Content-Length，接受该http包。
2. 组http包时，有Transfer-Encoding，则移除且不添加Content-Length。
Side effects:
- …

Fix Content-Length and Transfer-Encoding problems

---

config_brpc.sh
src/bthread/task_group.cpp
src/bthread/task_meta.h

Issue Number:
#2435 的改动可能会导致bthread_usleep实际上成功执行，但是返回ESTOP失败。
`_add_sleep_event`函数中，在定时器添加成功后，`e.meta->current_sleep = sleep_id`之前，定时器执行，唤醒了协程。
https://github.com/apache/brpc/blob/09141d4d87e2a68736144ebc6dad55eba449c6cc/src/bthread/task_group.cpp#L757-L775
协程被唤醒后，`current_sleep`为0、`interrupted`为false，返回了ESTOP错误。
https://github.com/apache/brpc/blob/09141d4d87e2a68736144ebc6dad55eba449c6cc/src/bthread/task_group.cpp#L804-L808 
Changed:
使用一个特定的成员变量代替`current_sleep==0`来表示定时器添加失败。
Side effects:
--- …

Fix bthread_usleep return unexpected error

---

.github/workflows/cifuzz.yml

Integration of [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration) into the brpc repository.
I've scheduled CIFuzz to run every Sunday at 00:00, instead of on every pull request.
I made this change based on my previous CIFuzz integration experience https://github.com/apache/trafficserver/pull/10462.
If you prefer, I can change it to `on: [pull_request]`.

[Fuzzing] add cifuzz workflow

---

src/bthread/bthread.cpp
src/bthread/id.cpp
src/bthread/list_of_abafree_id.h
test/CMakeLists.txt
test/abalist_unittest.cc

Issue Number: https://github.com/apache/brpc/issues/2477
A GC solution was introduced to solve the infinite growth problem.
It will try to do a GC operation when it exceeds a certain size.
To avoid frequent invalid GCs, the GC threshold is not changed until the size < 4 after a GC, otherwise the GC threshold is doubled.
Changed:
Side effects:
- The initial GC SIZE is a relatively large value with limited impact
---

support gc for ListOfABAFreeId

---

src/bthread/bthread.cpp

Issue Number: [#2542](https://github.com/apache/brpc/issues/2542)
由于第二次解析bthread_concurrency_by_tag时，never_set_bthread_concurrency_by_tag被置为了true，但TaskControl仍为NULL，返回的EPERM导致，gflags的validate失败，从而导致上层应用报错。
Changed:
Side effects:
---

Fix gflags bthread_concurrency_by_tag validate failed

---

src/bthread/bthread.h
src/bthread/bthread_once.cpp
src/bthread/singleton_on_bthread_once.h
src/bthread/types.h
test/bthread_once_unittest.cpp
test/mpsc_queue_unittest.cc

Issue Number:
目前`get_leaky_singleton`是基于pthread_once实现的，也存在#2517 提到的死锁问题。
https://github.com/apache/brpc/blob/df69b95cced673a69beec874ddd4900d26d850eb/src/butil/memory/singleton_on_pthread_once.h#L54-L64
Changed:
1. 支持bthread_once。
2. 基于bthread_once实现bthread singleton，解决死锁问题。
Side effects:
---

Support bthread_once and bthread singleton

---

example/rpcz_echo_c++/CMakeLists.txt
example/rpcz_echo_c++/client.cpp
example/rpcz_echo_c++/echo.proto
example/rpcz_echo_c++/server.cpp
src/brpc/builtin/rpcz_service.cpp
src/brpc/global.cpp
src/brpc/span.cpp
src/brpc/span.h
src/brpc/span.proto
src/bthread/bthread.cpp
src/bthread/task_group.cpp
src/bthread/unstable.h
test/brpc_alpn_protocol_unittest.cpp
test/bthread_unittest.cpp

Issue Number:
Changed:
Side effects:
---

span for new bthread

---

src/bthread/task_group.cpp
test/bthread_key_unittest.cpp

Issue Number:
#2554
当一个bthread（taskmeta中的attr.keytable_pool = null）的生命周期结束，且其拥有keytable实例时。在销毁keytable时会调用由用户创建bthread_key_create(bthread_key_t* key, void (destructor)(void data))中传入的destructor析构函数，如果destructor内部使用了bthread-mutex并挂起的话，bthread恢复后所在的task_group会发生变化。在现有的task_runner实现中，如果在return_keytable后不重新指定task_group的话，调用ending_sched(&g)会出现错误。
Changed:
Side effects:
---

Fix using butex in return keytable

---

src/brpc/controller.cpp

Issue Number:
当bthread_id_create执行成功，Socket::Address执行失败是，callback会被执行。当Controller析构的时候，bthread_id_error会再次执行callback。如果callback执行完会被释放（brpc::NewCallback默认行为），那么这个场景下会出现double delete的问题。
Changed:
Side effects:
---

Fix cancel callback may be called twice

---

src/bvar/default_variables.cpp

Issue Number:
CachedReader::get_value中fn没有在锁内执行，第一次执行get_value的时候，可能会读到_cache的初始值。由于_cache没有显式初始化，而且实际的类型（如ProcMemory、ProcStat）没有实现默认构造函数，所以成员变量的值是随机值。相对于随机值，值为0，让人更好理解一些。
https://github.com/apache/brpc/blob/24fc31eaa56d8b522975ca41ed012faf6cf77438/src/bvar/default_variables.cpp#L147-L163
Changed:
Side effects:
---

Fix random value of CachedReader at first time

---

src/butil/containers/doubly_buffered_data.h

Issue Number:#2561
推测常量ELEMENTS_PER_BLOCK本意是一页可以容纳DoublyBufferedData::Wrapper的个数，误写成了sizeof(T)
DoublyBufferedData::Wrapper增加BAIDU_CACHELINE_ALIGNMENT修饰，避免伪共享
Changed:
Side effects:
---

Fix : ELEMENTS_PER_BLOCK may be incorrect

---

.github/workflows/ci-macos.yml
CMakeLists.txt
Makefile
config_brpc.sh
src/brpc/esp_message.h
src/brpc/global.cpp
src/brpc/memcache.h
src/brpc/nshead_message.h
src/brpc/pb_compat.h
src/brpc/redis.h
src/brpc/serialized_request.h
src/json2pb/json_to_pb.cpp
src/json2pb/pb_to_json.cpp

Issue Number: close #2537 
Problem Summary: compatible with protobuf >= 22
Changed:
Side effects:
---

Support Protobuf 22

---

src/brpc/protocol.cpp
src/json2pb/json_to_pb.cpp
src/json2pb/pb_to_json.cpp

Issue Number:
Problem Summary:  PR #2546 在Protobuf 22-24这几个版本上的编译有一些问题，在25版本上可以编译通过。同时在Rocky 8.9的GCC 13上编译发现，原有的 #define private public的方式已经不被编译器接受，也会导致编译失败。
Changed:  修复在Protobuf 22-24这3个版本上编译失败的问题。对于private的问题，对于高版本增加一个特殊处理解决编译问题。
Side effects:
- Performance effects(性能影响): 无影响
- Breaking backward compatibility(向后兼容性): 无影响
---

Fix compile with protobuf 22-25.

---

src/butil/iobuf.cpp

Issue Number:
In tests there are some places that don't clear previous allocated block before resetting allocation hooks and lead to asan error.
Changed:
Release lts blocks in `reset_blockmem_allocate_and_deallocate`.
Side effects:
None
- Breaking backward compatibility(向后兼容性):
None

test/iobuf: fix mismatch deallocation

---

src/brpc/policy/streaming_rpc_protocol.cpp
src/brpc/stream.cpp

Issue Number: resolve #2541 
Changed: 
Side effects:
---

Ignore eovercrowded for streaming control frame

---

src/brpc/details/health_check.cpp
src/brpc/socket.cpp

Issue Number:
在tcp连接成功，ssl握手失败的情况下，rpc_channel_connection_count会自增。随后fd被close，但是计数却没有减
Changed:
只有在Socket::ResetFileDescriptor被成功调用后再自增计数，以使close fd时减计数的逻辑生效
Side effects:
---

修复rpc_channel_connection_count

---

src/bthread/bthread.cpp
src/bthread/bthread.h
src/bthread/butex.cpp
src/bthread/task_control.h
src/bthread/task_group.cpp
src/bthread/task_group.h
test/BUILD.bazel
test/bthread_butex_multi_tag_unittest.cpp

Issue Number:
Changed:
Side effects:
---

support bthread primitive cross different worker pools

---

config_brpc.sh

Issue Number: #2591
abseil targets required by protobuf may be an interface only target, which should not be linked.
Changed:
Side effects:
---

Do not link abseil interface targets

---

.gitignore
src/brpc/controller.cpp
src/brpc/policy/baidu_rpc_protocol.cpp
src/brpc/socket.cpp
src/brpc/socket.h
src/brpc/stream.cpp
src/brpc/stream.h
src/brpc/stream_impl.h
test/brpc_streaming_rpc_unittest.cpp

Issue Number: resolve #2285 
Changed:
Side effects:
---

Support on_failed callback for streaming rpc

---

src/brpc/controller.cpp
src/brpc/errno.proto
src/brpc/socket.cpp
src/brpc/socket.h
test/brpc_socket_unittest.cpp

Issue Number:
Changed:
1. 支持半关闭：无需SetFailed，关闭写入端，但不影响读数据。
2. 支持在数据写入socket写入成功后调用id_wait回调函数：对于一些请求和响应不是一一对应的场景，例如WebSocket、TCP Stream客户端、Streaming rpc等，只需要关注数据是否写入成功。数据写入socket写入成功后调用id_wait回调函数，可以统计成功率、耗时等。#2545 
Side effects:
---

Support shutdown write and notify for success write

---

test/run_tests.sh

Issue Number:
https://github.com/apache/brpc/blob/6a335aa8bc713768aaa4dfcc5b1b2b66fe64e7a8/test/run_tests.sh#L37-L44
`run_tests.sh`中有问题，认为最新的core文件一定是失败的ut生成的，但是[ci](https://github.com/apache/brpc/actions/runs/8832477501/job/24249875410)中出现了对不上的情况：
>  1 FAILED TEST
corefile=./core.test_butil.8086 prog=brpc_grpc_protocol_unittest
Changed:
先将旧的core文件删除。
Side effects:
---

Fix incorrect core file in run_tests.sh

---

docs/cn/getting_started.md
docs/en/getting_started.md

Issue Number:
Changed:
Side effects:
---

Update protobuf version in doc

---

src/butil/containers/flat_map.h
src/butil/containers/flat_map_inl.h
test/flat_map_unittest.cpp

Issue Number:
```
butil::FlatMap<int, int> m1;
if (m1.init(32) != 0) {}
butil::FlatMap<int, int> m2 = m1;
```
`FLatMap::operator=`的逻辑有问题，即使m1已经初始化了，但是因为m1是空的，所以将m1赋值给m2后，m2仍然是未初始化的，一旦被使用，基本上就会出core。
Changed:
Side effects:
---

Fix FlatMap assign operator bug

---

src/brpc/reloadable_flags.h

Issue Number:
Changed:
限制BRPC_VALIDATE_GFLAG只能在全局作用域或者namespace中使用，避免注册失败导致运行中的进程退出了。
Side effects:
---

Restrict BRPC_VALIDATE_GFLAG to global scope and namespace scope only

---

src/brpc/policy/http2_rpc_protocol.cpp

Issue Number:
Changed:
Side effects:
---

Fix comparison warning in http2_rpc_protocol.cpp

---

docs/cn/bthread_tagged_task_group.md
example/bthread_tag_echo_c++/server.cpp
src/brpc/server.cpp
src/bthread/bthread.cpp

Issue Number:
Changed:
Side effects:
---

bthread set concurrency by tag

---

src/brpc/builtin/common.cpp
src/brpc/builtin/common.h
src/brpc/builtin/hotspots_service.cpp
src/butil/process_util.cc
src/butil/process_util.h

Issue Number:
从 cmdline 中获取程序名称时不包含程序的完整路径。因为程序的启动路径可能已经包含在了 $PATH 中，所以 cmdline 中只有程序的名称而没有路径信息，导致在使用 `ProgramCHECKSUM` 以及使用 `heap profile` 解析符号时找不到程序的具体位置而导致失败。
```
export PATH=$PATH:/path/to/echo_server
```
启动server
```
echo_server
```
获取程序的校验码会报错：
```
E20240515 10:57:13.508802 39562 common.cpp:318] Fail to open `echo_server': No such file or directory [2]
```
使用 Heap Profiler 会解析不了.
```
[20240515.110220.heap]
Using remote profile at echo_server.
Using local file ./rpc_data/profiling/000000000000000000000000ce010000/20240515.110220.heap.
The first profile should be a remote form to use /pprof/symbol
```
Changed:
- Linux 系统使用 readlink(/proc/self/exe) 获取程序绝对路径
- MacOSX 系统使用 proc_pidpath 获取当前进程的绝对路径
Side effects:
- Breaking backward …

Fix GetProgramName not contains absolute path from cmdline

---

src/butil/endpoint.cpp
src/butil/memory/scope_guard.h
test/scope_guard_unittest.cc

Issue Number:
Changed:
Side effects:
---

Support SCOPE_EXIT macro

---

src/brpc/mongo_service_adaptor.h
src/brpc/span.h

Issue Number:
Changed:
Side effects:
---

Add virtual destructors to MongoServiceAdaptor and SpanFilter

---

.github/workflows/ci-linux.yml
src/butil/logging.cc
test/logging_unittest.cc

Issue Number:
```
thread_num=1 log_type=sync log_size=100 count=462130 duration=2s qps=231065 average_time=4349.05us
thread_num=8 log_type=sync log_size=100 count=271989 duration=2s qps=135994 average_time=59007.1us
thread_num=1 log_type=async log_size=100 count=1449393 duration=2s qps=724696 average_time=1383.17us
thread_num=8 log_type=async log_size=100 count=952119 duration=2s qps=476060 average_time=17001.6us
```
目前异步日志（完全由异步线程落盘日志）的性能仅仅是同步日志的3倍左右，没达到每秒百万的级别。
通过cpu profiler分析发现，瓶颈在`PrintLogPrefix`，特别是`localtime_r`或者`localtime_s`（有锁）。
Changed:
将`PrintLogPrefix`逻辑后移到异步线程运行，加快`LOG(xxx)`的速度。
优化后，异步日志性能得到了很大的提升，性能是同步日志的十几倍以上。
```
thread_num=1 log_type=sync log_size=100 count=612247 duration=2s qps=306123 average_time=3287.74us
thread_num=8 log_type=sync log_size=100 …
```

Opt performance of async log

---

src/brpc/circuit_breaker.cpp
src/brpc/circuit_breaker.h
test/brpc_circuit_breaker_unittest.cpp

解决server在夯住的情况下，比如可以响应ping请求、但没法响应业务逻辑请求时，单次ping请求成功就可以从熔断恢复，然后需要重新采样才能继续熔断的问题。
Issue Number:
Changed:
Side effects:
---

circuit breaker with half open state

---

src/brpc/details/http_message.cpp
src/brpc/details/http_message.h
src/brpc/http_header.cpp
src/brpc/http_header.h
src/butil/containers/case_ignored_flat_map.h
src/butil/containers/flat_map.h
src/butil/containers/flat_map_inl.h
test/brpc_http_message_unittest.cpp
test/brpc_http_rpc_protocol_unittest.cpp
test/flat_map_unittest.cpp

Issue Number: resolve #2575 
目前bRPC处理cookie和set-cookie这两个header的逻辑有问题：
1. [RFC 9114](https://datatracker.ietf.org/doc/html/rfc9114#section-4.2.1)规定： 多个cookie不能用`,`分隔，应该要用`; `；
> If a decompressed field section contains multiple cookie field lines, these MUST be concatenated into a single byte string using the two-byte delimiter of "; " (ASCII 0x3b, 0x20) before being passed into a context other than HTTP/2 or HTTP/3, such as an HTTP/1.1 connection, or a generic HTTP server application.
3. [RFC 6265](https://datatracker.ietf.org/doc/html/rfc6265#section-3) 规定：多个set-cookie不能合并到一个header。
> Origin servers SHOULD NOT fold multiple Set-Cookie header fields into
a single header field.  The usual mechanism for folding HTTP headers
fields (i.e., as defined in …

Fix invalid headers of multiple cookie and set-cookie

---

src/bthread/butex.cpp
src/bthread/id.cpp
src/bthread/mutex.cpp
src/bthread/mutex.h
src/bthread/timer_thread.cpp
src/bthread/timer_thread.h
test/bthread_mutex_unittest.cpp

Issue Number: resolve #1354
Changed:
1. FastPthreadMutex支持contention profiler。
2. 暴露FastPthreadMutex给用户使用。
Side effects:
---

Support FastPthreadMutex contention profiler && expose FastPthreadMutex to user

---

src/brpc/details/http_message.cpp
test/brpc_http_message_unittest.cpp

Issue Number:
[RFC 2616](https://datatracker.ietf.org/doc/html/rfc2616#section-14.23)规定：HTTP服务端要拒绝没有host的HTTP请求，并响应400 bad request。
Changed:
Side effects:
---

Reject http request without host

---

src/brpc/server_node.h

Issue Number: resolve #850 
Changed:
支持设置更多meta信息（地区信息、灰度信息等），满足多样路由规则的需求。
Side effects:
---

Support more meta for ServerNode

---

src/brpc/nshead_service.h
src/brpc/server.cpp
src/brpc/server.h
src/brpc/thrift_service.h

Issue Number:
Changed:
Side effects:
---

Fix max concurrency of thrift protocol and nshead protocol

---

src/butil/thread_key.cpp
src/butil/thread_key.h
src/butil/type_traits.h
test/endpoint_unittest.cpp
test/thread_key_unittest.cpp

Issue Number:
Changed:
Side effects:
---

Support thread local object iteration

---

src/bvar/multi_dimension_inl.h

当 mbvar 的 label 为空时，mbvar latency 的 tag 会多一个逗号，导致 prometheus 无法识别这样的上报。
旧的错误格式如下：
rpc_rough_rank_latency{,quantile="99"}
修复后的格式如下：
rpc_rough_rank_latency{quantile="99"}
Issue Number:
Changed:
Side effects:
---

fixbug: there is a ',' before 'quantile=' when labels is empty

---

src/brpc/rtmp.cpp
src/brpc/selective_channel.cpp
src/brpc/socket.cpp
src/brpc/socket.h
src/brpc/socket_inl.h
src/brpc/socket_map.cpp
src/brpc/versioned_ref_with_id.h
test/brpc_socket_unittest.cpp
test/brpc_ssl_unittest.cpp

Issue Number:
目前直接使用client Socket，存在两个问题：
1. 不能先连接对端，只能在第一次写入的时候连接。
2. 虽然可以先通过tcp connect获取一个fd，再通过SocketOptions.fd创建一个Socket对象。但是这种方式不支持ssl。
Changed:
支持在Socket::Create中连接对端，同时支持ssl。
Side effects:
---

Support connect on socket create

---

src/brpc/policy/http_rpc_protocol.cpp

Issue Number:
**h2 rpc_dump时 内存泄漏**。
具体是http和h2都走ProcessHttpRequest方法，在处理rpc_dump时，先AskToBeSampled创建堆对象再判is_http2，若是http2无释放堆对象逻辑。
发压cmd：rpc_press -protocol=h2 xxxx
Changed:
h2 req不做AskToBeSampled
修复前：
[brpc_h2_rpc_dump_mem_leak_bug.pdf](https://github.com/user-attachments/files/15798428/brpc_h2_rpc_dump_mem_leak_bug.pdf)
修复后：
[brpc_h2_rpc_dump_mem_leak_fixed.pdf](https://github.com/user-attachments/files/15798432/brpc_h2_rpc_dump_mem_leak_fixed.pdf)
Side effects:
无
--- …

fix h2 rpc_dump memory leak bug

---

src/brpc/socket.cpp

`_fd` should be reset if `ResetFileDescriptor` is going to return -1, otherwise the fd will be closed in callers like `CheckConnectedAndKeepWrite` or `Server::StartInernal` and socket lifecycle methods like `BeforeRecycled` or `WaitAndReset`.
Changed:
Side effects:
No
No
---

socket: fix potential double close

---

docs/cn/rpcz.md
src/brpc/span.cpp

rpcz目录在正常运行过程会周期性的删除旧的数据，但是如果在程序运行一段时间crash掉或者被kill掉，原来的rpcz目录不会释放掉，日积月累会占用很多空间。
这个PR会在rpcz启动的时候并且rpcz_keep_span_db为false的情况下，清理旧的数据。
Issue Number:
Changed:
Side effects:
---

remove old rpcz directory even if program crash

---

src/brpc/input_messenger.cpp

Issue Number: https://github.com/apache/brpc/issues/2677
Problem Summary: under `baidu_std`, server can not parse message when normal PRC and stream RPC arrive simultaneously 
Changed: switch between `baidu_std` and `stream_rpc` in `InputMessenger::CutInputMessage`
Side effects:
- Performance effects(性能影响): Little or none
- Breaking backward compatibility(向后兼容性): no
---

fix bug: switch between stream_rpc and baidu_std

---

src/brpc/details/health_check.cpp

Issue Number:
有用户反馈Socket被熔断后无法恢复，需要加上日志确定健康检查失败的原因。
Changed:
Side effects:
---

Add debug log for Socket health check

---

src/brpc/socket.cpp
test/brpc_socket_unittest.cpp

Issue Number:
Changed:
Side effects:
---

Fix uninitialized local side of Socket

---

src/bthread/key.cpp
src/bthread/types.h
test/bthread_key_unittest.cpp

Issue Number:
#2635
当brpc server 下处理的应用执行时间较短(bthread生命周期短)，且使用了bthread_local变量时，由于keytable 由bthread_keytable_pool_t中的一个全局链表维护，borrow_keytable、return_keytable时内部加互斥锁，导致锁成为瓶颈。
基于此，重新设计了bthread_keytable_pool_t：
新的bthread_keytable_pool_t结构体中，使用butil::ThreadLocal<bthread::KeyTableList>* list 保存TLS的KeyTable list。同时保留原有的free_keytables，不改变reserved_thread_local_data的语义，调用bthread_keytable_pool_reserve会在全局链表中预分配keytable.原有的互斥锁改为读写锁。
* borrow_keytable时优先从本地TLS链表中查找是否有可用的KeyTable，如果没有，且free_keytables不为NULL，再去从全局链表中加写锁获取keytable；如果都没有可用table，则返回NULL。
* return_keytable时只会将keytable插入TLS的KeyTable list中，由于是TLS变量，只有当bthread_keytable_pool_destroy才会产生竞争，所以只需要加写锁。
* bthread_keytable_pool_destroy时加写锁，首先delete butil::ThreadLocal<bthread::KeyTableList>* list，pool->destroyed = …

Use butil::ThreadLocal to store keytable

---

src/butil/bit_array.h
src/butil/containers/flat_map.h
src/butil/containers/flat_map_inl.h
test/flat_map_unittest.cpp

Issue Number:
1. Multi模式下，插入数据发生hash冲突的时候，size没有加一。另一方面，插入数据不能自动扩容。
2. m1 = m2，m1扩容后m1._nbucket不等于m2._nbucket的时候，m1的_buckets上除了插入数据的位置，其他位置没有set_invalid，后续使用会出现内存问题。
3. 扩容时，_buckets和_thumbnail都是先释放再申请新的内存。如果申请失败了，FlatMap就完全不可用了。
Changed:
1. size++。另外，当FlatMap负载超过阈值，则遍历Bucket链表，当存在不同的key的时候，则扩容。否则，不扩容直接插入。因为key一样，扩容后这些数据还是在同一个链表上。
2. 扩容后都要初始化_buckets和_thumbnail数组。
3. 申请内存成功后，再将其复制给_buckets和_thumbnail。一旦出现错误，则先释放已经申请的内存再返回失败。
Side effects:
---

Fix multi FlatMap scale and size

---

src/bthread/mutex.cpp
src/bthread/task_group.cpp
src/butil/debug/stack_trace.h
src/butil/debug/stack_trace_posix.cc
src/butil/memory/scope_guard.h
test/stack_trace_unittest.cc

Issue Number:
线程锁临界区内挂起协程（bthread_mutex、sync rpc、bthread_usleep、bthread_yeild等），属于未定义行为（大概率会造成死锁）。目前缺少一种发现机制，只能等到出现死锁后查看调用栈再排查。
Changed:
brpc已经hook了pthread mutex接口，加锁的时候将线程局部变量加一，解锁的时候，将线程局部变量减一。只有在线程局部变量等于0的时候，挂起协程才是安全的，否则，将调用栈打印出来用于排查问题。该调用栈只打印一次，因为一旦出现pthread mutex临界区内挂起协程，线程局部变量已经是错乱的，后续的调用栈已经没有参考价值。
Side effects:
---

Support pthread mutex deadlock detection

---

src/brpc/builtin/hotspots_service.cpp
src/brpc/builtin/pprof_service.cpp
src/brpc/policy/rtmp_protocol.cpp
src/brpc/socket.cpp
src/bthread/mutex.cpp
src/butil/debug/stack_trace.cc
src/butil/debug/stack_trace.h
src/butil/debug/stack_trace_posix.cc
src/butil/iobuf_profiler.cpp
src/butil/object_pool.h
src/butil/object_pool_inl.h
src/butil/third_party/dynamic_annotations/dynamic_annotations.c
src/butil/third_party/symbolize/symbolize.cc
src/butil/third_party/symbolize/symbolize.h
test/stack_trace_unittest.cc

Issue Number: resolve #859 
Changed:
目前contention profiler在最后submit的时候，有两种情况会申请内存：
1. 第一次submit时创建单例：ObjectPool、AgentCombiner::Agent；
2. ObjectPool::LocalPool::FreeChunk为空。
对于这两种情况，查找调用栈，发现存在malloc的符号，则不提交这次采样结果。
Side effects:
---

Fix malloc deadlock caused by contention profiler

---

.github/actions/install-all-dependences/action.yml
.github/workflows/ci-linux.yml
src/brpc/rdma/rdma_endpoint.cpp
src/brpc/socket.cpp
test/run_tests.sh

Issue Number: resolve #2706
Changed:
修复#2560 导致rmda编译错误的问题。
Side effects:
---

Fix rdma complie error

---

CMakeLists.txt

Issue Number: #2714 
On macos, originally it was mandatory to set `OPENSSL_ROOT_DIR` to` /usr/local/opt-openssl`, but now a judgment is added, only if `OPENSSL_ROOT_DIR` is not set. Is set to `/usr/local/opt-openssl`
Changed:
Added a judgment to the cmake file
Side effects:
- Performance effects(性能影响): NO
- Breaking backward compatibility(向后兼容性): YES
---

add openSSL_ROOT_DIR check on macos

---

src/brpc/server.cpp
src/brpc/server.h

Issue Number:
Changed:
Side effects:
---

Fix baidu master service leak

---

src/bthread/fd.cpp
src/butil/endpoint.cpp
src/butil/fd_utility.cpp
src/butil/fd_utility.h
test/bthread_fd_unittest.cpp
test/endpoint_unittest.cpp
test/run_tests.sh

Issue Number:
tcp_connect被中断之后，返回结果是有问题的：
1. `bthread_timed_connect / bthread_connect`：`butex_wait`返回0，errno等于`EWOULDBLOCK`或者`EINTR`，最后tcp_connect返回一个未连接成功的socket fd。
2. `pthread_timed_connect `：返回-1，errno等于`EINTR`。
Changed:
当errno等于`EWOULDBLOCK`或者`EINTR`，`pthread_fd_wait / bthread_fd_wait`继续wait到连接成功或者失败。
Side effects:
---

Fix tcp connect interrupt

---

tools/wireshark_baidu_std.lua

…otocol
Issue Number: resolve #2408
原本 tools/wireshark_baidu_std.lua 的实现存在两个问题：
1. 由于原本传入的解析长度是body_size - meta_size，这会导致解析时不止解析了BRPC Message，还会把Attachment也一同解析，出现一些令人困惑的解析结果；
2. 原本的实现方式只支持解析包含单个RPC请求/响应的报文，但实际同一报文中是可能包含多个RPC请求/响应的。
Changed:
修复 #2408 引入的wireshark dissector无法解析包含多个baidu_std protocol请求的报文的问题。
Side effects:
- Performance effects(性能影响):无
- Breaking backward compatibility(向后兼容性): yes
---

Support multiple RPCs parsing in wireshark dissector for baidu_std protocol

---

src/butil/containers/mpsc_queue.h
test/mpsc_queue_unittest.cc

Without specifying the type of the pointer, the memory will return to the pool holding all `void' pointers.
Issue Number: #2724 
Problem Summary: see issue #2724 
Changed:
Side effects:
---

[MPSQ] fix a memleak in butil::ObjectPoolAllocator

---

src/brpc/socket.cpp
test/endpoint_unittest.cpp

Issue Number: 
1. #2707 导致RdmaEndpoint回收资源的时候无法从移除对应的fd，导致后续相同值的fd无法再加入到epoll中。
2. 修复EndPointTest.interrupt一些问题：超时时间太小导致失败、信号处理函数中打日志会申请内存导致core。
Changed:
Side effects:
---

Fix rdma remove consumer error

---

src/brpc/serialized_response.h

Issue Number: resolve #2721
Changed:
Side effects:
---

Fix compilation errors of SerializedResponse

---

src/bthread/mutex.cpp
test/Makefile

Issue Number: resolve #2726 
#2692 未使用`__dl_sym`的原因是，UT无法运行，报错信息：`symbol lookup error: ./libbrpc.so: undefined symbol: pthread_mutex_trylock`。相关issue：#2266 #1086 。
报错原因总结：`libpthread.so`先于`libbrpc.dbg.so`加载，导致使用`__dl_sym RTLD_NEXT`在后续加载的动态库中找不到`pthread_mutex_trylock`符号。
解决方法有两个：
1. `libbrpc.dbg.so`先于`libpthread.so`加载。
2. 最终的可执行文件静态链接bRPC静态库。
具体分析：
[man文档](https://man7.org/linux/man-pages/man3/dlsym.3.html)提到`RTLD_NEXT`的作用：
> Find the next occurrence of the desired symbol in the search order after the current object.
在本场景下，大致意思是在从加载顺序在`libbrpc.dbg.so`之后的动态库中查找`pthread_mutex_*`符号。那么，`libbrpc.dbg.so`要先于`libpthread.so`加载，才能找到`pthread_mutex_*`系列符号。
在master分支下编译出brpc_channel_unittest程序用作调试。为了更好地展示，会对输出进行适当的处理（过滤、删减）。
通过`LD_DEBUG=libs`查看动态库加载顺序，发现`libpthread.so`先于`libbrpc.dbg.so` …

Fix pthread_mutex_trylock deadlock in jemalloc

---

example/rdma_performance/Makefile

Issue Number: #2740 
Changed:
Side effects:
---

[#2740] fix example/rdma_performance compilation error

---

docs/cn/server.md
src/brpc/policy/baidu_rpc_protocol.cpp
src/brpc/rpc_pb_message_factory.cpp
src/brpc/rpc_pb_message_factory.h
src/brpc/server.cpp
src/brpc/server.h
test/brpc_channel_unittest.cpp
test/brpc_server_unittest.cpp

Issue Number: resolve #2671
Changed:
Side effects:
---

Support rpc protobuf message factory interface

---

src/bthread/bthread.cpp
test/bthread_setconcurrency_unittest.cpp

Issue Number:
https://github.com/apache/brpc/issues/2542
升级到1.10.0版本后，重复解析两次 gflags 后，flags bthread_concurrency_by_tag validate会报错的问题又复现了。
是由于在默认配置下，第二次解析gflags时，num = 0，tag_ngroup = FALGS_bthread_concurrency。两者不想等导致返回了EPERM。
gflags的默认配置下，只有一个tag且等于0，bthread_concurrency_by_tag的默认值应该设置成等于bthread_concurrency的默认值，这样也比较合理。
Changed:
Side effects:
---

fix gflags bthread_concurrency_by_tag validate error

---

src/bthread/butex.cpp
src/bthread/butex.h
src/bthread/mutex.cpp
src/bthread/task_group.h
src/butil/containers/linked_list.h
src/butil/thread_local.h

Issue Number:
golang mutex的演进中有两点优化：
1. fast path没抢到锁的竞争者，进入slow path之后，立即再抢一次锁，不成功就阻塞在butex中，等下次唤醒在抢锁。进入slow path之后的第一次抢锁大概率是会失败的。[[1]](https://github.com/golang/go/commit/edcad8639a902741dc49f77d000ed62b0cc6956f)
2. 被唤醒的队头竞争者跟新竞争者抢锁，大概率也是会失败。因为新竞争者占用着cpu且数量很多。如果将队头的竞争者放到队尾，显然不公平，甚至可能出现饥饿问题。[[2]](https://github.com/golang/go/commit/0556e26273f704db73df9e7c4c3d2e8434dec7be)
Changed:
1. 进入slow path之后，如果worker线程本地调度队列为空，尝试自旋4次再抢锁，这对于临界区小的场景是有意义的。
2. 被唤醒的队头竞争者抢锁失败后，会被重新放回队头。
Side effects:
--- …

Active Spinning and queue old bthread at the head for bthread mutex

---

src/brpc/periodic_task.h

Issue Number:
Changed:
Make periodic_task.h a self-contained header file, If others include periodic_task.h, they must include ctime header.
Side effects:
- Breaking backward compatibility(向后兼容性): Yes
---

Make periodic_task.h a self-contained header file

---

src/butil/thread_local.h

Issue Number:
Changed:
Side effects:
---

Fix missing extern of tls_task_group

---

docs/cn/server.md
docs/en/server.md
src/brpc/policy/http_rpc_protocol.cpp
src/brpc/rpc_pb_message_factory.cpp
src/brpc/rpc_pb_message_factory.h
test/brpc_server_unittest.cpp
test/v3.proto

Issue Number: resolve #535
Changed:
1. 目前bRPC已经不支持pb 2.x，没有了兼容性方面的顾虑，所以在#2718 的基础上支持pb3 arena机制即可。
2. HTTP协议支持RpcPBMessageFactory。
Side effects:
---

Support arena rpc pb message factory

---

src/bthread/types.h

Issue Number: 
使用bthread_mutex、bthread_cond_t时，一旦不小心发现了拷贝，就会出现未定义行为。
Changed:
在C++环境中，禁止bthread_mutex、bthread_cond_t拷贝。
Side effects:
---

Support noncopyable sync objects

---

src/butil/compiler_specific.h
src/butil/containers/flat_map.h
src/butil/containers/mpsc_queue.h
src/butil/memory/aligned_memory.h
src/butil/memory/manual_constructor.h
src/butil/object_pool_inl.h
src/butil/resource_pool_inl.h

Issue Number: #2288 中引入用于对齐`Element`地址的`std::aligned_storage`在C++23中已经被废弃了。详细背景见[P1413R3](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p1413r3.pdf)提案。
Changed:
~~C++17起，使用[P1413R3](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p1413r3.pdf)提案中建议的`alignas(T) std::byte element_spaces[sizeof(T)]`来代替`std::aligned_storage`。~~
1. `butil::AlignedMemory`的实现跟[P1413R3](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p1413r3.pdf)提案中建议的`alignas(T) std::byte[sizeof(T)]`类似，优点是封装性更好，所以使用`butil::ManualConstructor`（包含`butil::AlignedMemory`）代替`std::aligned_storage`。
2. `MPSCQueueNode`、`ObjectPool`、`ResourcePool`也需要对齐。
3. 补充了一下`ALIGNAS`宏的一些注释（来自于chromium）。
Side effects:
---
- Please make sure …

Use butil::AlignedMemory instead of std::aligned_storage to align memory for placement new 

---

docs/cn/client.md
src/brpc/backup_request_policy.h
src/brpc/channel.cpp
src/brpc/channel.h
src/brpc/controller.cpp
src/brpc/controller.h
test/brpc_channel_unittest.cpp

Issue Number: resolve #2668 , resolve #2695
Changed:
Side effects:
---

Support backup request policy

---

src/brpc/authenticator.h
src/brpc/policy/baidu_rpc_protocol.cpp
src/brpc/policy/http_rpc_protocol.cpp
src/brpc/policy/http_rpc_protocol.h
src/brpc/policy/hulu_pbrpc_protocol.cpp
test/brpc_server_unittest.cpp

Issue Number:
当前server鉴权失败时，会直接关闭连接。client只有`EEOF`的错误，没法快速定位问题。
Changed:
在`Authenticator`增加一个接口，支持返回一个错误响应给client再关闭连接。
Side effects:
---

Send unauthorized response to client when authentication fails

---

src/bthread/bthread.h
src/bthread/butex.cpp
src/bthread/butex.h
src/bthread/mutex.cpp
src/bthread/mutex.h
src/bthread/rwlock.cpp
src/bthread/rwlock.h
src/bthread/semaphore.cpp
src/bthread/types.h
src/bvar/collector.h
test/BUILD.bazel
test/bthread_rwlock_unittest.cpp
test/bthread_semaphore_unittest.cpp

Issue Number:
Changed:
1. 按照[golang读写锁](https://github.com/golang/go/blob/master/src/sync/rwmutex.go)原理，在bRPC实现了对应的读写锁。
2. 支持bthread信号量，用于满足读写锁的实现需求，同时开放给用户使用。
3. contention profiler支持bthread信号量和读写锁。
Side effects:
---

Support semaphore and rwlock for bthread

---

src/bthread/types.h
test/BUILD.bazel

Issue Number:
Changed:
Side effects:
---

Make bthread semaphore and rwlock noncopyable

---

src/bthread/key.cpp
src/bthread/types.h
src/bthread/unstable.h
test/bthread_key_unittest.cpp

Issue Number: #2756
* 设置thread_local的keytable_list长度上限为KEY_TABLE_LIST_SIZE = 10000
* 超出KEY_TABLE_LIST_SIZE 后，返回KEY_TABLE_LIST_SIZE / 2 个 keytable给全局的free_keytables
* 当前thread的keytable_list为空但是free_keytables不为空时，一次性从free_keytables中取出至多BORROW_FROM_GLOBLE_SIZE = 100 个keytable给keytable_list
Changed:
Side effects:
---

Optimize keytablelist implementation

---

.github/workflows/ci-macos.yml
docs/cn/streaming_rpc.md
docs/en/streaming_rpc.md
example/streaming_batch_echo_c++/CMakeLists.txt
example/streaming_batch_echo_c++/client.cpp
example/streaming_batch_echo_c++/echo.proto
example/streaming_batch_echo_c++/server.cpp
src/brpc/channel.cpp
src/brpc/controller.cpp
src/brpc/controller.h
src/brpc/details/controller_private_accessor.h
src/brpc/policy/baidu_rpc_protocol.cpp
src/brpc/stream.cpp
src/brpc/stream.h
src/brpc/stream_impl.h

Issue Number: #2733 
Problem Summary: 支持一次RPC调用创建多个流
Side effects:
对批量创建stream场景有性能提升
协议改动兼容，支持平滑升级
---

Batch create and accept stream

---

src/brpc/policy/baidu_rpc_protocol.cpp
src/brpc/policy/http_rpc_protocol.cpp
src/brpc/policy/hulu_pbrpc_protocol.cpp
src/brpc/policy/nshead_protocol.cpp
src/brpc/policy/sofa_pbrpc_protocol.cpp
src/brpc/policy/thrift_protocol.cpp
src/brpc/server.cpp
src/brpc/server.h

Issue Number:
Problem Summary: Sometimes we need to disable check eovercrowded for some methods
Changed: add a method/service level option to disable check eovercrowded on server side
Side effects:
- Performance effects(性能影响): zero/or little
- Breaking backward compatibility(向后兼容性): no breaking
---

[feat][WIP] add a method option to disable check eovercrowded on server side

---

src/bthread/butex.cpp

Issue Number: #2777 
Changed:
Side effects:
---

Only support batch butex wake with the same tag

---

src/bthread/bthread.cpp

add check for bthread_setconcurrency_by_tag, make sure bRPC workers number in one group between BTHREAD_MIN_CONCURRENCY and BTHREAD_MAX_CONCURRENCY
Issue Number:
Changed:
Side effects:
---

add check for bthread_setconcurrency_by_tag

---

.bazelrc
MODULE.bazel

Issue Number:
boost has already officially published to bcr. switch to use that
Changed:
Side effects:
---

switch boost dependency in bzlmod to bcr

---

src/brpc/rpc_pb_message_factory.h

Issue Number:
Changed:
Side effects:
---

Fix memory leak of ArenaRpcPBMessageFactory

---

src/brpc/grpc.cpp

It doesn't compile with GCC 13.
Changed:
Adding missing `#include <cstdint>` for `int64_t` usage.
Side effects:
---

Add missing #include <cstdint>

---

docs/cn/bthread_tagged_task_group.md
example/bthread_tag_echo_c++/server.cpp
src/brpc/server.cpp
src/bthread/bthread.cpp
test/bthread_setconcurrency_unittest.cpp

Issue Number:
Problem Summary:  设置 tag 对应的 worker 需要考虑 bthread_concurrency 和 bthread_min_concurrency，而且如果超过 bthread_concurrency 而又没有使用 bthread_min_concurrency 就无法正常设置 tag 对应的 worker 值，因为修改 bthread_concurrency 的值会直接平均分配给每一个 tag。
Changed: 修改了增加 tag 对应 worker 的逻辑。
Side effects:
---

set tags workers unlimitedly

---

src/bvar/multi_dimension.h
src/bvar/multi_dimension_inl.h
test/Makefile

Issue Number: resolve #2788
Changed:
Side effects:
---

Support set_max_stats_count of MultiDimension

---

src/bthread/mutex.cpp
src/butil/logging.cc
src/butil/logging.h
src/bvar/detail/percentile.h
test/logging_unittest.cc

Issue Number:
有一些场景下，需要打印调用栈，但是crash_on_fatal_log=true时，CHECK会crash。
Changed:
支持打印调用栈，且不会crash。
Side effects:
---

Support backtrace log

---

MODULE.bazel

After using offical boost 1.83.0[1], rules_cc@0.0.13 are required, which, in turn, requires Protobuf v27.0.
Protobuf v27.0 is not compatible with GCC less than 13[2].
[1] https://github.com/apache/brpc/pull/2789
[2] https://github.com/protocolbuffers/protobuf/issues/16868
Issue Number: #2822
Changed:
Side effects:
---

Upgrade Protobuf to v27.3 for building with bzlmod

---

docs/cn/getting_started.md

In the previous instructions, the operation of switching to the build directory was omitted.

Fix build instructions in getting_started.md

---

docs/cn/server.md
docs/en/server.md
src/brpc/baidu_master_service.cpp
src/brpc/baidu_master_service.h
src/brpc/policy/baidu_rpc_protocol.cpp
src/brpc/policy/http_rpc_protocol.cpp
src/brpc/policy/hulu_pbrpc_protocol.cpp
src/brpc/policy/sofa_pbrpc_protocol.cpp
src/brpc/server.cpp
src/brpc/server.h

Issue Number:
Changed: add a method-level option(only valid for baidu_rpc, http_rpc, hulu_pbrpc and sofa_pbrpc protocols) to enable ignore eovercrowded errors for some methods.
Side effects:
- Performance effects(性能影响): no or little
---

method level option to ignore server eovercrowded

---

src/bthread/key.cpp

之前实现的 move_first_n_to_target 有问题，如果target是一串链表的话会导致全局维护的free_keytables链表中除了头节点的剩余keytables丢失，造成内存泄漏。
单测负载不高没测出来，修复后在我们自己的场景中进行了测试，keytable的数量不会出现持续升高的情况。
Issue Number:
Changed:
Side effects:
---

keytablelist bugfix

---

src/bvar/mvariable.cpp

Issue Number:
**Mixing tabs and spaces causes confusions.**
Changed:
Side effects:
---

fix: use space instead of tab

---

src/bthread/mutex.cpp

Issue Number:
Changed:
Side effects:
---

Fix unused private field warning of FastPthreadMutex

---

src/butil/containers/optional.h

Issue Number:
build fails when building with -std=c++17 on
Changed:
Side effects:
---

Fix build failure with -std=c++17 option

---

src/bthread/bthread.cpp
src/bthread/bthread.h
src/bthread/task_group.cpp
src/bthread/task_group.h
src/bthread/task_meta.h
src/butil/time.h

Issue Number: #2833 
Changed:
通过添加一个新的 ` bthread_cpu_clock_ns` 函数来获取当前bthread运行的时间，这个函数受 `bthread_enable_cpu_clock_stat` flag控制，默认不开启，需要获取运行时间的时候打开这个flag，用户在自己代码里面通过调用 `bthread_cpu_clock_ns`拿到运行时间采集到指标里面。
Side effects:
- Performance effects(性能影响): 打开开关后稍微影响bthrad调度的性能，一次调度增加 ~200ns的开销。
- Breaking backward compatibility(向后兼容性):  无
---

add support for bthread cpu usage

---

src/butil/object_pool.h
src/butil/object_pool_inl.h
src/butil/resource_pool.h
src/butil/resource_pool_inl.h

Issue Number:
Changed:
Side effects:
---

Support variable arguments for ResourcePool and ObjectPool

---

src/brpc/versioned_ref_with_id.h
src/butil/object_pool.h
src/butil/object_pool_inl.h
src/butil/resource_pool.h
src/butil/resource_pool_inl.h

Issue Number:
Changed:
修复缺少universal reference的问题。
Side effects:
---

Fix universal reference

---

src/brpc/server.cpp
src/butil/compiler_specific.h
src/butil/debug/leak_annotations.h
src/butil/lazy_instance.h
src/butil/memory/singleton.h

Issue Number: resolve #2164, resolve #1390, resolve #2470
Changed:
让LSan忽略Server和Singleton一些设计上预期内的内存泄漏。
Side effects:
---

Instruct LeakSanitizer to ignore designated memory leaks of Server and Singleton

---

docs/cn/combo_channel.md
docs/en/combo_channel.md
src/brpc/parallel_channel.cpp
src/brpc/parallel_channel.h
test/brpc_channel_unittest.cpp

Issue Number:
Changed:
支持设置阈值，使rpc成功数达到阈值时，Parallel RPC成功。
Side effects:
---

Support success limit of ParallelChannel

---

src/brpc/input_messenger.cpp
src/brpc/socket.cpp
src/brpc/socket.h
src/brpc/socket_inl.h
src/brpc/versioned_ref_with_id.h
test/brpc_socket_unittest.cpp

Issue Number: resolve #1154
Changed:
支持TCP_USER_TIMEOUT：https://github.com/grpc/proposal/blob/master/A18-tcp-user-timeout.md
Side effects:
---

Support tcp user timeout of client

---

.github/workflows/ci-linux.yml
config_brpc.sh
src/brpc/memcache.h
src/brpc/policy/http2_rpc_protocol.cpp
src/brpc/policy/http_rpc_protocol.cpp
src/brpc/rdma/block_pool.cpp
src/brpc/rdma/rdma_endpoint.cpp
src/brpc/rdma/rdma_helper.cpp
src/brpc/thrift_message.h
src/bthread/task_group.cpp
src/butil/logging.h

Issue Number:
Changed:
1. 修复编译警告。
2. make编译ci打开werror，及时发现和修复编译警告。
Side effects:
---

Fix some compilation warning issues

---

BUILD.bazel

Issue Number:
在最新的 protobuf 版本里，protoc_lib 包含 main 函数，而 `//:brpc`  --> `//:mcpack2pb` --> `@com_google_protobuf//:protoc_lib`，导致所有依赖 brpc 的 gtest 且没有显式写 main 函数的测试，实际上运行的是 protoc 的程序。比如issue https://github.com/protocolbuffers/protobuf/issues/12887
这个 PR 尝试解决这个问题，将 `//:mcpack2pb` 的依赖最小化。
Changed:
Side effects:
NO
- Breaking backward compatibility(向后兼容性):  NO compatibility issue.
---

Chore: minimize dependence to avoid depends on protoc_lib

---

src/brpc/server.cpp
test/brpc_channel_unittest.cpp
test/brpc_http_rpc_protocol_unittest.cpp

Issue Number: #2871
Changed:
Side effects:
---

fix memory leak issue #2871

---

docs/cn/streaming_rpc.md
docs/en/streaming_rpc.md
src/brpc/stream.cpp
test/brpc_streaming_rpc_unittest.cpp

https://github.com/apache/incubator-brpc/blob/master/docs/cn/streaming_rpc.md
"目前的实现还没有自动切割过大的消息，同一个tcp连接上的多个Stream之间可能有[Head-of-line blocking](https://en.wikipedia.org/wiki/Head-of-line_blocking)问题，请尽量避免过大的单个消息，实现自动切割后我们会告知并更新文档"
尝试解决这个 TODO。
之前#1947 这个MR存在一点问题（见 讨论和comment）一直没有合入。最近内部有很多业务有需求，我重新实现了下。

Support segment large brpc stream messages automatically

---

src/brpc/socket.cpp
src/brpc/versioned_ref_with_id.h

Issue Number:
Changed:
Side effects:
---

Fix description of VersionedRefWithId

---

src/bvar/multi_dimension.h
src/bvar/multi_dimension_inl.h
src/bvar/mvariable.cpp

Add a new gflag to set max stats count of a multi dimension.
Changed: add new gflag max_multi_dimension_stats_count
Side effects:
no
no

add gflag max_multi_dimension_stats_count

---

.github/workflows/ci-linux.yml
BUILD.bazel
MODULE.bazel
src/bthread/task_tracer.h
test/bthread_fd_unittest.cpp
test/endpoint_unittest.cpp

Issue Number:
Changed:
1. #2851 支持bazel编译。
2. 修复UT在github ci上因网络原因失败的问题。
Side effects:
---

Support bthread tracer with bazel

---

.github/actions/init-ut-make-config/action.yml
.github/actions/install-all-dependences/action.yml
.github/actions/install-essential-dependences/action.yml
.github/workflows/ci-linux.yml
Makefile
src/json2pb/json_to_pb.cpp
test/bthread_fd_unittest.cpp
test/bthread_semaphore_unittest.cpp
test/bthread_unittest.cpp
test/endpoint_unittest.cpp
test/stack_trace_unittest.cc

Issue Number:
Ubuntu 20.04 LTS runner will be removed on 2025-04-01. For more details, see https://github.com/actions/runner-images/issues/11101
Changed:
1. 更新linux ci镜像：ubuntu-20.04 -> ubuntu-22.04
2. ubuntu-22.04下更高版本（13-15）的clang会导致StackTraceTest失败，所以UT的ci继续使用clang-12编译。后续可以看看Chromium symbolize相关逻辑是否修复这个问题。
3. 修复一些编译警告问题。
4. 修复一些UT的问题。
Side effects:
---

Update ubuntu-20.04 to ubuntu-22.04 in CI

---

example/BUILD.bazel
example/redis_c++/redis_server.cpp
src/brpc/policy/redis_protocol.cpp
src/brpc/redis.cpp
src/brpc/redis.h
test/BUILD.bazel
test/brpc_redis_unittest.cpp

Issue Number: https://github.com/apache/brpc/issues/2901
Problem Summary:  RedisConnContext 添加auth信息支持多租户场景
Changed:
Side effects:
- Breaking backward compatibility(向后兼容性):  兼容
---

keep session info in RedisConnContext

---

src/bthread/parking_lot.h

Issue Number: https://github.com/apache/brpc/issues/1727
Problem Summary: high cpu usage because of futex in parking lot
Changed:
optimize parking lot 
Side effects:
minor improvement for most cases. significant for some cases. 
No
---

Reduce futex usage in ParkingLot

---

src/brpc/event_dispatcher.cpp
src/brpc/event_dispatcher_epoll.cpp
src/brpc/event_dispatcher_kqueue.cpp
test/bthread_unittest.cpp

Issue Number: #2819
Changed:
监控EventDispatcher事件处理延时。
Side effects:
---

Record latency of EventDispatcher

---

BUILD.bazel
src/brpc/builtin/prometheus_metrics_service.cpp
src/bvar/multi_dimension_inl.h
src/bvar/variable.h
test/BUILD.bazel
test/brpc_channel_unittest.cpp
test/brpc_prometheus_metrics_unittest.cpp
test/iobuf_unittest.cpp

Fix PrometheusMetricsDumper to dump unique comment of a certain metric name to follow the prometheus specification.
Also refine the prometheus ut case to support mvar output.
Issue Number:
#2825
Changed:
Side effects:
- Performance effects(性能影响): NO
---

Fix prometheus metric format (#2825)

---

src/brpc/event_dispatcher.cpp
src/bthread/parking_lot.h
src/butil/file_util_posix.cc

Issue Number:
#2907 合入后，CI经常超时，都是发生在`EventDispatcherTest.dispatch_tasks`和`KeyTest.creating_key_in_parallel`。
原因：`signal`早于`wait`，`signal`没改`_pending_signal`，导致后续的`wait`不会立即返回。
Changed:
无论有无waiter，`signal`都要改`_pending_signal`。
Side effects:
---

Fix ParkingLot::signal does not modify _pending_signal when there is no waiter

---

CMakeLists.txt

Issue Number: #2913
glog 依赖 gflags，静态链接的时候，glfags 必须在 glog 后面，否则可能会链接错误
Changed:
Side effects:
---

[#2913] fix link error if with glog

---

src/butil/containers/doubly_buffered_data.h
src/butil/type_traits.h
test/brpc_load_balancer_unittest.cpp

Issue Number:
DoublyBufferedData::Read要配合ScopedPtr使用，使用上需要理解成本，甚至有可能会用错，导致死锁等问题。
Changed:
1. 增加一个DoublyBufferedData::Read重载函数，用户只需要传入自定义函数，操作T就可以了。
2. 支持可变参数。
Side effects:
---

Support a more safe read function and variadic functions of DoublyBufferedData

---

src/brpc/details/method_status.cpp
src/brpc/details/method_status.h
src/brpc/policy/baidu_rpc_protocol.cpp
src/brpc/policy/http_rpc_protocol.cpp
src/brpc/policy/hulu_pbrpc_protocol.cpp
src/brpc/policy/mongo_protocol.cpp
src/brpc/policy/nshead_protocol.cpp
src/brpc/policy/sofa_pbrpc_protocol.cpp
src/brpc/policy/streaming_rpc_protocol.cpp
src/brpc/policy/streaming_rpc_protocol.h

Issue Number: resolve #2437
Changed:
1. 确保耗时不包括用户回调的时间。
2. 耗时包括异步写的response的时间。
Side effects:
---

Optimize server latency

---

src/brpc/details/http_message.cpp
src/brpc/details/http_message.h
test/brpc_http_message_unittest.cpp

Issue Number:
Changed:
http body不需要拷贝数据，与收包IOBuf共享数据即可——zero copy。
Side effects:
---

Optimize zero copy of http body

---

src/brpc/policy/baidu_rpc_protocol.cpp
test/brpc_socket_unittest.cpp

Issue Number:
SendRpcResponse中会统一归还messages，不需要在ProcessRpcRequest中提前归还。
Changed:
Side effects:
---

Fix double free messages in baidu-std

---

src/brpc/socket.cpp
test/brpc_builtin_service_unittest.cpp
test/brpc_redis_unittest.cpp
test/brpc_socket_unittest.cpp
test/brpc_streaming_rpc_unittest.cpp
test/bthread_fd_unittest.cpp
test/bthread_unittest.cpp
test/endpoint_unittest.cpp

Issue Number:
Changed:
Side effects:
---

Fix some unstable UTs

---

src/brpc/extension.h
src/brpc/policy/http_rpc_protocol.cpp
src/brpc/policy/http_rpc_protocol.h
src/bthread/key.cpp
src/butil/logging.cc
src/butil/memory/singleton_on_pthread_once.h
src/json2pb/json_to_pb.cpp
src/json2pb/json_to_pb.h
src/json2pb/pb_to_json.cpp
src/json2pb/pb_to_json.h
src/json2pb/protobuf_type_resolver.cpp
src/json2pb/protobuf_type_resolver.h
test/addressbook_map.proto
test/brpc_builtin_service_unittest.cpp
test/brpc_http_rpc_protocol_unittest.cpp
test/brpc_protobuf_json_unittest.cpp
test/bthread_rwlock_unittest.cpp

Issue Number:
bRPC内部的json2pb要求map json的格式是`[{"key": ..., "value": ...}, {...}]`，跟习惯用法`{"key": value}`不一样，不利于多语言接入。
Changed:
使用Protobuf提供的json2pb能力， 支持Protobuf的ProtoJson格式http body，方便多语言接入。
Side effects:
---

Support ProtoJson formatted http body

---

src/brpc/adaptive_max_concurrency.cpp
src/brpc/adaptive_max_concurrency.h
src/brpc/concurrency_limiter.h
src/brpc/policy/auto_concurrency_limiter.cpp
src/brpc/policy/auto_concurrency_limiter.h
src/brpc/policy/constant_concurrency_limiter.cpp
src/brpc/policy/constant_concurrency_limiter.h
src/brpc/policy/timeout_concurrency_limiter.cpp
src/brpc/policy/timeout_concurrency_limiter.h
src/brpc/server.cpp

Issue Number: #2873
目前只实现了ConstantConcurrencyLimiter的动态修改。
Changed:
Side effects:
---

support dynamic update method concurrency

---

.github/actions/init-ut-make-config/action.yml
.github/workflows/ci-linux.yml
docs/cn/sanitizers.md
src/bthread/stack_inl.h
src/bthread/task_group.cpp
test/brpc_load_balancer_unittest.cpp
test/bthread_cond_unittest.cpp
test/run_tests.sh
test/security_unittest.cc

Issue Number:
#2890 调__sanitizer_start_switch_fiber时，应该传将要被调度的bthread stack信息，而不是将要挂起的bthread stack信息。
Changed:
Side effects:
---

Fix asan switch fiber with error stack info

---

docs/cn/heap_profiler.md
src/brpc/details/jemalloc_profiler.cpp

Issue Number:
1. 重置采样率还会继续采样，不应设置FLAGS_je_prof_active=false。
2. 想看到内存对象数，而不只是大小。
Changed:
1. 修改FLAGS_je_prof_reset时，去掉修改FLAGS_je_prof_active逻辑。
2. 增加extra_options参数，支持查看内存对象数。
Side effects:
无
---

jemalloc profiler support objects

---

src/bthread/task_group.cpp
src/butil/thread_local.h

What problem does this PR solve?
解决bthread_setspecific注册的变量，用bthread_getspecific可能会找不到的问题。
根据 https://github.com/apache/brpc/issues/1776 , https://github.com/apache/brpc/pull/2156 里的一些相关描述，我尝试将清理tls这段代码抽出来作为单独函数并声明为noinline，在我自己的场景下测试可以修复这个问题
Changed:
Side effects:
---

use BAIDU_VOLATILE_THREAD_LOCAL to declare tls_bls to avoid error compiler optimization

---

src/brpc/selective_channel.cpp

Fixed the issue that when using SelectiveChannel, the header could not be transparently transmitted to the subchannel.
Issue Number:
Changed:
Side effects:
---

add headers to sub cntl.

---

src/brpc/adaptive_max_concurrency.cpp
src/brpc/adaptive_max_concurrency.h
src/brpc/policy/constant_concurrency_limiter.cpp
src/brpc/server.cpp
src/brpc/server.h
test/brpc_adaptive_class_unittest.cpp

Issue Number:
n/A
A nit fix using const instead of static new, I am not C++ expert, but it seems we just have `static std::string*` with a fix value in previous implications of this PR. I suppose:
- static string with a fix value equals with const, as 1st commit.
- After 1st commit of this PR, I notice that if a function just returns a const string, in fact, we can use a const string replace.
as I am not C++ expert, I used another 3 commits to fix the compile issue.
Changed:
Side effects:
I suppose those implements either previous impl for this PR or changes in this PR moves to compiler optimization.
I searched and learned through www,  I suppose there only difference between the memory location for static(previous) and const(this PR), but …

Nit enhance 25 03 05

---

src/butil/iobuf.cpp
src/butil/iobuf.h
test/iobuf_unittest.cpp

IOBuf通过reserve_aligned(size_t n, size_t alignment)函数在IOBuf内部预分配一些符合对齐规则的内存，后续可以通过unsafe_assign函数或者IOBufAsZeroCopyInputStream等函数把这些内存段解析出来，让用户填充数据。
这样做的好处是，统一使用IOBuf的内存管理机制，典型的如RDMA这种内存需要注册的场景，用户自己去注册会比较麻烦，RDMA已经提供给IOBuf内存分配器，直接使用非常方便。
Issue Number:
#993
Changed:
Side effects:
---

iobuf support reserve_aligned

---

src/brpc/policy/http_rpc_protocol.cpp

Issue Number: resolve #2947
Changed:
Side effects:
---

Fix HttpResponseSenderAsDone Run with NULL messages

---

src/brpc/restful.cpp

Issue Number:
Changed: Use standard library functions to optimize comparison operators, cache path objects, reduce the number of pointer indirect addressing operations, and streamline code.
Side effects:
- Performance effects: no
- Breaking backward compatibility: no
---

use standard alg to optimze comparator

---

src/brpc/load_balancer.h
src/brpc/policy/dynpart_load_balancer.h
src/brpc/policy/locality_aware_load_balancer.h
src/brpc/policy/randomized_load_balancer.cpp
src/brpc/policy/randomized_load_balancer.h
src/brpc/policy/round_robin_load_balancer.cpp
src/brpc/policy/round_robin_load_balancer.h
src/brpc/policy/weighted_randomized_load_balancer.cpp
src/brpc/policy/weighted_randomized_load_balancer.h
src/brpc/policy/weighted_round_robin_load_balancer.cpp
src/brpc/policy/weighted_round_robin_load_balancer.h
test/bthread_countdown_event_unittest.cpp

Issue Number:
In n tries, some servers with small weights may not be selected.
Changed:
Side effects:
---

Make sure WeightedRandomizedLoadBalancer can traverse the whole server list

---

docs/cn/client.md
src/brpc/channel.cpp
src/brpc/channel.h
src/brpc/details/health_check.cpp
src/brpc/details/naming_service_thread.cpp
src/brpc/details/naming_service_thread.h
src/brpc/health_check_option.h
src/brpc/socket.cpp
src/brpc/socket.h
src/brpc/socket_map.cpp
src/brpc/socket_map.h
test/brpc_load_balancer_unittest.cpp

**Current Application-Layer Health Check Mechanism**
The current application-layer health check mechanism is configured via the -health_check_path flag. If this flag is left empty, the health check is disabled. However, since gflag is a global variable, once set, it enables the application-layer health check for all downstream services accessed by the service.
For complex services that may interact with dozens or even hundreds of downstream services (some of which might not be brpc-based and could instead be Go/Java services), not all downstream services necessarily support health check requests. Even for those that do, the health check request paths (URLs) may vary across services. Therefore, it is necessary to support channel-level configuration for application-layer health check …

Support channel level application health check options

---

BUILD.bazel
bazel/config/BUILD.bazel
docs/cn/getting_started.md
docs/en/getting_started.md

Fix libunwind linked by default on x86_64 cpu when building via bazel.
Issue Number:
libunwind is linked by default on x86_64 cpu when build via bazel, even though the user did not specify any flags.
Changed: 
Side effects:
---

Fix libunwind linked by default on x86_64 cpu when building via bazel

---

src/bthread/list_of_abafree_id.h
test/baidu_thread_local_unittest.cpp

GCC 13 no longer transitively includes <cstdint> from other standard library headers. This causes compilation failures for code using types like uint32_t and uintptr_t without explicitly including <cstdint>.
This commit Fix UT compilation errors with GCC 13 due to missing <cstdint> includes
The errors were:
- error: 'uintptr_t' was not declared in this scope
- error: 'uint32_t' does not name a type
This change ensures compatibility with GCC 13 while maintaining backward compatibility with older compiler versions.
Reference: https://gcc.gnu.org/gcc-13/porting_to.html
cmake building error under gcc13.3
```
cmake -B build -DBUILD_UNIT_TESTS=ON && cmake --build build -j16
```
```
/home/yxc/code/2505/brpc/test/baidu_thread_local_unittest.cpp: In function ‘void {anonymous}::fun3(void*)’: …
```

Fix UT compilation errors with GCC 13 due to missing <cstdint> includes

---

src/brpc/policy/thrift_protocol.cpp

Issue Number:
https://github.com/apache/brpc/blob/c24e641009fa0305f0efebce694d0dad886c85ca/src/brpc/policy/thrift_protocol.cpp#L112-L123
p is `char*`, so `*p = htonl(seq_id);` can not set seq_id(a uint32_t variable) to buf.
Changed:
Side effects:
---

Fix incorrect sequence id setting in thrift message begin

---

src/butil/macros.h

Issue Number:
Changed:
Side effects:
---

Support macro to disable move

---

src/bthread/timer_thread.cpp

During shutdown, `stop_and_join()` sets `_stop = true`, sets `_nearest_run_time = 0`, and calls `futex_wake_private()` to wake up the timer thread. However, due to a race condition, the timer thread may:
1. See `_stop == false` and enter the loop.
2. Block on acquiring `_mutex` while `stop_and_join()` holds it.
3. After `stop_and_join()` releases the mutex, the timer thread acquires it and sets `_nearest_run_time = int64_max`, **overwriting the earlier** `_nearest_run_time = 0`.
4. Miss the wake-up signal because at the time `stop_and_join()` called `futex_wake_private()`, the timer thread had not yet entered futex wait.
As a result, after finishing all remaining tasks, the timer thread may enter futex wait **with no further wake-up**, causing the program to hang on `pthread_join`. …

Fix race condition that causes TimerThread to hang during shutdown

---

src/brpc/policy/consistent_hashing_load_balancer.cpp
src/brpc/policy/consistent_hashing_load_balancer.h

Issue Number:2993
Changed:
1. 在判断Node是否相同时，依次比较hash/server_addr/tag
2. 在生成hash时，包含tag。
Side effects:
---

Consistent hashing support server tag

---

docs/cn/rdma.md
src/brpc/channel.cpp
src/brpc/input_messenger.cpp
src/brpc/rdma/rdma_endpoint.cpp
src/brpc/rdma/rdma_endpoint.h
src/brpc/rdma/rdma_helper.cpp
src/brpc/rdma/rdma_helper.h
src/brpc/server.cpp
src/brpc/socket.cpp
src/brpc/span.cpp
src/butil/iobuf.cpp

Issue Number:
#1434 #2344 #1650 
RDMA支持Polling模式，使用bRPC的rdma测试工具能看到延迟明显降低。如果希望做到run-to-completion模型，需要把使用rdma的Server线程数设置成2（epoll bthread独占一个线程，另一个线程给rdma poller bthread和所有请求的bthread。），如果需要调用spdk/io_uring等异步驱动，需要设置rdma::SetPollingModeCallback， 并且设置rdma_poller_yield为true。
Changed:
Side effects:
---

rdma support polling mode

---

example/echo_c++/client.cpp
example/echo_c++/server.cpp
src/brpc/checksum.cpp
src/brpc/checksum.h
src/brpc/controller.cpp
src/brpc/controller.h
src/brpc/details/controller_private_accessor.h
src/brpc/global.cpp
src/brpc/options.proto
src/brpc/policy/baidu_rpc_meta.proto
src/brpc/policy/baidu_rpc_protocol.cpp
src/brpc/policy/crc32c_checksum.cpp
src/brpc/policy/crc32c_checksum.h
src/brpc/server.cpp
test/brpc_server_unittest.cpp

Issue Number: #2159
Implementing Checksum Functionality at the bRPC Level:
General Requirement: Similar to the compression feature, implement a unified solution at the bRPC level.
Better Performance: Implementing checksum at the user level requires users to serialize protobuf or other data packets and then calculate the checksum. Implementing it at the bRPC level allows direct use of the serialized results for checksum calculation.
Better Compatibility: Implementing checksum at the user level means users work with protobuf data packets. If the protocol changes and the client and server protocols become inconsistent, checksum calculations based on protobuf will fail, preventing users from leveraging protobuf's compatibility features.
Changed:
Side effects:
- Performance …

baidu_std support checksum

---

src/butil/endpoint.cpp

Issue Number:
Problem Summary: fix compile error in endpoint.cpp
**compile tools**: gcc 5.2 and bazel 7.2.0
Changed:
Side effects:
---

fix: Specifying the global namespace for bind and connect

---

src/brpc/selective_channel.cpp
src/brpc/socket_map.cpp
src/brpc/socket_map.h
test/brpc_socket_map_unittest.cpp

Issue Number: resolve #2998
When the health check is turned off, the SocketMap does not hold a reference to the Socket, so the Socket will be abnormally recycled when the connection is closed.
Changed:
Regardless of whether the health check is enabled, SocketMap must hold a reference to the socket.
Side effects:
---

Bugfix: Socket without health check was abnormally recycled

---

src/brpc/policy/http_rpc_protocol.cpp
test/brpc_http_rpc_protocol_unittest.cpp

…y could not be parsed by the client to get the correct error code after authentication failed
Issue Number: #3001 
Changed:
- grpc协议和http协议当前共用同一个鉴权函数，所以在鉴权函数中增加了对http协议类型的判断，如果是http2.0版本，按grpc格式返回错误
Side effects:
---

Fix the bug that the grpc protocol is incompatible with authentication(issue:#3001)

---

src/bvar/latency_recorder.cpp

Issue Number: resolve #3013
Changed:
Side effects:
---

Bugfix: LatencyRecorder::expose CHECK fails when save_series flag is false

---

src/brpc/load_balancer.h
src/brpc/policy/randomized_load_balancer.cpp
src/brpc/policy/round_robin_load_balancer.cpp
src/brpc/policy/weighted_randomized_load_balancer.cpp
src/bthread/prime_offset.h
src/bthread/task_control.cpp
src/bthread/task_control.h
src/bthread/task_group.cpp
src/bthread/task_group.h

Issue Number: resolve #1231 , resolve #2640 , resolve #2972
Changed:
`bthread_worker_usage` should consist of `_cumulated_cputime_ns` and the CPU time of the task currently run by the worker.
Side effects:
---

Bugfix: bthread_worker_usage could exceed bthread_worker_count

---

src/brpc/rdma/block_pool.cpp
src/brpc/rdma/block_pool.h
src/brpc/rdma/rdma_helper.cpp
test/brpc_block_pool_unittest.cpp

Issue Number:
rdma block pool runtime ExtendBlockPool has some error:
1. a region may has many buckets, extend a region not hold all bucket locks, will case race condition, disable runtime extend a region when buckets greater than 1.
2. when new region created, link the region to idle_list case link list break.
3. add feature, in scenarios where users need to manually specify memory regions (e.g., using hugepages or custom memory pools), when FLAGS_rdma_memory_pool_user_specified_memory is true, user is  responsibility of extending memory blocks , this ensuring flexibility for advanced use cases.
Changed:
Side effects:
---
- When providing us with a new feature, it …

bugfix: extend block pool runtime

---

src/bthread/task_tracer.cpp
src/bthread/task_tracer.h

Issue Number: Fix #3031
Problem Summary: SignalTrace mode has memory access problem
Changed: use `Result` instead of `Result *`
Side effects:
---

Bugfix: SignalTrace mode has memory access problem

---

src/bthread/task_control.cpp

Issue Number: None
In some scenarios, services may prefer to keep worker thread names unchanged, as external monitoring and alerting systems already rely on custom-defined thread names. To accommodate this, we've introduced a gflag to control whether bRPC should modify worker thread names.
When thread name modification is disabled through this configuration, users can alternatively set worker thread names within the **run_worker_startfn** function.
Changed:
Side effects:
---

add flags for set worker thread name

---

src/butil/iobuf.h

google::protobuf::int64 has been removed.
Issue Number:
Changed:
Side effects:
---

replace google::protobuf::int64 by int64_t

---

src/brpc/redis_command.cpp
src/brpc/redis_reply.cpp
test/brpc_redis_unittest.cpp

Issue Number: null
Problem Summary: redis request or response may have a too large size that cause the server to consume too much memory.
Changed: Add a limit for allocation size
Side effects:
- Performance effects: no
- Breaking backward compatibility: Some redis request/response may fail to parse if the data size exceed the default value of redis_max_allocation_size (64M). User can adjust the flag redis_max_allocation_size for their senarios.
---

Limit redis alloc size

---

src/brpc/rdma/rdma_endpoint.cpp
src/brpc/rdma/rdma_helper.cpp

Issue Number: #2265 
现有的代码中对 IB verbs API 的使用有误。很多 API 的返回值本身是错误码（errno），但并不会修改 errno.
Changed:
Side effects:
---

fix error checking against IB verbs API (#2265)

---

src/brpc/socket.cpp

Issue Number: resolve #3030 
Changed:
Side effects:
---

Bugfix: Only event dispatcher thread has flag BTHREAD_GLOBAL_PRIORITY

---

src/brpc/details/health_check.cpp
src/brpc/socket.cpp
src/brpc/socket.h

Issue Number:
Fix #3058 
Changed:
Side effects:
---

fix socket _versioned_ref can not recover && remove _hc_started flag

---

src/butil/third_party/symbolize/symbolize.cc

Issue Number: resolve  #3063 
Changed:
- Marked InstallSymbolizeOpenObjectFileCallback() as BAIDU_WEAK in src/butil/third_party/symbolize/symbolize.cc to avoid symbol collision with glog.
Side effects:
---

Fix symbol conflict with glog by marking InstallSymbolizeOpenObjectFileCallback as BAIDU_WEAK

---

cmake/CMakeLists.download_gtest.in
src/bvar/detail/combiner.h
src/bvar/recorder.h
test/bvar_recorder_unittest.cpp

Issue Number: Fix #3065
Changed:
Side effects:
---

Bugfix: _combiner is not initialized in IntRecorder constructor

---

src/brpc/rdma/rdma_helper.h
src/brpc/socket.cpp

when rdma event dispatcher unschedule is true, start ProcessEvent background
Issue Number:
In certain scenarios, such as when using SPDK, it is required that the bthread executing SPDK must run on a single thread—that is, in single-threaded polling mode. This means the bthread of the event dispatcher must continuously occupy one worker thread and must not preempt other bthreads. This ensures no scheduling occurs, preventing SPDK from being scheduled onto other worker threads.
No
Changed:
Side effects:
--- …

when rdma event dispatcher unschedule is true, start ProcessEvent background

---

src/brpc/controller.cpp
src/brpc/controller.h
src/brpc/policy/baidu_rpc_protocol.cpp

Issue Number: #3072
当前，brpc 的用户函数里（CallMethod ）无法获取 RPC 在  socket 被读取的时间点，所以存在几个问题：
1. 无法在用户代码里统计出 RPC 正确的处理总耗时：因为在用户代码里只能从 RPC 开始被处理时开始统计时间， 而实际耗时还应该包含 RPC 在 bthread 队列里的等待时间
2. 无法直接抛弃超时的RPC： 如果 RPC 在 bthread 调度队列等待的时间过长（也就是从 socket 读取到被 bthread 开始处理这个 RPC 的排队时间，我们线上偶发）， 且超过了超时时间， 这个请求应该直接被抛弃， 但是用户无法获取 RPC 到达时间， 导致无法实现这功能
所以，应该把 RPC 从 socket 读取到的时间点暴露给用户代码。
> 说明：
> 1.  brpc 中 RPC 的 received_us 并不是 RPC 达到机器网卡的时间， 也不代表用户的发送时间， 但是相对于从 CallMethod 调用后用户自己统计 RPC 耗时， received_us 相对更精确
> 2. 当前代码仅修改了 baidu_rpc， 其他的协议没支持， get_rpc_received_us 返回 0， 表示这个协议不支持
Changed:
Side effects:
---
- Please follow …

Expose the received_us of RPC to users

---

src/brpc/span.cpp
src/brpc/span.h

Issue Number: no
Hello maintainers,
This PR makes two contributions:
It replaces the C-style cast in Span class with static_cast.
During my usage of bRPC, I extended the functions of Collected and encountered a scenario where the container being sorted by SpanEarlier contained bvar::Collected* pointers that were not Span instances. This led to a crash due to the unsafe downcast.
The current implementation implicitly assumes that only Span objects will ever be passed to this comparator. While this is efficient, it's not robust against incorrect usage.
Changed:
Using static_cast instead of a C-style cast is a modern C++ best practice. It improves code quality by:
Type Safety: It provides compile-time checks for the validity of the cast within the type hierarchy.
Clarity: It …

Refactor: Use static_cast for safer downcasting in brpc::Span

---

.github/workflows/ci-macos.yml

Issue Number:
https://github.com/apache/brpc/actions/runs/17352439325/job/49260866694?pr=2985
```shell
Homebrew requires formulae to be in a tap, rejecting:
./homebrew-formula/protobuf.rb
```
Changed:
Side effects:
---

Fix macos ci

---

src/brpc/input_messenger.cpp
src/brpc/rdma/block_pool.cpp
src/brpc/rdma/rdma_endpoint.h

Issue Number:
When both rdma_memory_pool_max_regions and rdma_memory_pool_buckets are greater than 1, dynamic memory expansion may cause concurrent modification issues in the memory linked list due to lock contention problems. To address this, we increase the region_num count for each block_type. Dynamic memory expansion is only permitted when both of the following conditions are met:
rdma_memory_pool_buckets equals 1
g_info->region_num[block_type] is less than 1
Changed:
Side effects:
---
- Please follow [Contributor Covenant Code of Conduct](https://github.com/apache/brpc/blob/master/CODE_OF_CO …

rdma runtime extend block restriction

---

src/bthread/timer_thread.cpp

add a gflag for brpc timer bucket count
Issue Number:
Changed:
Side effects:
---

add flag for brpc timer buckets count

---

.github/workflows/ci-linux.yml
.gitignore
BUILD.bazel
src/bthread/task_tracer.cpp

Issue Number: resolve #3110
Changed:
Side effects:
---

bazel: fix with_bthread_tracer config setting
