apache/brpc

- .gitignore
- Dockerfile
docker env is easier for people test/compiling brpc. BTW,  can you provide an official image in the dockerhub? 
Thanks
> add dockerfile

- src/brpc/controller.cpp
In brpc src/brpc/controller.cpp doesn't deal with the SIGTERM but it should.
> add SIGTERM handle for brpc controller

- src/brpc/redis_command.cpp
- test/brpc_redis_unittest.cpp
> fix redis cmd_format bug in the empty string case

- docs/cn/memory_management.md
Unrecognizabel Characters marked by red frame as follows:
> Fix unrecognizable characters in memory_management.md

- docs/cn/getting_started.md
add deps when install on MacOS
> add deps when install on MacOS

- test/brpc_ssl_unittest.cpp
- test/bthread_setconcurrency_unittest.cpp
use "google" may cause compile error .
> use GFLAGS_NS instead of google

- docs/cn/new_protocol.md
- docs/en/new_protocol.md
update the new_protocol.md about new  support protocols
> update new_protocol.md doc to add new support protocols

- src/butil/endpoint.cpp
> support for SO_REUSEPORT socket option

- src/brpc/redis_command.cpp
- src/brpc/redis_reply.cpp
- test/brpc_redis_unittest.cpp
1. Flush previous component when beginning and ending quotes
2. Escape quote symbols in quoted contents
3. Quote backslash and doublequote when printing redis messages
4. Print better logs for unmatched quotes
> Make escaping and quoting in redis more reasonable

- src/butil/time.cpp
- src/butil/time.h
修正获取CPU基准频率的操作（原实现获取的是动态频率而非基准频率），增加两种方法
> fix read_invariant_cpu_frequency

- src/brpc/controller.cpp
在pooled模式下，[sending_sock可能会先被回收](https://github.com/brpc/brpc/blob/4fec80cb2434712017a7f512a430e8a17b42a157/src/brpc/controller.cpp#L724)，之后再调用GetOrNewSharedPart时，就会直接New一个SharedPart。导致数据无法被正确反馈到CircuitBreaker。
> CircuitBreaker_Bug_Fix

- src/brpc/circuit_breaker.cpp
- src/brpc/circuit_breaker.h
在熔断的初始化期间使用error rate来判断是否需要熔断。
> circuit_breaker optimization 

- src/brpc/builtin/connections_service.cpp
> fix rtt display in connection page

- src/brpc/policy/redis_protocol.cpp
- src/brpc/redis.cpp
- src/brpc/redis.h
- src/brpc/redis_reply.cpp
- src/brpc/redis_reply.h
> Fix redis parse

- src/brpc/socket.cpp
https://github.com/brpc/brpc/issues/643
> Fix check failed in WaitAndReset

- docs/cn/circuit_breaker.md
> add doc for circuit breaker

- src/brpc/global.cpp
- src/brpc/load_balancer.cpp
- src/brpc/load_balancer.h
- src/brpc/policy/consistent_hashing_load_balancer.cpp
- src/brpc/policy/consistent_hashing_load_balancer.h
- src/brpc/policy/dynpart_load_balancer.cpp
- src/brpc/policy/dynpart_load_balancer.h
- src/brpc/policy/hasher.cpp
- src/brpc/policy/hasher.h
- src/brpc/policy/locality_aware_load_balancer.cpp
- src/brpc/policy/locality_aware_load_balancer.h
- src/brpc/policy/randomized_load_balancer.cpp
- src/brpc/policy/randomized_load_balancer.h
- src/brpc/policy/round_robin_load_balancer.cpp
- src/brpc/policy/round_robin_load_balancer.h
- src/brpc/policy/weighted_round_robin_load_balancer.cpp
- src/brpc/policy/weighted_round_robin_load_balancer.h
- src/brpc/socket.h
- test/brpc_load_balancer_unittest.cpp
1. lb 支持字符串配置项格式 "lb_name:key1=value1 key2=value2 ...."
2. 重构consistency hash lb使得能够接受各种形式的hash函数
3. 增加了一个ketama consistency hash的lb
> lb configurable && consistency hash lb refactor

- docs/cn/bvar.md
- docs/en/bvar.md
- src/brpc/builtin/prometheus_metrics_service.cpp
- src/brpc/builtin/prometheus_metrics_service.h
- src/brpc/builtin_service.proto
- src/brpc/details/server_private_accessor.h
- src/brpc/server.cpp
- src/brpc/server.h
- test/brpc_prometheus_metrics_unittest.cpp
> customize brpc metrics path

- src/brpc/ssl_options.h
> modify code: src/brpc/ssl_options.h annotation ciper to cipher

- src/brpc/details/naming_service_thread.h
Fix https://github.com/apache/incubator-brpc/issues/909
> Initialize use_rdma to false

- CMakeLists.txt
- src/bthread/context.cpp
- src/bthread/context.h
- src/bthread/processor.h
- src/butil/third_party/snappy/snappy-internal.h
- src/butil/third_party/snappy/snappy-stubs-internal.h
update libcontext
fix compile error
add compilation options
> adapt to Arm64

- src/brpc/controller.cpp
Controller::Call 的拷贝构造函数中没有对enable_circuit_breaker赋值，会导致backup request不会触发熔断相关逻辑
> enable circuit breaker for backup request

- tools/gdb_bthread_stack.py
contribute my own gdb script, which can get active bthread stack trace, only support running process
> tools: add gdb_bthread_stack.py

- src/butil/containers/hash_tables.h
- test/endpoint_unittest.cpp
the another optional solution of Issue #1007
make right of the hash function of HashInts32.
> bugfix to the hash function HashInts32.

- src/brpc/circuit_breaker.cpp
> ignore ELIMIT for circuit breaker

- src/brpc/channel.cpp
> fix h2_req check failed when retry after ELIMIT error

- CHANGES.md
I create this file and add the first section for 0.9.8-rc01 to log release
> add release note file since 0.9.8-rc01

- .asf.yaml
update brpc info on github about page
> add .asf.yaml to set github about info

- .bazelrc
- BUILD
- WORKSPACE
- openssl.BUILD
- src/brpc/span.h
- src/bthread/key.cpp
- src/bthread/task_group.cpp
- src/butil/find_cstr.cpp
- src/butil/find_cstr.h
- test/baidu_thread_local_unittest.cpp
- test/bthread_futex_unittest.cpp
- test/file_util_unittest.cc
- zlib.BUILD
testing on 11.0-bigsur. This pr also fixes #1260
> Fix bazel build in macos

- CMakeLists.txt
- example/rdma_performance/client.cpp
- src/brpc/rdma/rdma_communication_manager.cpp
- src/brpc/rdma/rdma_completion_queue.cpp
- src/brpc/rdma/rdma_completion_queue.h
- src/brpc/rdma/rdma_endpoint.cpp
- src/brpc/rdma/rdma_endpoint.h
- src/brpc/rdma/spsc_queue.h
- src/brpc/server.cpp
- src/brpc/socket.cpp
- test/brpc_naming_service_unittest.cpp
- test/brpc_redis_unittest.cpp
1) fd leak when destroy rdma cq channel; 
2) listen on incorrect internal port when using rdma
> fix two bugs about rdma

- src/brpc/policy/discovery_naming_service.cpp
- test/brpc_naming_service_unittest.cpp
See API here at https://github.com/bilibili/discovery/blob/master/doc/api.md#%E6%B3%A8%E5%86%8Cregister
> Fix registering multiple addresses to discovery

- docs/cn/bvar_c++.md
Very tiny change. but if you read the document and copy the sample source code from the markdown file. You will compile with error message.
> Change chinese quotation marks in bvar_c++.md sample code

- src/bvar/detail/series.h
> fix warning in gcc8+

- docs/cn/client.md
- docs/en/client.md
- src/brpc/global.cpp
- src/brpc/policy/weighted_randomized_load_balancer.cpp
- src/brpc/policy/weighted_randomized_load_balancer.h
- test/brpc_load_balancer_unittest.cpp
implement weighted randomized load balancer
> implement weighted randomized load balancer #1254

- tools/rpc_view/rpc_view.cpp
> rpc_view support setting timeout

- src/brpc/socket.cpp
> Fix Socket::WaitAndReset memory leak 

- docs/cn/flatmap.md
> Add FlatMap example code

- .travis.yml
- docs/cn/thrift.md
- docs/en/thrift.md
> Fix apache thrift download failed

- community/oncall.md
> add oncall.md

- Dockerfile
docker scan image report one high severity vulnerability found in base image.
it is still 16.04,
so I upgrade it to 20.04 version.
> upgrade baseimage to 20.04

- src/brpc/policy/baidu_rpc_protocol.cpp
1. channel的连接模式设置为single
2. 客户端并发发起创建stream的请求
2. 服务端出现限流或者overcrowded等状态（为了快速复现，可以把max_concurrency设置很小）
3. 客户端解析服务端返回数据，报解析错误（PARSE_ERROR_ABSOLUTELY_WRONG)
当客户端使用baidu_rpc协议发起创建新的stream请求（创建Stream）时，服务端判断限流或者拥堵，直接报错，不再处理请求。(baidu_rpc_protocol.cpp)。这样的后果是服务端的`brpc::StreamAccept`没有执行，服务端stream socket没有创建，controller的repsonse_stream就没有设置。
```cpp
void ProcessRpcRequest(InputMessageBase* msg_base) {
......
if (!server->IsRunning()) {
cntl->SetFailed(ELOGOFF, "Server is stopping");
break;
}
if (socket->is_overcrowded()) {
cntl->SetFailed(EOVERCROWDED, "Connection to %s is overcrowded",
butil::endpoint2str(socket->remote_side()).c_str());
break;
}
if (!server_accessor.AddConcurrency(cntl.get())) {
cntl->SetFailed(
ELIMIT, "Reached server's max_concurrency=%d",
server->options().max_concurrency); …
```
> Fix a bug that server will send unexpected data frame to client if there are errors occur during processing stream create request

- community/release_cn.md
gpg --edit-key gpg --edit-key lorinlee  does not work
need to change to gpg --edit-key lorinlee
> update gnp edit command options

- src/bvar/status.h
> fix status

- tools/BUILD
Add bazel support to https://github.com/apache/incubator-brpc/blob/master/docs/cn/rpc_replay.md
> Add rpc_replay BUILD file

- docs/cn/getting_started.md
> docs: fix typo

- src/brpc/details/load_balancer_with_naming.cpp
will close: #1684 
similar PR: #1415
> change a log level fatal to error

- test/bthread_work_stealing_queue_unittest.cpp
> Fix work_stealing_queue_unittest for ARM.

- src/brpc/server.cpp
- src/brpc/server.h
- test/brpc_server_unittest.cpp
> Implement brpc server Start(PortRange, const ServerOptions*)

- src/butil/containers/flat_map.h
- src/butil/containers/flat_map_inl.h
- test/flat_map_unittest.cpp
insert(const std::pair<key_type, mapped_type>& kv)
> Implement FlatMap insert(const std::pair<key_type, mapped_type>& kv)

- docs/cn/rpcz.md
- src/bthread/task_group.cpp
- src/bthread/types.h
- test/bthread_unittest.cpp
Solve #1491
Related: #505
This feature has been used in Baidu for years.
> Support inherit span on bthread create

- src/butil/containers/flat_map.h
> flat_map: fix code annotation

- docs/cn/error_code.md
- docs/en/error_code.md
> 对齐源码中阈值默认值

- docs/cn/auto_concurrency_limiter.md
> update doc for auto_concurrency_limiter

- docs/cn/auto_concurrency_limiter.md
auto concurrency limiter: update doc to make it consisten with the code
> auto concurrency limiter: update doc to make it consisten with the code

- docs/cn/getting_started.md
- docs/en/getting_started.md
> doc: update compiling with cmake

- .github/workflows/license-eyes.yml
- .licenserc.yaml
- example/thrift_extension_c++/echo.thrift
- package/rpm/brpc.spec
> Add skywalking license eyes

- src/brpc/controller.cpp
- src/brpc/controller.h
- src/brpc/details/controller_private_accessor.h
- src/brpc/policy/redis_authenticator.cpp
- src/brpc/policy/redis_authenticator.h
- src/brpc/policy/redis_protocol.cpp
- src/brpc/socket.cpp
- src/brpc/socket.h
> redis auth support select db

- src/brpc/policy/http_rpc_protocol.cpp
fix: h2 ProcessHttpRequest request_protocol is modified to  PROTOCOL_H2
> Fix(h2 protocol): ProcessHttpRequest

- test/bvar_recorder_unittest.cpp
> Fix test_bvar fail on mac

- test/brpc_socket_unittest.cpp
Fix the slow test https://app.travis-ci.com/github/apache/incubator-brpc/jobs/580274145
> Fix the slow test in brpc_socket_unittest.cpp

- src/bthread/butex.cpp
- test/bthread_cond_bug_unittest.cpp
Fixed #617 issue, put "erase_from_butex_and_wakeup" into "wait_for_butex" to strong guarantee the execution sequence.
> Fix bug butex_wait failed with timeout

- .github/pull_request_template.md
Signed-off-by: fan <yfan3763@gmail.com>
Issue Number: https://github.com/apache/incubator-brpc/issues/1951
Problem Summary: we don't have a pull request template.
Changed:
Side effects:
---
> add pull_request_template.md

- community/oncall.md
Issue Number:
Changed:
Side effects:
---
> community: Update oncall.md

- .github/pull_request_template.md
Fix Contributor Covenant Code of Conduct link
> Update pull_request_template.md Contributor Covenant Code of Conduct link

- CODE_OF_CONDUCT.md
email address: [dev@brpc.apache.org](mailto:dev@brpc.apache.org)
> Update CODE_OF_CONDUCT.md email address

- community/newcommitter_en.md
Issue Number:
Changed:
Side effects:
---
> community: adjust markdown format

- docs/en/rdma.md
Issue Number: None
Problem Summary: Found some typos in docs/en/rdma.md
Changed: Fix typos in docs/en/rdma.md
Side effects:
- Performance effects(性能影响): None
- Breaking backward compatibility(向后兼容性):  None
---
> fix typos in rdma documentation

- src/butil/iobuf.cpp
Issue Number: #1988
Problem Summary: warning信息的标点符号位置错误
Changed: 修改标点符号位置
Side effects:
- Breaking backward compatibility(向后兼容性):  是的
---
> fix warning message error

- docs/en/bvar_c++.md
add english version of bvar_c++.md
> Create bvar_c++.md under docs/en

- .github/workflows/ci_linux.yml
Issue Number: #1963 
Linux流水线 先提交一部分，本周再提交几次
Changed:
Side effects:
---
> Linux workflow

- docs/cn/getting_started.md
Issue Number:
There is issue of markdown format in doc/cn/getting_started.md
[docker][#docker]  =>   [docker](#docker)
Changed:
[docker][#docker]  =>   [docker](#docker)
Side effects:
- Breaking backward compatibility(向后兼容性):  No
---
> Fix format issue of doc/cn/getting_started.md.

- tools/rpc_replay/rpc_replay.cpp
https://github.com/apache/incubator-brpc/actions/runs/3559564054/jobs/5979002361
> Fix MacOS warning: bool literal returned from 'main' [-Wmain]

- src/bvar/multi_dimension.h
- src/bvar/multi_dimension_inl.h
- test/bvar_multi_dimension_unittest.cpp
Issue Number: #2040 
Problem Summary: MultiDimension add delete_stats and has_stats interface
Changed: See Problem Summary
Side effects:
- Breaking backward compatibility(向后兼容性): No
---
> mbvar support delete_stats and has_stats interface

- docs/cn/http_client.md
Issue Number: no
Problem Summary: some words repeated.
Changed: delete duplicate error in http_client.md file.
Side effects:
- Performance effects(性能影响): no
- Breaking backward compatibility(向后兼容性): yes 
---
> fix http_client.md duplicate error

- docs/cn/mbvar_c++.md
> optimize mbvar doc

- community/oncall.md
Signed-off-by: lei he <lhestz@163.com>
Issue Number:
Changed:
Side effects:
---
> update oncall.md from Dec 19th to Dec 25th

- src/brpc/details/mesalink_ssl_helper.cpp
- src/brpc/details/ssl_helper.cpp
- src/brpc/server.cpp
- src/brpc/server.h
- src/brpc/socket.cpp
Issue Number:
Changed:
Side effects:
---
> fix some typos

- docs/cn/mbvar_c++.md
- src/brpc/parallel_channel.h
> WIP: fix doc && code style

- community/apache-package-validator.sh
- community/release_cn.md
- community/release_en.md
- community/releasecheck.md
Issue Number: #2078 
Changed:
Side effects:
---
> Update release steps for TLP

- package/rpm/brpc.spec
- tools/parallel_http/CMakeLists.txt
- tools/rpc_press/CMakeLists.txt
- tools/rpc_replay/CMakeLists.txt
- tools/rpc_view/CMakeLists.txt
- tools/trackme_server/CMakeLists.txt
Issue Number: NONE
Changed:
Side effects:
---
> Install and pack brpc tools

- README.md
Add hyperlink to https://brpc.apache.org/
Problem Summary: Adding hyperlink at the start of the sentence makes to easy to get the website without having to scroll up to the sidebar
Changed: README.md
---
> Update README.md, add hyperlink to site

- community/release_cn.md
- community/release_en.md
Issue Number: close #2101 
Changed:
Side effects:
---
> Update release steps

- src/brpc/policy/domain_naming_service.cpp
Issue Number:
Changed:
Side effects:
---
> feat: dns resolve support ipv6

- src/brpc/socket.cpp
Issue Number:
Changed:
Side effects:
---
> Fix memory leak of socket

- docs/cn/flatmap.md
Issue Number:
Changed:
Side effects:
---
> Provide an example of FlatMap that erases element during iteration

- src/brpc/data_factory.h
Issue Number:
Changed:
Side effects:
---
> Fix comment typo in DataFactory

- src/butil/strings/string_piece.h
Issue Number:
Changed:
Side effects:
---
> fix: typo of StringPiece

- src/bvar/variable.cpp
- src/bvar/variable.h
- test/bvar_variable_unittest.cpp
Issue Number:
Changed:
Side effects:
---
> bvar add is_hidden 

- src/brpc/rdma/rdma_endpoint.h
- src/brpc/rdma/rdma_helper.cpp
Issue Number:
Changed:
Side effects:
---
> RdmaResource disallow copy and assign

- src/brpc/server.cpp
Issue Number:
Changed:
Side effects:
---
> Remove wordexp

- test/brpc_load_balancer_unittest.cpp
Issue Number:
Add performance unittest of DoublyBufferedData
Changed:
Side effects:
---
> Add performance unittest of DoublyBufferedData

- community/release_cn.md
…n of brpc by using envs
Issue Number:
Changed:
Side effects:
---
> get ride of the annoying replacement work by using envs

- src/brpc/input_messenger.cpp
- src/brpc/socket.cpp
- src/brpc/socket.h
- src/brpc/socket_inl.h
- test/brpc_socket_unittest.cpp
Issue Number: #1895 
Changed:
Side effects:
---
> Support TCP heartbeat of client

- src/brpc/http2.h
Issue Number: #2240 
Changed: 补充缺失的头文件
Side effects:
- Breaking backward compatibility(向后兼容性): 无
---
> Fix compilation errors reported by GCC-13

- src/brpc/channel.h
Issue Number:
Changed:
Add comments about load balancer in brpc/channel.h to make it same with the doc
Side effects:
---
> Update comments for load balancer at channel

- src/bthread/task_group.cpp
Issue Number:
Changed:
Side effects:
- Breaking backward compatibility(向后兼容性): No
---
> add missing BAIDU_GET_VOLATILE_THREAD_LOCAL in task_group.cpp

- src/butil/string_printf.cpp
Issue Number:
Changed:
Side effects:
---
> Fix typo of comment  in string_printf

- .github/workflows/ci-macos.yml
- homebrew-formula/protobuf.rb
Issue Number:
Changed:
Side effects:
---
> Fix macos ci failed with protobuf version

- src/butil/memory/ref_counted.h
Issue Number:
Changed:
Side effects:
---
> scoped_refptr add move constructor

- src/brpc/policy/weighted_round_robin_load_balancer.cpp
- src/brpc/policy/weighted_round_robin_load_balancer.h
- test/brpc_load_balancer_unittest.cpp
Issue Number:
Changed:
Side effects:
---
> Fix typo of load balancer

- README.md
- README_cn.md
Issue Number:
Changed:
Side effects:
---
> Opt README doc for rdma

- src/brpc/controller.cpp
- src/brpc/details/naming_service_thread.cpp
- src/brpc/http_method.cpp
- src/brpc/policy/dynpart_load_balancer.cpp
- src/bthread/countdown_event.cpp
- src/butil/containers/doubly_buffered_data.h
- src/butil/logging.h
- src/butil/macros.h
- src/butil/memory/scoped_ptr.h
- src/butil/scoped_generic.h
- src/bvar/detail/agent_group.h
- src/bvar/mvariable.cpp
- src/bvar/variable.cpp
- test/brpc_channel_unittest.cpp
Issue Number:
Changed:
Side effects:
---
> Support release assert

- docs/cn/http_service.md
- docs/cn/nshead_service.md
- docs/cn/server.md
- docs/en/http_service.md
- docs/en/server.md
Issue Number: 无
Problem Summary: 部分文档在vscode中打开会提示`The character U+00a0 is invisible.`
Changed: 使用空格替换文档中的`U+00a0`不可见字符
Side effects:
- Performance effects(性能影响): 否
- Breaking backward compatibility(向后兼容性): 是 
---
> Replace invisible U+00a0 characters with spaces in doc

- src/bvar/mvariable.cpp
Issue Number:
Changed:
Side effects:
---
> make bvar_max_dump_multi_dimension_metric_number modifiable

- src/brpc/policy/http_rpc_protocol.cpp
Issue Number: https://github.com/apache/brpc/issues/2334
Problem Summary: 非grpc的h2协议无法解析gzip数据。
Changed: 当使用h2+gzip访问brpc server时，能正确解压数据并反序列化。
Side effects:
- Performance effects(性能影响):  无
- Breaking backward compatibility(向后兼容性):  是
---
> fix normal h2 with gzip data

- src/brpc/details/http_message.cpp
- test/brpc_http_message_unittest.cpp
Issue Number: Fix  #1610
Changed:
Side effects:
---
> Fix HTTP no content of 1xx and 204

- src/brpc/builtin/rpcz_service.cpp
- src/brpc/controller.cpp
- src/brpc/controller.h
Issue Number:
Changed:
Side effects:
---
> Escape span method name

- docs/cn/execution_queue.md
- src/bthread/execution_queue.cpp
- src/bthread/execution_queue.h
- src/bthread/execution_queue_inl.h
- test/bthread_execution_queue_unittest.cpp
Issue Number:
Changed:
ExecutionQueue支持使用pthread来执行任务。
Side effects:
---
> Support pthread mode for ExecutionQueue

- src/bvar/multi_dimension.h
- src/bvar/multi_dimension_inl.h
- test/bvar_multi_dimension_unittest.cpp
Issue Number: #2404 
Changed:
Side effects:
---
> Add mbvar clear_stats method

- src/brpc/controller.cpp
Issue Number: #2395
Changed:
Side effects:
---
> Fix RetryPolicy blocks health check

- src/bthread/context.cpp
- src/bthread/context.h
- src/bthread/processor.h
- src/butil/atomicops.h
- src/butil/atomicops_internals_loongarch64_gcc.h
- src/butil/build_config.h
- src/butil/debug/debugger_posix.cc
- src/butil/time.h
- test/bthread_work_stealing_queue_unittest.cpp
Issue Number: 
https://github.com/apache/brpc/issues/2363
Add support for LoongArch64
Changed:
Side effects:
No
No
---
> Add support for loongarch64

- docs/en/server.md
Fixes a typo.
Changed: spelling in server.md
Side effects: No side effect
---
> [Typo fixed in server.md]

- src/brpc/server.h
Issue Number:
Changed:
Side effects:
---
> Remove useless and

- README.md
Fixes #2433 
Fixed the typo error in readme file.
Looking forward for merging the PR.
Issue Number: #2433 
Changed: Fixed a small typo error under readme file.
Side effects:
---
> Fixed the typo error

- src/brpc/policy/weighted_round_robin_load_balancer.cpp
Issue Number:
wrr添加兜底策略
Changed:
wrr添加兜底策略，防止节点较少时, 开启了backup request，但选取节点失败
Side effects:
---
> add wrr lb fallback strategy

- src/brpc/builtin/hotspots_service.cpp
Issue Number:
Changed:
Side effects:
---
> Support max width of flame graph image

- docs/cn/load_balancing.md
- src/brpc/socket.h
- test/brpc_socket_unittest.cpp
> remove the docs and comments related to HealthCheckThread

- src/brpc/controller.cpp
- src/brpc/controller.h
- src/brpc/policy/baidu_rpc_meta.proto
- src/brpc/policy/baidu_rpc_protocol.cpp
- test/brpc_server_unittest.cpp
Issue Number: #2405、#1479
支持用户在请求或者响应中添加一些通用属性，无需修改上层协议。
Changed:
Side effects:
---
> Support user fields of baidu protocol

- example/asynchronous_echo_c++/server.cpp
- example/http_c++/http_server.cpp
Issue Number: fix #2481
Changed:
Side effects:
---
> Fix json2pb compile error of examples

- src/brpc/reloadable_flags.cpp
- src/brpc/reloadable_flags.h
Issue Number:
Changed:
Side effects:
---
> Support uint32 reloadable flags

- src/brpc/policy/memcache_binary_protocol.h
Issue Number:
Changed:
Side effects:
---
> fix typo about memcache_binary_protocol

- README.md
- README_cn.md
Issue Number:
Changed:
Side effects:
---
> Fix bRPC case

- src/brpc/rdma/rdma_endpoint.cpp
Issue Number:
Changed:
Side effects:
---
> modify GetGlobalEventDispatcher for rdma

- test/mpsc_queue_unittest.cc
Issue Number:
#2492 合入后，好像影响了UT，导致UT出错或者被跳过了。
Changed:
Side effects:
---
> Fix MPSCQueue UT

- src/bthread/fd.cpp
- src/bthread/unstable.h
- src/butil/endpoint.cpp
- src/butil/endpoint.h
- src/butil/fd_utility.cpp
- src/butil/fd_utility.h
- src/butil/memory/scope_guard.h
- test/bthread_fd_unittest.cpp
- test/endpoint_unittest.cpp
- test/mpsc_queue_unittest.cc
Issue Number:
Changed:
connect支持超时功能。
Side effects:
---
> Support timed connect for both bthread and pthread

- src/butil/containers/mpsc_queue.h
Issue Number:
Changed:
Side effects:
---
> fix MPSCQueue memory not released with `DefaultAllocator`

- src/butil/logging.cc
Issue Number:
Changed:
Side effects:
---
> Support bthread id for log

- test/CMakeLists.txt
- test/Makefile
- test/scope_guard_unittest.cc
Issue Number:
Changed:
Side effects:
---
> Add UT of ScopeGuard

- .github/workflows/ci-linux.yml
Issue Number:
Changed:
安装gdb，是得ci运行UT出现coredump时能打印堆栈。
Side effects:
---
> Install gdb for linux ci

- .github/workflows/ci-macos.yml
Issue Number: #2591
Changed:
Side effects:
---
> ci: fixed protobuf and abseil versions

- src/butil/iobuf_profiler.cpp
Issue Number:
Changed:
Side effects:
---
> Fix IOBuf profiler rate

- community/release_cn.md
- community/release_en.md
Issue Number: https://github.com/apache/brpc/pull/2705
Problem Summary: add manual for update version for MODULE.bazel in release step
Changed: update document only
Side effects:
---
> Add release doc about update version in MODULE.bazel

- .github/pull_request_template.md
Issue Number:
Changed:
Side effects:
---
> Fix link of CODE_OF_CONDUCT.md in pull request template

- src/butil/containers/mpsc_queue.h
Issue Number:
Changed:
Side effects:
---
> fix mpsc queue cur enqueue node to atomic exhange

- src/brpc/channel.h
Issue Number:
Changed:
允许bRPC外部的代码调用CheckHealth函数来检测channel是否健康。这个功能在网易的Curve项目中有线上的使用，目前是通过编译时打patch来维护的，希望官方能给支持。
Side effects:
---
> Make CheckHealth public for users to use this function.

- test/CMakeLists.txt
Issue Number: https://github.com/apache/brpc/issues/2770
Problem Summary: cmake编译unittest失败
Changed: cmake编译脚本加入缺失的文件
Side effects:
- Breaking backward compatibility(向后兼容性):  无
---
> fix unittest on cmake

- src/brpc/socket.cpp
Issue Number: resolve #2490
Changed:
Side effects:
---
> Fix Socket check failed with invalid fd of Stream

- test/brpc_alpn_protocol_unittest.cpp
Issue Number:
Changed:
Side effects:
---
> Add required headers to fix unittest compilation

- CMakeLists.txt
Issue Number: resolve #2805
Changed:
Side effects:
---
> Support user specific CMAKE_MODULE_PATH

- .github/workflows/cifuzz.yml
Issue Number:
Problem Summary: upgrade upload-artifact version according to [1] and [2]
[1]: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
[2]: https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md
Changed:
Side effects:
---
> Upgrade upload-artifact version

- src/brpc/nonreflectable_message.h
Issue Number: #2829
* https://github.com/protocolbuffers/protobuf/commit/a626dd332f177e110afd3eef71728e5951d8f3a0
* https://github.com/protocolbuffers/protobuf/commit/49bb305147392ecdc65234b4b03b51de66e02e48
Changed:
Side effects:
---
> Support Protobuf v29

- docs/cn/getting_started.md
- docs/en/getting_started.md
Issue Number:
Changed:
Side effects:
---
> docs: update build requirements

- src/butil/thread_key.h
- test/thread_key_unittest.cpp
Issue Number:
Changed:
Side effects:
---
> Remove redundant const of ThreadLocal

- community/release_cn.md
- community/release_en.md
Issue Number:
Changed:
Side effects:
---
> Fix release documents

- BUILD.bazel
- MODULE.bazel
Issue Number: https://github.com/apache/brpc/issues/2845
Changed: no
Side effects:
---
> Fix build on macos with apple M1 chip

- src/butil/containers/doubly_buffered_data.h
Issue Number: resolve #2397
Changed:
Side effects:
---
> Remove the unused INVALID_PTHREAD_KEY

- test/bthread_cond_unittest.cpp
Issue Number:
Changed:
Side effects:
---
> Disable CondTest.too_many_bthreads_from_bthread in asan ut

- src/bvar/detail/combiner.h
- src/bvar/detail/percentile.cpp
- src/bvar/detail/percentile.h
- src/bvar/recorder.h
- src/bvar/reducer.h
Issue Number: resolve #2937 
Changed:
Side effects:
---
> Fix thread safety of AgentCombiner

- src/brpc/policy/http_rpc_protocol.cpp
- src/brpc/server.cpp
- src/butil/containers/doubly_buffered_data.h
- src/json2pb/pb_to_json.cpp
Issue Number: resolve #2937
Changed:
Side effects:
---
> Fix thread safety of Wrapper

- src/bthread/task_tracer.cpp
Issue Number: #2983 
Problem Summary: `TaskTracer::TraceImpl`, did not set the relevant variables(`m->traced`) on all return paths, which would cause a deadlock.
use `BRPC_SCOPE_EXIT` to ensure `m->traced==false` on all return paths.
Changed: src/bthread/task_tracer.cpp `TaskTracer::TraceImpl()` function
Side effects:
- Performance effects: No
- Breaking backward compatibility: No
---
> Fix bthread task tracer deadlock bug (issue #2983)

- src/brpc/rdma/rdma_helper.cpp
Issue Number:
Changed:
Engineering equivalent implementation, when I need to use multiple versions of ibverbs.so in actual applications, it is easier to expand.
Side effects:
- Performance effects: no
- Breaking backward compatibility: no
---
> optimize the fallback code style

- docs/cn/server.md
Just document enhancement
Just document enhancement
> Enhance doc for server.md

- src/bvar/multi_dimension.h
Issue Number:
Changed:
Side effects:
---
> Bugfix: MultiDimension::set_max_stats_count should be public
